### ISSUE TITLE
Variable name typo in ansible_windows.pdf

### ISSUE THREAD

**Issue by nylou2020** [ansible/workshops#1006]
##### SUMMARY

Within the "ansible_windows.pdf" deck, there is a variable name typo on pages 52 - 57.
The typo is in the win_service module.
The correct variable should be:     name: " {{ service_name }}"
![ansible_windows_deck_WrongVarName](https://user-images.githubusercontent.com/67385513/97448100-a265a280-1906-11eb-8044-061e34817bf2.png)

No. I did not know this.  Well, I guess I do now.

##### ISSUE TYPE
- Documentation Report --> See the deck:  ansible_windows.pdf

**Comment by cloin** [comment]
Fixed. Thanks for the issue @nylou2020 !
