### ISSUE TITLE
Ansible Security Workshop Pscx task error

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1010]
##### SUMMARY

provisioning issue:

TASK [windows_ws_setup : Install Pscx needed for unzip step later] *************
fatal: [d543-student1-windows_ws]: FAILED! => {"changed": false, "msg": "Problems adding a prerequisite module PowerShellGet No match was found for the specified search criteria and module name 'PowerShellGet'. Try Get-PSRepository to see all available registered module repositories.", "nuget_changed": false, "output": "", "repository_changed": false}

##### ISSUE TYPE

 - Bug Report

**Specific TASK**
 - name: Install Pscx needed for unzip step later
    win_psmodule:
      name: pscx
      allow_clobber: true

**Comment by IPvSean** [comment]
is this still an issue or did it get fixed? @rhjcd

**Comment by liquidat** [comment]
This is a random problem which occurs only once in a while. From what we know, this is an error of AWS or the windows DSC repositories, nothing we can fix.
