### ISSUE TITLE
RHPDS Security Workshop error

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1016]
**PROD GUID with example:  d543**

TASK [windows_ws_setup : Install Pscx needed for unzip step later] *************
fatal: [d543-student1-windows_ws]: FAILED! => {"changed": false, "msg": "Problems adding a prerequisite module PowerShellGet No match was found for the specified search criteria and module name 'PowerShellGet'. Try Get-PSRepository to see all available registered module repositories.", "nuget_changed": false, "output": "", "repository_changed": false}

**Related TASK:**

 - name: Install Pscx needed for unzip step later
    win_psmodule:
      name: pscx
      allow_clobber: true

**Suggest Fix:**

add an 'until loop'

**Comment by liquidat** [comment]
@rhjcd We already have a rescue step here: https://github.com/ansible/workshops/blob/0c066b0c3dd23a5b7127801b5279a009d2401dd9/provisioner/roles/windows_ws_setup/tasks/main.yml#L26
Can you please check if that error happened in the rescue step? And if this error brought it into the rescue step to begin with?

I am wondering how long such a loop should wait...

**Comment by liquidat** [comment]
Seems to be a hick up which only rarely comes up. Closing.
