### ISSUE TITLE
Estimated Lab Time

### ISSUE THREAD

**Issue by duboyd** [ansible/workshops#1028]
It would help to have an estimated Lab Time Completion in the decks to help facilitators who are running this for the first time know how to allot time properly within the context of the overall time allocations. I know it varies, but I think you can get a general estimate.

**Comment by cigamit** [comment]
This is what we typically did for the Windows Workshop.  Something like this could be adjusted for all the Workshops.
https://github.com/mgmt-sa-tiger-team/skylight/blob/master/docs/AGENDA.md

**Comment by cloin** [comment]
Yeah I think something like this could be beneficial and could also be added to the exercise divider slides of the workshop decks. @cigamit, field SAs would know the timing better. I wouldn’t mind making the proper edits.

**Comment by IPvSean** [comment]
can you elaborate on what you mean?  Which workshop?  For Network Automation each exercise has an amount of time we created on the slide at the exercise section->
![image](https://user-images.githubusercontent.com/6537680/100273464-d397b980-2f2a-11eb-98ac-c21aed25fb05.png)

do you mean in general?

**Comment by IPvSean** [comment]
@duboyd can you provide more info?

**Comment by abenokraitis** [comment]
Closing due to lack of feedback
