### ISSUE TITLE
issues with License key for workshop

### ISSUE THREAD

**Issue by RedHatSE** [ansible/workshops#1029]
issue with license on Ansible it now requires a subscription manfest. 
![manifest](https://user-images.githubusercontent.com/58218812/99585511-6fb64380-29b4-11eb-8923-256b31c443d0.png)

```

**Comment by Spredzy** [comment]
Please make sure you are sticking to 3.7.3 version (or anything <3.8.0) that has been released few hours ago and that introduces a change in the way license are handled.

Default code https://github.com/ansible/workshops/blob/60f5fccabeba7a33d1946a959201136f6b77a579/provisioner/roles/control_node/tasks/tower.yml#L2-L5

**Comment by cloin** [comment]
This is a known change in newly released tower version 3.8. We haven’t yet figured out a solution for workshops and will continue with 3.7.3 until then.
