### ISSUE TITLE
RHEL Supplemental Exercises 404

### ISSUE THREAD

**Issue by ffirg** [ansible/workshops#1045]
##### SUMMARY
The link for return to workshop index is broken in https://ansible.github.io/workshops/exercises/ansible_rhel/supplemental/
It points to https://ansible.github.io/workshops/exercises/ which no longer exists.

##### ISSUE TYPE
 - Bug Report

**Comment by IPvSean** [comment]
fixed on `devel` will be fixed with next release to `master`, thank you for contributing @ffirg
