### ISSUE TITLE
Security Workshop: QRadar logs not visible

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1070]
##### SUMMARY

-  Logging is not visible in QRadar after completing all prior steps in the demo. 
- This issue is in the deployed RHPDS environment for demo, "Ansible Security Demo" in the Ansible Demos catalog.

**Link to instructions:**   
Step is 1.6:
https://ansible.github.io/workshops/exercises/ansible_security/2.1-enrich/

**Link to repo:**
https://github.com/ansible/workshops/tree/devel/exercises/ansible_security/2.1-enrich

**Comment by liquidat** [comment]
Confirmed. QRadar does not show any logs at all. We are on it.

**Comment by liquidat** [comment]
Issue seems to be related to this: [UPDATED: A QRadar deploy changes on 31 December 2020 can impact product functionality
](https://www.ibm.com/support/pages/node/6395080)
