### ISSUE TITLE
Ansible workshop slides include broken example in inventory

### ISSUE THREAD

**Issue by Seandersont** [ansible/workshops#1122]
The second half of this line, found on pg 34 of the ansible for rhel workshop slide deck does not work

node-[1:30] ansible_host=10.42.0.[31:60]

I believe this example is included in several of the other workshops, but the range on the variable does not work, and the ini (or yml) file will only parse it as a string. ie. for node-1, ansible_host will be 10.42.0.[31:60], not 10.42.0.31 as this suggests.

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
hey roger did this get removed? @rlopez133

**Comment by IPvSean** [comment]
any update @rlopez133 ?

**Comment by rlopez133** [comment]
I'll take a look at this tomorrow @IPvSean
