### ISSUE TITLE
[Ansible Provisioner] Error in docker build

### ISSUE THREAD

**Issue by type954** [ansible/workshops#1128]
An error occurs when building with the dockerfile below.
What is the problem?

docker build --no-cache -t "ansible_workshop:dockerfile" .
-------- dockerfile --------
FROM python:alpine

RUN set -ex && apk –update add rpm openssh-client openssl ca-certificates wget && apk –update add –virtual build-dependencies python3-dev libffi-dev openssl-dev cargo build-base && pip3 install –upgrade pip pycrypto cffi && pip3 install setuptools wheel && pip3 install cryptography && pip3 install ansible && pip3 install jinja2 && pip3 install netaddr && pip3 install pbr && pip3 install hvac && pip3 install jmespath && pip3 install ruamel.yaml && pip3 install boto && pip3 install boto3 && pip3 install passlib && pip3 install paramiko && pip3 install urllib3 && apk del build-dependencies && rm -rf /var/cache/apk/* && mkdir -p /etc/ansible && echo ‘localhost’ > /etc/ansible/hosts

ENV ANSIBLE_GATHERING smart ENV ANSIBLE_HOST_KEY_CHECKING false ENV ANSIBLE_RETRY_FILES_ENABLED false ENV ANSIBLE_ROLES_PATH /ansible/playbooks/roles ENV ANSIBLE_SSH_PIPELINING True ENV PYTHONPATH /ansible/lib ENV PATH /ansible/bin:$PATH ENV ANSIBLE_LIBRARY /ansible/library

WORKDIR /ansible/playbooks

ENTRYPOINT [“ansible-playbook”]
---------------------------

---- error ------
[+] Building 3.3s (5/6)
 => [internal] load build definition from Dockerfile                                                       0.0s
 => => transferring dockerfile: 1.10kB                                                                     0.0s
 => [internal] load .dockerignore                                                                          0.0s
 => => transferring context: 2B                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:alpine                                           1.3s
 => CACHED [1/3] FROM docker.io/library/python:alpine@sha256:2438776142e82a0d33adce3b801e4ad92d35e294f777  0.0s
 => ERROR [2/3] RUN set -ex && apk –update add rpm openssh-client openssl ca-certificates wget && apk     1.9ss
------
 > [2/3] RUN set -ex && apk –update add rpm openssh-client openssl ca-certificates wget && apk –update add –virtual build-dependencies python3-dev libffi-dev openssl-dev cargo build-base && pip3 install –upgrade pip pycrypto cffi && pip3 install setuptools wheel && pip3 install cryptography && pip3 install ansible && pip3 install jinja2 && pip3 install netaddr && pip3 install pbr && pip3 install hvac && pip3 install jmespath && pip3 install ruamel.yaml && pip3 install boto && pip3 install boto3 && pip3 install passlib && pip3 install paramiko && pip3 install urllib3 && apk del build-dependencies && rm -rf /var/cache/apk/* && mkdir -p /etc/ansible && echo ‘localhost’ > /etc/ansible/hosts:
#5 0.362 + apk '–update' add rpm openssh-client openssl ca-certificates wget
#5 0.366 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
#5 1.216 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
#5 1.837 ERROR: unable to select packages:
#5 1.888   add (no such package):
#5 1.888     required by: world[add]
#5 1.888   –update (no such package):
#5 1.888     required by: world[–update]
------
executor failed running [/bin/sh -c set -ex && apk –update add rpm openssh-client openssl ca-certificates wget && apk –update add –virtual build-dependencies python3-dev libffi-dev openssl-dev cargo build-base && pip3 install –upgrade pip pycrypto cffi && pip3 install setuptools wheel && pip3 install cryptography && pip3 install ansible && pip3 install jinja2 && pip3 install netaddr && pip3 install pbr && pip3 install hvac && pip3 install jmespath && pip3 install ruamel.yaml && pip3 install boto && pip3 install boto3 && pip3 install passlib && pip3 install paramiko && pip3 install urllib3 && apk del build-dependencies && rm -rf /var/cache/apk/* && mkdir -p /etc/ansible && echo ‘localhost’ > /etc/ansible/hosts]: exit code: 2

**Comment by IPvSean** [comment]
I somehow never saw this issue go by... but I have no idea what you are trying to do?  We don't support a dockerfile anywhere I am aware?  I just did a search on dockerfile and came up with only an exercise that @rhcreynold had done... I am not sure if his team is still using that workshop type or not?

Can you provide more info @type954

**Comment by IPvSean** [comment]
no info provided
