### ISSUE TITLE
Windows Ex 8 variable names are missing for chocolatey install

### ISSUE THREAD

**Issue by dpullman-emergent** [ansible/workshops#1145]
##### SUMMARY

The variable names for the task Install specific versions of packages sequentially are blank for name, version, and loop. Also the variables for the debug message in the last task are missing completely.

This appears to be the exercise image on https://ansible.github.io/workshops/exercises/ansible_windows/8-chocolatey/. I'm seeing the variable names on github.com version of the README.md.

I've attached a screenshot.

##### ISSUE TYPE
- Documentation Report
![Screen Shot 2021-04-21 at 15 07 15](https://user-images.githubusercontent.com/63753805/115607876-850d0200-a2b3-11eb-95aa-c422c93cb53a.png)

**Comment by dpullman-emergent** [comment]
Sorry, should have included expected version.
  - name: Install specific versions of packages sequentially
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    loop: "{{ choco_packages }}"

  - debug:
      msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}

Attached screenshot of README.md from https://github.com/ansible/workshops/tree/devel/exercises/ansible_windows/8-chocolatey
![Screen Shot 2021-04-22 at 16 46 34](https://user-images.githubusercontent.com/63753805/115783243-9d038500-a38a-11eb-9193-e7a15555d392.png)

**Comment by ffirg** [comment]
This has been fixed in a previous issue I raised but github.io needs a refresh to pick up.

**Comment by dpullman-emergent** [comment]
I agree, you can see the correct names in the code, it's just github.io that is lacking.

**Comment by IPvSean** [comment]
this looks solved now: https://ansible.github.io/workshops/exercises/ansible_windows/8-chocolatey/

sorry for slow response... been heads down with Ansiblefest 2021... please reopen if this is still an issue @ffirg or @dpullman-emergent
