### ISSUE TITLE
Rhel_90 Workshop exercise navigation not working.

### ISSUE THREAD

**Issue by owainow** [ansible/workshops#1159]
### Problem Summary

The navigation at the bottom of each exercise for previous or next seems to reference a previous repo structure and as a result, returns a 404 when clicked. Needs to be updated with the new structure (1.2 -> 2) across all exercises. Cheers. 

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

N/A

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

N/A

**Comment by IPvSean** [comment]
This is fixed
