### ISSUE TITLE
hosts section in apache_install.yml is inconsistent with workshop-examples

### ISSUE THREAD

**Issue by saito-hideki** [ansible/workshops#1169]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

**Description:**
In 2.3-projects/README.md,  the`hosts` section in apache_install.yml is inconsistent with workshop-examples. However, we already have the PR(ansible/workshop-examples/pull/3) for `workshop-examples`.

So I opened this issue for tracking for the status of the PR(ansible/workshop-examples/pull/3).

**ansible/workshop-examples**
- https://github.com/ansible/workshop-examples/blob/master/rhel/apache/apache_install.yml#L2-L3

**ansible/workshops**
- https://github.com/ansible/workshops/blob/devel/exercises/ansible_rhel/2.3-projects/README.md

In this case, I think the hosts sections in workshops is correct:

```
---
- name: Apache server installed
  hosts: all
```

**Comment by IPvSean** [comment]
issue is solved by merge of 1169
