### ISSUE TITLE
Windows gitlab get_certificate failure

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#1173]
### Problem Summary

Intermittent failure here: 
![image (2)](https://user-images.githubusercontent.com/8515817/119380658-0549cd00-bc8f-11eb-9e62-361eccda0e1b.png)

https://github.com/ansible/workshops/blob/c784d0d288c1678870b79b5feb11c86f29b08735/provisioner/roles/gitlab-server/tasks/add-users.yml#L13

### Issue Type

Bug

### Extra vars file

ci

### Ansible Playbook Output

screenshot above

### Ansible Version

ci

### Ansible Configuration

ci

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

ci

**Comment by craig-br** [comment]
It looks like letsencrypt is throttling the CI

`[2021-05-25T00:37:00.327Z]     There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/`

Windows workshop successfully deployed on my AWS account, pointing toward this being specific to CI.
