### ISSUE TITLE
https://ansible.github.io/workshops/exercises/ansible_windows/ needs a refresh for RHPDS labs

### ISSUE THREAD

**Issue by ffirg** [ansible/workshops#1178]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

https://ansible.github.io/workshops/exercises/ansible_windows/ needs a refresh so it picks up the fix for exercise 8 missing loop info and the new workflow exercise 9.

**Comment by anshulbehl** [comment]
https://github.com/ansible/workshops/pull/1206 has been merged to fix this.
