### ISSUE TITLE
ERROR! Invalid callback for stdout specified: community.general.yaml

### ISSUE THREAD

**Issue by nirvkot** [ansible/workshops#1196]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

Hello for all!
Some issue with chapter workshops/exercises/ansible_rhel/1.3-playbook/
"Writing Your First Playbook".
After:
[student<X>@ansible-1 ansible-files]$ ansible-playbook apache.yml
We have an error like:
ERROR! Invalid callback for stdout specified: community.general.yaml

The workaround that we've found - change ".ansible.cfg file:
[defaults]
stdout_callback = community.general.yaml

to:
[defaults]
stdout_callback = yaml

**Comment by cbolz** [comment]
I just ran into this as well. It seems to be caused by commit 9d0d8693c24a6b8323c8645e39614517bae06f1c

We could also instruct the student to install the callback plugin with
````
ansible-galaxy collection install community.general
````

Personally, I would leave it out entirely since I believe this is too much of a challenge too early in the workshop.

**Comment by goetzrieger** [comment]
@IPvSean

**Comment by abenokraitis** [comment]
Sean is on PTO this whole week. @liquidat  could you take a look?

**Comment by liquidat** [comment]
@goetzrieger @cbolz @cloin I am about to remove the callback line from the `ansible.cfg` - or do you see any place where this is used throughout the workshop?

**Comment by liquidat** [comment]
Looks like the networking workshop uses this:
https://ansible.github.io/workshops/exercises/ansible_network/3-facts/
