### ISSUE TITLE
Ansible Linux Automation Workshop (L) - student-node(s) not accessible

### ISSUE THREAD

**Issue by bosebc** [ansible/workshops#1198]
### Area

Other

### Proposed Changes

User says..
**I noticed that studen17-node3 and student45-node3  with respective IPs 54.93.218.250 and 3.67.69.51 are not responding to simple ssh connection and I have no way to restart those instances.**

Here is the guid. Service "RHPDS-RH-idhaoui-redhat.com-PROD_ANSIBLE_WORKSHOPS-22ab_COMPLETED"

Team, kindly check. Thanks

**Comment by cloin** [comment]
Hello! Thank you for opening an issue. Please provide additional information related to provisioning of this workshop. We are not able to retrieve logs by guid.

**Comment by cloin** [comment]
@bosebc need more info here or will close out.

**Comment by bosebc** [comment]
Thanks @cloin for your reply. I've informed the requestor to follow-up on this issue. 
Please keep this for few days. If no reply then you may proceed to close.
Thanks

**Comment by cloin** [comment]
@bosebc Sounds good. Closing now but you can reopen any time with additional information.
