### ISSUE TITLE
F5 Workshops failing with undefined Variable offline_token

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#1224]
### Problem Summary

Did multiple deployments in the past and never had this issue, something new looks like new variable required?

### Issue Type

Bug

### Extra vars file

ec2_region: us-west-2
ec2_name_prefix: MMABIS-AnsibleGH-Test
student_total: 1
workshop_type: f5
admin_password: supersecretpass!
doubleup: no
## Optional Variables
dns_type: aws
workshop_dns_zone: "mydemo.net"
create_login_page: true
autolicense: false
towerinstall: false
ibm_community_grid: false

### Ansible Playbook Output

[root@Elysium provisioner]# ansible-playbook provision_lab.yml -e @/git/vars/f5_vars.yml
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callback_enabled instead. This feature will be removed from ansible-core in version 2.15. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[WARNING]: Skipping callback plugin 'time', unable to load
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

PLAY [Perform Checks to make sure this Playbook will complete successfully] *********************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [build workshop into collection] ***********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [install newly created collection] *********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Delete content & directory] ***************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [run pre-check role to make sure workshop will complete provisioning] **********************************************************************************************************************************************************************

TASK [ansible.workshops.workshop_check_setup : make sure we are running correct Ansible Version] ************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure workshop_type is set to a correct value] ***********************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure dns_type is set to a correct value] ****************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure network_type is set to a correct value] ************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : make sure DNS name is 65 characters or less] *****************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure security_console is set to a correct value] ********************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : make sure we are not running with TESTWORKSHOP as the name so no overlap] ************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure we are not using `ansible` as the password] ********************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : automation controller checks] ********************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : check workshop specific information] *************************************************************************************************************************************************************
included: /root/.ansible/collections/ansible_collections/ansible/workshops/roles/workshop_check_setup/tasks/unsupported_workshop.yml for localhost => (item=/root/.ansible/collections/ansible_collections/ansible/workshops/roles/workshop_check_setup/tasks/unsupported_workshop.yml)

TASK [ansible.workshops.workshop_check_setup : unsupported workshop for workshop_check_setup role] **********************************************************************************************************************************************
ok: [localhost] =>
  msg: no more setup for workshop_check_setup role the f5 does not have any specific setup specified

TASK [run AWS check setup if using AWS] *********************************************************************************************************************************************************************************************************

TASK [ansible.workshops.aws_check_setup : grab boto version] ************************************************************************************************************************************************************************************
changed: [localhost]

TASK [ansible.workshops.aws_check_setup : make sure we are running correct boto version] ********************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.aws_check_setup : check for underscores in workshop name] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.aws_check_setup : does route53 zone exist] ******************************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : make sure workshop_dns_zone is owned by your account] *************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.aws_check_setup : FIND AZ ZONE FOR REGION us-west-2] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : Remove any AZs in the aws_az_deny_list when defined] **************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : Output AWS Availability Zones (AZs)] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.aws_check_setup : SET AZ ZONE TO FIRST AVAILABLE] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : grab information about AWS user] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : print whoami] *****************************************************************************************************************************************************************************************
ok: [localhost] =>
  whoami:
    account: '250871914685'
    account_alias: ''
    arn: arn:aws:iam::250871914685:user/mmabis_programmatic_access
    changed: false
    failed: false
    user_id: AIDATU2JBUC6625ELDI2A

TASK [ansible.workshops.aws_check_setup : save username of AWS user] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : save account id of AWS user] **************************************************************************************************************************************************************************
ok: [localhost]

TASK [download AAP] *****************************************************************************************************************************************************************************************************************************

TASK [ansible.workshops.aap_download : Generating an access token] ******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'offline_token' is undefined

    The error appears to be in '/root/.ansible/collections/ansible_collections/ansible/workshops/roles/aap_download/tasks/main.yml': line 3, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

    # https://access.redhat.com/articles/3626371#bgenerating-an-access-tokenb-4
    - name: Generating an access token
      ^ here

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
localhost                  : ok=23   changed=4    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

### Ansible Version

ansible [core 2.11.2]
  config file = /git/workshops/provisioner/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 2.11.2
  libyaml = False

### Ansible Configuration

[root@Elysium provisioner]# ansible-config dump --only-changed
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callback_enabled instead. This feature will be removed from ansible-core in version 2.15. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/git/workshops/provisioner/ansible.cfg) = ['time']
DEFAULT_FORKS(/git/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/git/workshops/provisioner/ansible.cfg) = ['/git/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/git/workshops/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/git/workshops/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/git/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/git/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/git/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/git/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/git/workshops/provisioner/ansible.cfg) = False
[root@Elysium provisioner]# ansible-config dump --only-changed
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callback_enabled instead. This feature will be removed from ansible-core in version 2.15. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/git/workshops/provisioner/ansible.cfg) = ['time']
DEFAULT_FORKS(/git/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/git/workshops/provisioner/ansible.cfg) = ['/git/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/git/workshops/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/git/workshops/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/git/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/git/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/git/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/git/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/git/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

[root@Elysium provisioner]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by IPvSean** [comment]
nice catch.... I am working on getting workshops moved to AAP 2.0.... 

try doing this...->

```
cd your_local_path/workshops
ansible-galaxy collection build --verbose --force --output-path build/
ansible-galaxy collection install --verbose --force-with-deps build/*.tar.gz
```

effectively instead of downloading from `ansible.workshops` on galaxy this will install the collection locally from the version you are on and should work.  I have been quickly interating the galaxy roles as I am testing them and this usually wouldn't affect others b/c they are using our RHPDS.... 

sorry about this, once AAP 2.0 move happens this will be much more stable

**Comment by VDI-Tech-Guy** [comment]
Hey @IPvSean - The Fix didnt work


[root@Elysium workshops]# ansible-galaxy collection build --verbose --force --output-path build/
Using /root/.ansible.cfg as config file
Created collection for ansible.workshops at /git/workshops/build/ansible-workshops-0.0.10.tar.gz
[root@Elysium workshops]# ansible-galaxy collection install --verbose --force-with-deps build/*.tar.gz
Using /root/.ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'ansible.workshops:0.0.10' to '/root/.ansible/collections/ansible_collections/ansible/workshops'
Downloading https://galaxy.ansible.com/download/awx-awx-19.2.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/awx-awx-19.2.2-4ymjfka4
ansible.workshops:0.0.10 was installed successfully
Installing 'awx.awx:19.2.2' to '/root/.ansible/collections/ansible_collections/awx/awx'
Downloading https://galaxy.ansible.com/download/amazon-aws-1.5.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/amazon-aws-1.5.0-js6nhgxl
awx.awx:19.2.2 was installed successfully
Installing 'amazon.aws:1.5.0' to '/root/.ansible/collections/ansible_collections/amazon/aws'
Downloading https://galaxy.ansible.com/download/arista-eos-2.1.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/arista-eos-2.1.2-v4w685r9
amazon.aws:1.5.0 was installed successfully
Installing 'arista.eos:2.1.2' to '/root/.ansible/collections/ansible_collections/arista/eos'
Downloading https://galaxy.ansible.com/download/ansible-netcommon-2.0.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/ansible-netcommon-2.0.2-3htocb3v
arista.eos:2.1.2 was installed successfully
Installing 'ansible.netcommon:2.0.2' to '/root/.ansible/collections/ansible_collections/ansible/netcommon'
Downloading https://galaxy.ansible.com/download/ansible-posix-1.2.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/ansible-posix-1.2.0-ots5laaz
ansible.netcommon:2.0.2 was installed successfully
Installing 'ansible.posix:1.2.0' to '/root/.ansible/collections/ansible_collections/ansible/posix'
Downloading https://galaxy.ansible.com/download/ansible-product_demos-1.2.7.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/ansible-product_demos-1.2.7-rpblq00i
ansible.posix:1.2.0 was installed successfully
Installing 'ansible.product_demos:1.2.7' to '/root/.ansible/collections/ansible_collections/ansible/product_demos'
Downloading https://galaxy.ansible.com/download/ansible-windows-1.5.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/ansible-windows-1.5.0-_ifjjpi2
ansible.product_demos:1.2.7 was installed successfully
Installing 'ansible.windows:1.5.0' to '/root/.ansible/collections/ansible_collections/ansible/windows'
Downloading https://galaxy.ansible.com/download/chocolatey-chocolatey-1.1.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/chocolatey-chocolatey-1.1.0-pccya9zu
ansible.windows:1.5.0 was installed successfully
Downloading https://galaxy.ansible.com/download/cisco-ios-2.0.1.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/cisco-ios-2.0.1-zirb5yge
Installing 'chocolatey.chocolatey:1.1.0' to '/root/.ansible/collections/ansible_collections/chocolatey/chocolatey'
chocolatey.chocolatey:1.1.0 was installed successfully
Installing 'cisco.ios:2.0.1' to '/root/.ansible/collections/ansible_collections/cisco/ios'
Downloading https://galaxy.ansible.com/download/community-aws-1.5.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/community-aws-1.5.0-ajyp7jey
cisco.ios:2.0.1 was installed successfully
Installing 'community.aws:1.5.0' to '/root/.ansible/collections/ansible_collections/community/aws'
Downloading https://galaxy.ansible.com/download/community-crypto-1.6.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/community-crypto-1.6.2-5f8r6tf6
community.aws:1.5.0 was installed successfully
Installing 'community.crypto:1.6.2' to '/root/.ansible/collections/ansible_collections/community/crypto'
Downloading https://galaxy.ansible.com/download/community-general-3.0.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/community-general-3.0.2-sd6e26vm
community.crypto:1.6.2 was installed successfully
Installing 'community.general:3.0.2' to '/root/.ansible/collections/ansible_collections/community/general'
Downloading https://galaxy.ansible.com/download/community-mysql-2.1.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/community-mysql-2.1.0-6it5bu39
community.general:3.0.2 was installed successfully
Installing 'community.mysql:2.1.0' to '/root/.ansible/collections/ansible_collections/community/mysql'
Downloading https://galaxy.ansible.com/download/community-windows-1.3.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/community-windows-1.3.0-2247n41d
community.mysql:2.1.0 was installed successfully
Installing 'community.windows:1.3.0' to '/root/.ansible/collections/ansible_collections/community/windows'
Downloading https://galaxy.ansible.com/download/f5networks-f5_modules-1.9.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/f5networks-f5_modules-1.9.0-ptrk3jb9
community.windows:1.3.0 was installed successfully
Installing 'f5networks.f5_modules:1.9.0' to '/root/.ansible/collections/ansible_collections/f5networks/f5_modules'
Downloading https://galaxy.ansible.com/download/junipernetworks-junos-2.1.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/junipernetworks-junos-2.1.0-hfa900nt
f5networks.f5_modules:1.9.0 was installed successfully
Installing 'junipernetworks.junos:2.1.0' to '/root/.ansible/collections/ansible_collections/junipernetworks/junos'
Downloading https://galaxy.ansible.com/download/redhat_cop-tower_configuration-1.0.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/redhat_cop-tower_configuration-1.0.2-5q4nc22b
junipernetworks.junos:2.1.0 was installed successfully
Installing 'redhat_cop.tower_configuration:1.0.2' to '/root/.ansible/collections/ansible_collections/redhat_cop/tower_configuration'
Downloading https://galaxy.ansible.com/download/redhat_cop-tower_utilities-0.3.2.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/redhat_cop-tower_utilities-0.3.2-gzioeqtv
redhat_cop.tower_configuration:1.0.2 was installed successfully
Downloading https://galaxy.ansible.com/download/ansible-utils-2.3.0.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/ansible-utils-2.3.0-g0fa_n8k
Installing 'redhat_cop.tower_utilities:0.3.2' to '/root/.ansible/collections/ansible_collections/redhat_cop/tower_utilities'
redhat_cop.tower_utilities:0.3.2 was installed successfully
Installing 'ansible.utils:2.3.0' to '/root/.ansible/collections/ansible_collections/ansible/utils'
Downloading https://galaxy.ansible.com/download/containers-podman-1.6.1.tar.gz to /root/.ansible/tmp/ansible-local-280790k5atv0v/tmp2yrafas_/containers-podman-1.6.1-7l71rtdh
ansible.utils:2.3.0 was installed successfully
Installing 'containers.podman:1.6.1' to '/root/.ansible/collections/ansible_collections/containers/podman'
containers.podman:1.6.1 was installed successfully
[root@Elysium workshops]# ls
assets      build        decks  docs       files       images    LICENSE   meta      pooneliner.py  README.ja.md  requirements.yml  test-requirements.txt
bindep.txt  _config.yml  demos  exercises  galaxy.yml  _layouts  Makefile  po4a.cfg  provisioner    README.md     roles             tox.ini
[root@Elysium workshops]# cd provisioner/
[root@Elysium provisioner]# ls
ansible.cfg  devops.yml  group_vars  inventory       network.yml        qradar.yml  requirements_security.yml  rhel.yml  sample_workshops  smart_mgmt.yml  teardown_lab.yml  windows.yml
demo.yml     f5.yml      hosts       middleware.yml  provision_lab.yml  README.md   rhel_90.yml                roles     security.yml      splunk.yml      tests
[root@Elysium provisioner]# ansible-playbook provision_lab.yml -e @/git/vars/f5_vars.yml
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callback_enabled instead. This feature will be removed from ansible-core in version 2.15. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[WARNING]: Skipping callback plugin 'time', unable to load
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

PLAY [Perform Checks to make sure this Playbook will complete successfully] *********************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [build workshop into collection] ***********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [install newly created collection] *********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Delete content & directory] ***************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [run pre-check role to make sure workshop will complete provisioning] **********************************************************************************************************************************************************************

TASK [ansible.workshops.workshop_check_setup : make sure we are running correct Ansible Version] ************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure workshop_type is set to a correct value] ***********************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure dns_type is set to a correct value] ****************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure network_type is set to a correct value] ************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : make sure DNS name is 65 characters or less] *****************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure security_console is set to a correct value] ********************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : make sure we are not running with TESTWORKSHOP as the name so no overlap] ************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : make sure we are not using `ansible` as the password] ********************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.workshop_check_setup : automation controller checks] ********************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.workshop_check_setup : check workshop specific information] *************************************************************************************************************************************************************
included: /root/.ansible/collections/ansible_collections/ansible/workshops/roles/workshop_check_setup/tasks/unsupported_workshop.yml for localhost => (item=/root/.ansible/collections/ansible_collections/ansible/workshops/roles/workshop_check_setup/tasks/unsupported_workshop.yml)

TASK [ansible.workshops.workshop_check_setup : unsupported workshop for workshop_check_setup role] **********************************************************************************************************************************************
ok: [localhost] =>
  msg: no more setup for workshop_check_setup role the f5 does not have any specific setup specified

TASK [run AWS check setup if using AWS] *********************************************************************************************************************************************************************************************************

TASK [ansible.workshops.aws_check_setup : grab boto version] ************************************************************************************************************************************************************************************
changed: [localhost]

TASK [ansible.workshops.aws_check_setup : make sure we are running correct boto version] ********************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.aws_check_setup : check for underscores in workshop name] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.aws_check_setup : does route53 zone exist] ******************************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : make sure workshop_dns_zone is owned by your account] *************************************************************************************************************************************************
ok: [localhost] => changed=false
  msg: All assertions passed

TASK [ansible.workshops.aws_check_setup : FIND AZ ZONE FOR REGION us-west-2] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : Remove any AZs in the aws_az_deny_list when defined] **************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : Output AWS Availability Zones (AZs)] ******************************************************************************************************************************************************************
skipping: [localhost]

TASK [ansible.workshops.aws_check_setup : SET AZ ZONE TO FIRST AVAILABLE] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : grab information about AWS user] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : print whoami] *****************************************************************************************************************************************************************************************
ok: [localhost] =>
  whoami:
    account: '250871914685'
    account_alias: ''
    arn: arn:aws:iam::250871914685:user/mmabis_programmatic_access
    changed: false
    failed: false
    user_id: AIDATU2JBUC6625ELDI2A

TASK [ansible.workshops.aws_check_setup : save username of AWS user] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [ansible.workshops.aws_check_setup : save account id of AWS user] **************************************************************************************************************************************************************************
ok: [localhost]

TASK [download AAP] *****************************************************************************************************************************************************************************************************************************

TASK [ansible.workshops.aap_download : Generating an access token] ******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'offline_token' is undefined

    The error appears to be in '/root/.ansible/collections/ansible_collections/ansible/workshops/roles/aap_download/tasks/main.yml': line 3, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

    # https://access.redhat.com/articles/3626371#bgenerating-an-access-tokenb-4
    - name: Generating an access token
      ^ here

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
localhost                  : ok=23   changed=4    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

**Comment by rlopez133** [comment]
Hi @VDI-Tech-Guy ,

There is a new required variable "offline_token" added in order to authenticate calls to the Red Hat APIs. 

Within your extra_vars.yml you'll need to add the following:
```
# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "eyQ.60y_ezoosYst_FJlZfVsud9qGbDt7QRly6nhprqVEREi......XYZ"
```

Just go to that https://access.redhat.com/management/api site, generate your offline token and supply it in the offline_token variable within extra_vars.yml and you should be good to go.

**Comment by rlopez133** [comment]
@VDI-Tech-Guy - I also just realized you will need 2 additional parameters as well in the extra_vars.yml

```
redhat_username: <username>
redhat_password: <pw>
```

This corresponds with your access.redhat.com account and is needed for podman authentication in order to download the Execution Environment images.

**Comment by rlopez133** [comment]
If you need further assistance, feel free to reopen the issue.
