### ISSUE TITLE
Linux workshop: Spend less time creating files, more time learning Ansible

### ISSUE THREAD

**Issue by benblasco** [ansible/workshops#1226]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

In my experience, the Linux Automation workshop is a bit too long, and occasionally gets lost in needless detail that detracts from the overall message and also consumes time that could be better spent understanding the fundamental concepts.

One such example of this is all the html and other template type files that need to be created in Part 1: Ansible Engine exercises.  

In order to make this easier for students, I wrote my own automation that pre-populates their environment with the appropriate directories and configuration files for the first few exercises.

[https://github.com/benblasco/ansible_linux_workshop/tree/main/workshop_2021_help](https://github.com/benblasco/ansible_linux_workshop/tree/main/workshop_2021_help)

Perhaps this could either be incorporated into the environment generation, and the exercises be tweaked.  Otherwise I am happy to share this automation so people can pre-populate the environment at their discretion.

**Comment by IPvSean** [comment]
hey @benblasco sorry for delays on some github issues, we have been heads-down with AAP 2 refresh for all workshops 

tagging our awesome TMM @rlopez133 to take a look, he literally mentioned to me today that he wanted to do this

**Comment by benblasco** [comment]
Can work with you on this one @rlopez133

**Comment by rlopez133** [comment]
Hey @benblasco ! Yeah I'm going to take a look at the stuff you built and see if I can at the very least pump some of that into the environment.

**Comment by rlopez133** [comment]
@benblasco - check that PR out and by all means I'm open to feedback to make it better.

**Comment by IPvSean** [comment]
@rlopez133 can we close this bug? is this good now @benblasco ?

**Comment by rlopez133** [comment]
@IPvSean should be able to close. This should of fixed: https://github.com/ansible/workshops/pull/1354

**Comment by benblasco** [comment]
Good stuff @IPvSean and @rlopez133 

My next crusade is to try and make time to review the exercises again and try to tighten the instructions and the wording up.  I think we can make this workshop really strong with some minor tweaks.

Ok with closure.
