### ISSUE TITLE
Fedora 34 - One time setup instructions fail

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1242]
### Problem Summary

Instructions for One-time setup do not work on Fedora 34
docs/setup.md

`[root@centos ~]# dnf install python3-boto \
python3-boto3 \
python3-netaddr \
python3-passlib \
python3-pywinrm \
python3-requests \
python3-requests-credssp`

Provisioner fails at `grab boto version` task

### Issue Type

Bug

### Extra vars file
workshop_type: security
security_console: qradar

offline_token: **

redhat_username: **
redhat_password: **

dns_type: aws

admin_password: **
windows_password: **
workshop_dns_zone: rhdemo.io

controllerinstall: true
create_cluster: false
ibm_community_grid: false
use_manifest: true

### Ansible Playbook Output

Failed at task `grab boto3 version`

### Ansible Version

Ansible [core 2.11.3] 
  config file = /home/craig/workshops/ansible/workshops_repo/provisioner/ansible.cfg
  configured module search path = ['/home/craig/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/craig/.virtualenvs/ansible_latest/lib/python3.9/site-packages/ansible
  ansible collection location = /home/craig/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/craig/.virtualenvs/ansible_latest/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True

### Ansible Configuration

[defaults]
interpreter_python = auto_silent
stdout_callback = community.general.yaml
inventory      = hosts
forks          = 50
host_key_checking = False
retry_files_enabled = False
no_target_syslog = False
callback_whitelist = time
[ssh_connection]
scp_if_ssh = True

[persistent_connection]
connect_timeout = 60
command_timeout = 60

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 34 x86

**Comment by craig-br** [comment]
@craig-br

**Comment by craig-br** [comment]
Fix is to install using pip. I'll create a PR after ASA workshop is updated

**Comment by rlopez133** [comment]
Hey @craig-br , this shouldn't need pip and we should avoid pip when possible.

Looking at Fedora 34, `python3-boto` is in the System repo.

```
Last metadata expiration check: 0:29:42 ago on Fri 13 Aug 2021 10:22:12 AM CDT.
python3-boto-2.49.0-8.fc34.noarch : A simple, lightweight interface to Amazon Web Services
Repo        : @System
Matched from:
Provide    : python3-boto = 2.49.0-8.fc34
```

**Comment by craig-br** [comment]
Hey @rlopez133 Did you have any issues following the guide? If not, I'll close it

**Comment by rlopez133** [comment]
@craig-br I didn't for finding those packages on F34.

**Comment by craig-br** [comment]
@rlopez133 Thanks. Closed
