### ISSUE TITLE
provisioning smart_mgmt workshop fails

### ISSUE THREAD

**Issue by calvingsmith** [ansible/workshops#1244]
### Problem Summary

when attempting to provision the smart management workshop, I get the following error: 

```
TASK [redhat_cop.tower_configuration.projects : Add Projects] ********************************************************************************************************************************************************************************
failed: [SATTEST-student1-ansible-1] (item={'name': 'Automated Management', 'organization': 'Default', 'scm_update_on_launch': True, 'scm_update_cache_timeout': 3600, 'scm_type': 'git', 'scm_url': 'https://github.com/willtome/automated-smart-management.git', 'scm_branch': 'smart_mgmt'}) => changed=false 
  ansible_loop_var: tower_projects_item
  msg: Project update failed
  tower_projects_item:
    name: Automated Management
    organization: Default
    scm_branch: smart_mgmt
    scm_type: git
    scm_update_cache_timeout: 3600
    scm_update_on_launch: true
    scm_url: https://github.com/willtome/automated-smart-management.git
ok: [SATTEST-student1-ansible-1] => (item={'name': 'Fact Scan', 'organization': 'Default', 'scm_type': 'git', 'scm_url': 'https://github.com/ansible/awx-facts-playbooks.git'})


```

Investigating I found that removing the redhat.satellite requirement from http://github.com/willtome/automated-smart-management/collections/requirements.yml (after forking it, of course) got me past that step but then I get the following error: 

```
TASK [redhat_cop.tower_configuration.projects : Add Projects] ********************************************************************************************************************************************************************************
ok: [SATTEST-student1-ansible-1] => (item={'name': 'Automated Management', 'organization': 'Default', 'scm_update_on_launch': True, 'scm_update_cache_timeout': 3600, 'scm_type': 'git', 'scm_url': 'https://github.com/calvingsmith/automated-smart-management.git', 'scm_branch': 'smart_mgmt'})
ok: [SATTEST-student1-ansible-1] => (item={'name': 'Fact Scan', 'organization': 'Default', 'scm_type': 'git', 'scm_url': 'https://github.com/ansible/awx-facts-playbooks.git'})

TASK [redhat_cop.tower_configuration.job_templates : Add Tower Job Templates] ****************************************************************************************************************************************************************
failed: [SATTEST-student1-ansible-1] (item={'name': 'SETUP / Satellite', 'project': 'Automated Management', 'playbook': 'setup_satellite.yml', 'inventory': 'Workshop Inventory', 'credentials': ['Satellite Credential'], 'extra_vars': {'refresh_satellite_manifest': False}, 'ask_variables_on_launch': True}) => changed=false 
  ansible_loop_var: tower_templates_item
  msg: 'Unable to create job_template SETUP / Satellite: {''playbook'': [''Playbook not found for project.'']}'
  tower_templates_item:
    ask_variables_on_launch: true
    credentials:
    - Satellite Credential
    extra_vars:
      refresh_satellite_manifest: false
    inventory: Workshop Inventory
    name: SETUP / Satellite
    playbook: setup_satellite.yml
    project: Automated Management
failed: [SATTEST-student1-ansible-1] (item={'name': 'SETUP / Tower', 'project': 'Automated Management', 'playbook': 'setup_tower.yml', 'inventory': 'Workshop Inventory'}) => changed=false 
  ansible_loop_var: tower_templates_item
  msg: 'Unable to create job_template SETUP / Tower: {''playbook'': [''Playbook not found for project.'']}'
  tower_templates_item:
    inventory: Workshop Inventory
    name: SETUP / Tower
    playbook: setup_tower.yml
    project: Automated Management

```

### Issue Type

Bug

### Extra vars file

---
offline_token: REDACTED
tower_configuration_credentials_secure_logging: false
# region where the nodes will live
redhat_username: 'REDACTED'
redhat_password: 'REDACTED'
ec2_region: us-east-2
# name prefix for all the VMs
ec2_name_prefix: SATTEST
# amount of work benches to provision
student_total: 1
# workshop is put into rhel mode
workshop_type: smart_mgmt
# define DNS zone. AWS DNS required
dns_type: aws
workshop_dns_zone: redhatgov.io
# password used for student account on control node
admin_password: REDACTED
# disable ibm community grid
ibm_community_grid: false
## Optional Variables
# select rhel7 or rhel8 client nodes
rhel: rhel7
# this will install Ansible Tower on all control nodes
controllerinstall: true
# this will install VS Code web on all control nodes
code_server: true
# this will change the location of lab guide
# ansible_workshops_url: https://github.com/ansible/workshops
# ansible_workshops_version: smart_mgmt
ec2_info:
  satellite:
    owners: 605251984176
    filter: 'casmith-satellite*'
    username: ec2-user
    os_type: linux
    size: r5a.xlarge
  rhel7:
    owners: 309956199498
    size: t2.medium
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-7.9_HVM*'
    username: ec2-user
    python_interpreter: '/usr/bin/python'
  rhel8-tower:
    owners: 309956199498
    size: t2.medium
    os_type: linux
    disk_space: 20
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user
  attendance_host:
    owners: 309956199498
    size: t3.micro
    os_type: linux
    disk_space: 10
    architecture: x86_64
    filter: 'RHEL-8*HVM-*Hourly*'
    username: ec2-user

### Ansible Playbook Output

key data in notes, will upload full output if needed.

### Ansible Version

$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/cgs/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]

### Ansible Configuration

$ ansible-config dump --only-changed
$

(no output)

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 33

**Comment by IPvSean** [comment]
@heatmiser can you take a look?

**Comment by heatmiser** [comment]
@IPvSean @calvingsmith PR #1270 submitted
