### ISSUE TITLE
Arista EOS_banner module not accepting multi-line banners

### ISSUE THREAD

**Issue by benblasco** [ansible/workshops#1265]
### Problem Summary

Network workshop exercise 7 has users using a Tower Survey to create a banner

https://github.com/ansible/workshops/tree/devel/exercises/ansible_network/7-controller-survey

The job template fails on EOS devices when the user applies a multi line banner due to a known (and resolved issue) in the eos_banner module:

https://github.com/ansible-collections/arista.eos/issues/36
https://github.com/ansible-collections/arista.eos/pull/39

Can we update the lab environment to include a newer version of the Arista collection?  Will this resolve the issue?

### Issue Type

Bug

### Extra vars file

N/A.  Multi-vendor networking workshop provisioned using no special parameters

### Ansible Playbook Output

TASK [banner : ADD THE EOS BANNER] *********************************************
fatal: [rtr2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "data": "string index out of range", "msg": "string index out of range"}
fatal: [rtr4]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "data": "string index out of range", "msg": "string index out of range"}

### Ansible Version

Tower 3.7.3
Ansible 2.9.24 

[student13@ansible-1 ~]$ ansible --version
ansible 2.9.24
  config file = /home/student13/.ansible.cfg
  configured module search path = ['/home/student13/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

### Ansible Configuration

Not sure if the output below is relevant

```
[student13@ansible-1 ~]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student13/.ansible.cfg) = ['/home/student13/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student13/.ansible.cfg) = community.general.yaml
DEFAULT_TIMEOUT(/home/student13/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student13/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student13/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student13/.ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/home/student13/.ansible.cfg) = 200
RETRY_FILES_ENABLED(/home/student13/.ansible.cfg) = False
[student13@ansible-1 ~]$ 

[student13@ansible-1 ~]$ sudo su - awx
[awx@ansible-1 ~]$ 
[awx@ansible-1 ~]$ 
[awx@ansible-1 ~]$ ansible-config dump --only-changed
[awx@ansible-1 ~]$ 


```

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

Ansible Tower as provisioned in multi-vendor Networking workshop in RHPDS.

**Comment by IPvSean** [comment]
@benblasco will it be OK if you can wait one more week?  AAP 2 will use a newer collection on `devel` branch and should work fine

or do we need to also support workshop on AAP 1.2?  I would love to just start removing AAP 1.2 workshops ASAP

**Comment by benblasco** [comment]
No rush! My only comment is that AAP 1.2 workshops should stick around until people are comfortable with 2.0 workshops *and* bugs have been ironed out.

**Comment by benblasco** [comment]
Always happy to contribute etc.
