### ISSUE TITLE
Ansible Windows Automation Workshop: Wrong links in Exercise description

### ISSUE THREAD

**Issue by rhmk** [ansible/workshops#1271]
### Area
Ansible Windows Automation Workshop

### Proposed Changes
The exercise pages have implemented wrong links:
Page: https://ansible.github.io/workshops/exercises/ansible_windows/3-playbook/
the following links have to be replaced:

- https://docs.ansible.com/ansible/latest/win_feature_module.html with https://docs.ansible.com/ansible/latest/module/win_feature_module.html
- https://docs.ansible.com/ansible/latest/win_service_module.html with https://docs.ansible.com/ansible/latest/module/win_service_module.html
- http://docs.ansible.com/ansible/YAMLSyntax.html with https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

**Comment by IPvSean** [comment]
assigning to @cloin

**Comment by IPvSean** [comment]
any update @cloin ?

**Comment by cloin** [comment]
previously fixed.
