### ISSUE TITLE
Provisioner can't find roles from installed collection

### ISSUE THREAD

**Issue by nleiva** [ansible/workshops#1298]
### Problem Summary

Hi, for some reason ansible can't find the roles from the `ansible.workshops` collection we manually install.

The collection is installed successfully at `/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_collections/ansible_collections/ansible/workshops` in the example below.

```json
{   
    ... 
    "stdout_lines": [
        "\u001b[0;34mUsing /tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/ansible.cfg as config file\u001b[0m",
        "Starting galaxy collection install process",
        "Process install dependency map",
        "Starting collection install process",
        "Installing 'ansible.workshops:0.0.20' to '/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_collections/ansible_collections/ansible/workshops'",
        "ansible.workshops:0.0.20 was installed successfully",
        ...
        "Downloading https://galaxy.ansible.com/download/containers-podman-1.8.0.tar.gz to /var/lib/awx/.ansible/tmp/ansible-local-143b7w3pop2/tmpc98yta2k/containers-podman-1.8.0-sjsjqfg1",
        "Installing 'containers.podman:1.8.0' to '/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_collections/ansible_collections/containers/podman'",
        "containers.podman:1.8.0 was installed successfully"
    ],
    ...
}
```

However, this path is not in the search path for roles, from the error below.

```
TASK [Delete content & directory] **********************************************
changed: [localhost] => {"changed": true, "path": "build", "state": "absent"}

TASK [run pre-check role to make sure workshop will complete provisioning] *****
ERROR! the role 'ansible.workshops.workshop_check_setup' was not found in /tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/roles:/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner

The error appears to be in '/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/provision_lab.yml': line 21, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      include_role:
        name: ansible.workshops.workshop_check_setup
              ^ here
```

It looks for roles at:
- `/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/roles`
- `/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_roles` 
- `/var/lib/awx/.ansible/roles`
- `/usr/share/ansible/roles`
- `/etc/ansible/roles`
- `/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner`

No mention of `ansible_collections`. Should we modify `ansible.cfg`?

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

```
TASK [Delete content & directory] **********************************************
changed: [localhost] => {"changed": true, "path": "build", "state": "absent"}

TASK [run pre-check role to make sure workshop will complete provisioning] *****
ERROR! the role 'ansible.workshops.workshop_check_setup' was not found in /tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/roles:/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/requirements_roles:/var/lib/awx/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner

The error appears to be in '/tmp/bwrap_3588_ge1s3ud_/awx_3588_q8g33bz3/project/provisioner/provision_lab.yml': line 21, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      include_role:
        name: ansible.workshops.workshop_check_setup
              ^ here
```

### Ansible Version

```
⇨  ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 
(Red Hat 8.4.1-1)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.5] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/cloud211/lib64/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/my-envs/cloud211/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.1
  libyaml = True
```

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

Red Hat Enterprise Linux release 8.4 (Ootpa)

**Comment by IPvSean** [comment]
note from conversation with @nleiva this is Tower 3.8 which explains the bubblewrap....... I am not 100% sure what is going on.... but I am guessing that where Tower 3.8 "looks" for collections and where the `ansible-galaxy` command "puts" them don't match....

@nleiva if you can try this for me, it would be appreciated:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#collections-paths

we can do this->

in the ansible.cfg:
```
[default]
collections_paths=~/.ansible/collections:/usr/share/ansible/collections
```

so.... hard part is changing it.... 

on your control know sudo -i then su - awx and become the awx user and cd into the right project and try editing the ansible.cfg to see if it works... let me know if you get stuck

**Comment by nleiva** [comment]
I tried it without success (https://github.com/nleiva/workshops/blob/devel/provisioner/ansible.cfg#L20).

It's like ansible is unaware the it needs to look for roles in the collection folder. I'll try a couple of things to see if I can come with a workaround.

**Comment by IPvSean** [comment]
did you try @nleiva ?  I think as long as we have 2.11 and use requirements 

```
---
collections:
  - name: ansible.workshops
    version: 1.0.0
```

**Comment by IPvSean** [comment]
OK many people were struggling with the way I had the collection install itself (e.g. the workshop provisioner did a ansible-galaxy collection install ansible.workshops before executing the rest of the provision__lab.yml). I have moved back to relative path e.g. provisioner/provision_lab.yml  will do ../roles/control_node/

Try again and it "should" work
