### ISSUE TITLE
Multiple Ansible Demo & workshop failing on RHPDS.

### ISSUE THREAD

**Issue by Chetan-07** [ansible/workshops#1303]
### Problem Summary

We have multiple failures for Ansible Windows Workshop, Ansible Linux Automation Workshop (L, S, and T), and Ansible RHEL Demos on RHPDS.  Sharing below details for your reference.

Failed GUID's: b4d8, 21ab, 1333.

TASK [/tmp/ansible-workshops-b4d8/ansible_agnostic_deployer/ansible/workdir/ansible-workshops/provisioner/../roles/control_node : install ansible development branch to venv] ***
fatal: [b4d8-student1-ansible-1]: FAILED! => {"changed": false, "cmd": ["/opt/my-envs/ansible_dev/bin/pip3", "install", "git+https://github.com/ansible/ansible.git@devel", "psutil", "paramiko", "ncclient"], "msg": "stdout: created virtual environment CPython3.6.8.final.0-64 in 755ms\n  creator CPython3Posix(dest=/opt/my-envs/ansible_dev, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)\n    added seed packages: pip==21.2.4, setuptools==58.0.4, wheel==0.37.0\n  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\nCollecting git+https://github.com/ansible/ansible.git@devel\n  Cloning https://github.com/ansible/ansible.git (to revision devel) to ./pip-req-build-czf41f92\n  Resolved https://github.com/ansible/ansible.git to commit 57359d0174d471e92290e0d591978b9f1fbce7b7\nCollecting psutil\n  Downloading psutil-5.8.0-cp36-cp36m-manylinux2010_x86_64.whl (291 kB)\nCollecting paramiko\n  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)\nCollecting ncclient\n  Downloading ncclient-0.6.12.tar.gz (106 kB)\nCollecting jinja2\n  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)\nCollecting PyYAML\n  Using cached PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)\nCollecting cryptography\n  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl (3.0 MB)\nCollecting packaging\n  Downloading packaging-21.0-py3-none-any.whl (40 kB)\nCollecting resolvelib<0.6.0,>=0.5.3\n  Downloading resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)\n\n:stderr:   Running command git clone -q https://github.com/ansible/ansible.git /tmp/pip-req-build-czf41f92\nERROR: Package 'ansible-core' requires a different Python: 3.6.8 not in '>=3.8'\n"}

### Issue Type

Bug

### Extra vars file

TASK [/tmp/ansible-workshops-b4d8/ansible_agnostic_deployer/ansible/workdir/ansible-workshops/provisioner/../roles/control_node : install ansible development branch to venv] ***
fatal: [b4d8-student1-ansible-1]: FAILED! => {"changed": false, "cmd": ["/opt/my-envs/ansible_dev/bin/pip3", "install", "git+https://github.com/ansible/ansible.git@devel", "psutil", "paramiko", "ncclient"], "msg": "stdout: created virtual environment CPython3.6.8.final.0-64 in 755ms\n  creator CPython3Posix(dest=/opt/my-envs/ansible_dev, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)\n    added seed packages: pip==21.2.4, setuptools==58.0.4, wheel==0.37.0\n  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\nCollecting git+https://github.com/ansible/ansible.git@devel\n  Cloning https://github.com/ansible/ansible.git (to revision devel) to ./pip-req-build-czf41f92\n  Resolved https://github.com/ansible/ansible.git to commit 57359d0174d471e92290e0d591978b9f1fbce7b7\nCollecting psutil\n  Downloading psutil-5.8.0-cp36-cp36m-manylinux2010_x86_64.whl (291 kB)\nCollecting paramiko\n  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)\nCollecting ncclient\n  Downloading ncclient-0.6.12.tar.gz (106 kB)\nCollecting jinja2\n  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)\nCollecting PyYAML\n  Using cached PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)\nCollecting cryptography\n  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl (3.0 MB)\nCollecting packaging\n  Downloading packaging-21.0-py3-none-any.whl (40 kB)\nCollecting resolvelib<0.6.0,>=0.5.3\n  Downloading resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)\n\n:stderr:   Running command git clone -q https://github.com/ansible/ansible.git /tmp/pip-req-build-czf41f92\nERROR: Package 'ansible-core' requires a different Python: 3.6.8 not in '>=3.8'\n"}

### Ansible Playbook Output

TASK [/tmp/ansible-workshops-b4d8/ansible_agnostic_deployer/ansible/workdir/ansible-workshops/provisioner/../roles/control_node : install ansible development branch to venv] ***
fatal: [b4d8-student1-ansible-1]: FAILED! => {"changed": false, "cmd": ["/opt/my-envs/ansible_dev/bin/pip3", "install", "git+https://github.com/ansible/ansible.git@devel", "psutil", "paramiko", "ncclient"], "msg": "stdout: created virtual environment CPython3.6.8.final.0-64 in 755ms\n  creator CPython3Posix(dest=/opt/my-envs/ansible_dev, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)\n    added seed packages: pip==21.2.4, setuptools==58.0.4, wheel==0.37.0\n  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\nCollecting git+https://github.com/ansible/ansible.git@devel\n  Cloning https://github.com/ansible/ansible.git (to revision devel) to ./pip-req-build-czf41f92\n  Resolved https://github.com/ansible/ansible.git to commit 57359d0174d471e92290e0d591978b9f1fbce7b7\nCollecting psutil\n  Downloading psutil-5.8.0-cp36-cp36m-manylinux2010_x86_64.whl (291 kB)\nCollecting paramiko\n  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)\nCollecting ncclient\n  Downloading ncclient-0.6.12.tar.gz (106 kB)\nCollecting jinja2\n  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)\nCollecting PyYAML\n  Using cached PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)\nCollecting cryptography\n  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl (3.0 MB)\nCollecting packaging\n  Downloading packaging-21.0-py3-none-any.whl (40 kB)\nCollecting resolvelib<0.6.0,>=0.5.3\n  Downloading resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)\n\n:stderr:   Running command git clone -q https://github.com/ansible/ansible.git /tmp/pip-req-build-czf41f92\nERROR: Package 'ansible-core' requires a different Python: 3.6.8 not in '>=3.8'\n"}

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

NA

**Comment by IPvSean** [comment]
hey @Chetan-07 not filling out data like this-> 

```
Operating System
NA
```

does not help me fix the issue... please take the time to fully fill out the ticketing template next time

**Comment by Chetan-07** [comment]
> hey @Chetan-07 not filling out data like this->
> 
> ```
> Operating System
> NA
> ```
> 
> does not help me fix the issue... please take the time to fully fill out the ticketing template next time

@IPvSean I'm sorry! This was my first time creating issues on github. I'll take care from next time.

**Comment by IPvSean** [comment]
task identified here: https://github.com/ansible/workshops/blob/master/roles/control_node/tasks/venv.yml#L28

the way this works is there is a virtualenv created for demo purposes that is a rolling release on the ansible devel.  Now that ansible has split between ansible community distribution and ansible-core, and ansible-core has moved forward to python 3.8 this is causing an issue (upstream issue, not related to changed to workshops we did).

Since we don't have an actual exercise showcasing this... I am going to remove all venv stuff, since it will be deprecated for Execution Environments

**Comment by IPvSean** [comment]
@Chetan-07 I "think" I know how to fix this, but in the interest of time I already merged PR https://github.com/ansible/workshops/pull/1304

This will immediately be picked up by RHPDS.... (I usually do a lot more testing...) can you retry?

In parallel I am testing it out... but I don't want to have people wait another hour

**Comment by IPvSean** [comment]
I tested this from my control node, I am running 
```
➜  provisioner git:(master) ✗ ansible --version
ansible [core 2.11.2]
  config file = /Users/sean/Documents/GitHub/IPvSean/workshops/provisioner/ansible.cfg
  configured module search path = ['/Users/sean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sean/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

it worked first try with the fix I made... let me know if this works

**Comment by Chetan-07** [comment]
I'm ordering few demos to test.

**Comment by IPvSean** [comment]
![image (117)](https://user-images.githubusercontent.com/6537680/134358821-787c4595-5e0b-42d7-8501-15756016ef52.png)

awesome, closing issue 

![boom](https://media2.giphy.com/media/LrN9NbJNp9SWQ/giphy-downsized.gif?cid=6104955ea8e1a0e5b108b9d7d1c3151d14039e5787ee5352&rid=giphy-downsized.gif&ct=g)

**Comment by 9strands** [comment]
FYI, all Ansible labs are failing currently - seems to have occurred from Friday through to now.

**Comment by IPvSean** [comment]
@9strands different issue, next time open an issue and we can investigate
