### ISSUE TITLE
Security workshop - Section 2 Exercise 2.2 Snort logs to QRadar unknown source

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1334]
### Problem Summary

**Section 2 - Exercise 2.2 - Step 2.6** 
https://aap2.demoredhat.com/exercises/ansible_security/2.2-threat/
- Requires user to whitelist attacker IP  and add Snort log source to QRadar.
- QRadar changes were not deployed and the playbook creates an incorrect log source identifier

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

NA

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL 8

**Comment by IPvSean** [comment]
did you get this fixed with your PR @craig-br ?  close?
