### ISSUE TITLE
Use Spanish flag for Spanish language

### ISSUE THREAD

**Issue by amayagil** [ansible/workshops#1343]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

In the body of the exercises page, you are presented with a different set of languages options, while Portuguese states clearly that it is the brazilian variant (hence using its flag) in the case of Spanish, it is not stating that the variant being used is the one in Colombia, but it is using its flag. I strongly recommend using the Spanish flag instead, as it’s the one most people identify with the Spanish language, as it's done for the English and French languages in this same page.

**Comment by IPvSean** [comment]
@amayagil originally it was just a homage for the contributor.  The person that translated the Spanish was from Colombia so I just reflected the flag... /shrug 

I can change it... but I think all the translations are out of date so I might wait until someone takes a look.  My understanding is that you speak Spanish fluently?  Can you help us out 🙏

**Comment by IPvSean** [comment]
closing issue until someone has time to work on this
