### ISSUE TITLE
Step 5: after running the “check_httpd.yml” playbook you are told to expect a 403 error

### ISSUE THREAD

**Issue by amayagil** [ansible/workshops#1347]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

after running the “check_httpd.yml” playbook you are told to expect a 403 error, but instead, a 200 is shown, which is due to different causes than the ones explained in the guide.

No variable is being referenced.

**Comment by amayagil** [comment]
https://aap2.demoredhat.com/exercises/ansible_rhel/1.3-playbook/#step-4---extend-your-playbook-start--enable-apache
you should get a 403 but you get this
TASK [Check that you can connect (GET) to a page and it returns a status 200] ***
fatal: [ansible-1]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error no host given>", "redirected": false, "status": -1, "url": "http://"}
IP var is not referenced, should be:
  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: "http://{{ IP }}"

**Comment by amayagil** [comment]
same as https://github.com/ansible/workshops/issues/1396

**Comment by IPvSean** [comment]
@rlopez133 did you close this out?

**Comment by rlopez133** [comment]
I thought this was fixed by #1399 is it not?

**Comment by IPvSean** [comment]
closing this out since lack of answer to @rlopez133
