### ISSUE TITLE
Next Exercise and Previous Exercise links broken in Exercise 3

### ISSUE THREAD

**Issue by amayagil** [ansible/workshops#1348]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

link https://aap2.demoredhat.com/exercises/ansible_rhel_90/1.2-thebasics is broken
link https://aap2.demoredhat.com/exercises/ansible_rhel_90/1.4-variables is broken

**Comment by IPvSean** [comment]
fixed and updated documentation
