### ISSUE TITLE
AAP2 Security Workshop windows instance creation times out

### ISSUE THREAD

**Issue by tonykay** [ansible/workshops#1369]
### Problem Summary

RHPDS based deployments have seen a number of failures of the AAP2 Security Workshop.

It looks like a timeout on the 

### Issue Type

Bug

### Extra vars file

workshop_type: security
security_console: 'qradar'

## Optional Variables
create_login_page: true
autolicense: true
towerinstall: true
dns_type: aws

### Ansible Playbook Output

TASK [manage_ec2_instances : Wait for async instance creation to complete] *****
FAILED - RETRYING: Wait for async instance creation to complete (60 retries left).
FAILED - RETRYING: Wait for async instance creation to complete (59 retries left).
.
.
FAILED - RETRYING: Wait for async instance creation to complete (4 retries left).
FAILED - RETRYING: Wait for async instance creation to complete (3 retries left).
FAILED - RETRYING: Wait for async instance creation to complete (2 retries left).
FAILED - RETRYING: Wait for async instance creation to complete (1 retries left).
failed: [localhost] (item={'started': 1, 'finished': 0, 'ansible_job_id': '219228715480.19801', 'results_file': '/home/opentlc-mgr/.ansible_async/219228715480.19801', 'changed': True, 'failed': False}) => {"ansible_job_id": "219228715480.19801", "ansible_loop_var": "item", "attempts": 60, "changed": false, "finished": 0, "item": {"ansible_job_id": "219228715480.19801", "changed": true, "failed": false, "finished": 0, "results_file": "/home/opentlc-mgr/.ansible_async/219228715480.19801", "started": 1}, "started": 1}
ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '380151732358.19894', 'results_file': '/home/opentlc-mgr/.ansible_async/380151732358.19894', 'changed': True, 'failed': False}) => {"ansible_job_id": "380151732358.19894", "ansible_loop_var": "item", "attempts": 1, "changed": false, "finished": 1, "instance_ids": null, "instances": [], "item": {"ansible_job_id": "380151732358.19894", "changed": true, "failed": false, "finished": 0, "results_file": "/home/opentlc-mgr/.ansible_async/380151732358.19894", "started": 1}, "tagged_instances": [{"ami_launch_index": "0", "architecture": "x86_64", "block_device_mapping": {"/dev/sda1": {"delete_on_termination": true, "status": "attached", "volume_id": "vol-07b301beac2753fd9"}}, "dns_name": "ec2-3-70-132-229.eu-central-1.compute.amazonaws.com", "ebs_optimized": false, "groups": {"sg-017493712a9028fcd": "da92-insecure_all"}, "hypervisor": "xen", "id": "i-0050fca273f5f37b1", "image_id": "ami-05b046f9e8002b63e", "instance_type": "t3.micro", "kernel": null, "key_name": "da92-key", "launch_time": "2021-10-13T11:18:34.000Z", "placement": "eu-central-1a", "private_dns_name": "ip-172-16-254-179.eu-central-1.compute.internal", "private_ip": "172.16.254.179", "public_dns_name": "ec2-3-70-132-229.eu-central-1.compute.amazonaws.com", "public_ip": "3.70.132.229", "ramdisk": null, "region": "eu-central-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "tags": {"AWS_USERNAME": "opentlc-mgr", "Info": "AWS_USERNAME that provisioned this-> opentlc-mgr", "Linklight": "This was provisioned through the linklight provisioner", "Students": "1", "Workshop": "da92", "Workshop_snort": "da92-snort", "Workshop_type": "security", "ansible-workshops": "true", "owner": "opentlc-mgr", "short_name": "snort", "username": "ec2-user"}, "tenancy": "default", "virtualization_type": "hvm"}]}

### Ansible Version

ansible [core 2.11.5]
  config file = /home/opentlc-mgr/.ansible.cfg
  configured module search path = ['/home/opentlc-mgr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/opentlc-mgr/virtualenvs/ansible2.11-python3.8-2021-09-27/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/opentlc-mgr/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/opentlc-mgr/virtualenvs/ansible2.11-python3.8-2021-09-27/bin/ansible
  python version = 3.8.11 (default, Jul 23 2021, 14:55:16) [GCC 9.1.1 20190605 (Red Hat 9.1.1-2)]
  jinja version = 3.0.1
  libyaml = True

### Ansible Configuration

[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callback_enabled instead. This feature will be removed from ansible-core in
version 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/home/opentlc-mgr/.ansible.cfg) = ['profile_tasks']

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Employee SKU"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

**Comment by craig-br** [comment]
This issue will be resolved with planned migration to T3 AWS instances.
