### ISSUE TITLE
"Previous Exercise" broken link

### ISSUE THREAD

**Issue by amayagil** [ansible/workshops#1372]
### Area

Ansible Network Automation Workshop

### Proposed Changes

At the end of "Exercise 8: Understanding RBAC in Automation controller
" (https://aap2.demoredhat.com/exercises/ansible_network/8--controller-rbac/README.md) "Previous Exercise" link (https://aap2.demoredhat.com/exercises/ansible_network/7--controller-survey/README.md) is broken

**Comment by IPvSean** [comment]
fixed and live on https://aap2.demoredhat.com/exercises/ansible_network/8-controller-rbac/
