### ISSUE TITLE
"Previous exercise" link broken

### ISSUE THREAD

**Issue by amayagil** [ansible/workshops#1382]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

on AAP 2 - Linux Automation Workshop, exercise https://aap2.demoredhat.com/exercises/ansible_rhel/1.3-playbook/ at the bottom, "Previous exercise" (https://aap2.demoredhat.com/exercises/ansible_rhel/2-thebasics) link is broken

**Comment by IPvSean** [comment]
fixed and live in https://aap2.demoredhat.com/exercises/ansible_rhel/1.3-playbook/
