### ISSUE TITLE
Security workshop Workshop access link needs more visibility

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1400]
### Area

Ansible Security Automation

#### Summary

![image](https://user-images.githubusercontent.com/42829306/138123484-8f7ae1c6-9da4-47f7-a5f6-cc534279445b.png)

- The `Workshop access` link in the security exercises should be larger and the link text needs to be updated to indicate it's clickable

#### Recommendation
-  Currently, the `workshop access` section is duplicated in each .md file. This should be updated to be a Jekyll `include` to keep the code DRY.
-This issue is also an opportunity to explore using side navigation

**Comment by IPvSean** [comment]
@craig-br 

what about something like this->
![image](https://user-images.githubusercontent.com/6537680/156599243-958d1772-4c32-4c8f-a160-84b55f053a2f.png)

and hover does 
![image](https://user-images.githubusercontent.com/6537680/156599278-7c877d16-3501-455d-bd38-1f596f2ae4ea.png)

The CSS is->
```
a h3 {
    color: #EE0000;
    text-decoration: underline;
    font-weight: bold;
}
a h3:hover {
    color: #5F0000;
}
```

**Comment by IPvSean** [comment]
fixed 👊
