### ISSUE TITLE
Cisco flavor of the workshop referencing Arista.eos modules

### ISSUE THREAD

**Issue by makebeer-war** [ansible/workshops#1411]
### Area

Ansible Network Automation Workshop

### Proposed Changes

Need to change Exercise 4 to be more cisco centric for the cisco flavor. I tried converting the commands myself but got an error. I'll be opening a bug as well for the particular issue I'm running into.

`fatal: [rtr3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr3#. Please make sure it's an L2 switch"}`

**Comment by IPvSean** [comment]
OK finished a cisco example: https://ipvsean.github.io/workshops/exercises/ansible_network/supplemental/4-resource-module-cisco/

This will go into the next release.... reopen or create a new issue if this exercise does not work
