### ISSUE TITLE
Exercise4 AAP Network Automation Cisco flavor

### ISSUE THREAD

**Issue by makebeer-war** [ansible/workshops#1412]
### Problem Summary

In exercise 4, it instructs you to use the arista.eos.vlans module to merge config changes and define some vlans. Since I was using the cisco flavour, I don't have any arista routers. I switched to cisco.ios.vlans (and cisco.ios.ios_vlans) and am getting the following error:

`fatal: [rtr3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr3#. Please make sure it's an L2 switch"}`

Here is a copy of my playbook

`---
- name: configure VLANs
  hosts: cisco
  gather_facts: no

  tasks: 
    - name: use vlans resouce module
      cisco.ios.ios_vlans:
        state: merged
        config:
          - name: desktops
            vlan_id: 20
          - name: servers
            vlan_id: 30
          - name: printers
            vlan_id: 40
          - name: DMZ
            vlan_id: 50`

I'm running it using 

`ansible-navigator run  resource.yaml --mode stdout`

### Issue Type

Bug

### Extra vars file

There's no extra vars file. 

cat of inventory file

`[routers:vars]
ansible_user=ec2-user

[routers:children]
cisco

[cisco]
rtr1 ansible_host=3.238.79.27 private_ip=172.16.47.160
rtr2 ansible_host=3.232.132.226 private_ip=172.18.84.153
rtr4 ansible_host=3.215.184.75 private_ip=172.18.197.7
rtr3 ansible_host=3.239.197.92 private_ip=172.16.118.227

[cisco:vars]
ansible_network_os=ios
ansible_connection=network_cli

[dc1]
rtr1
rtr3

[dc2]
rtr2
rtr4

[control]
ansible-1 ansible_host=3.238.156.198 ansible_user=student1 private_ip=172.16.147.226 ansible_password=WmYOnLRSTt8b51

[network:children]
routers
[network:vars]
restore_inventory="Workshop Inventory"
restore_credential="Workshop Credential"
restore_project="Workshop Project"`

### Ansible Playbook Output

`TASK [use vlans resouce module] ************************************************
fatal: [rtr3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr3#. Please make sure it's an L2 switch"}
fatal: [rtr4]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr4#. Please make sure it's an L2 switch"}
fatal: [rtr1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr1#. Please make sure it's an L2 switch"}
fatal: [rtr2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "'show vlan' doesn't seems to be supported on the IOS box and failed with error: show vlan\r\nshow vlan\r\n% Incomplete command.\r\n\r\nrtr2#. Please make sure it's an L2 switch"}`

### Ansible Version

` 0│---
 1│ansible:
 2│  collections:
 3│    details:
 4│      amazon.aws: 1.5.0
 5│      ansible.controller: 4.0.0
 6│      ansible.netcommon: 2.2.0
 7│      ansible.network: 1.0.1
 8│      ansible.posix: 1.2.0
 9│      ansible.security: 1.0.0
10│      ansible.utils: 2.3.0
11│      ansible.windows: 1.5.0
12│      arista.eos: 2.2.0
13│      cisco.asa: 2.0.2
14│      cisco.ios: 2.3.0
15│      cisco.iosxr: 2.3.0
16│      cisco.nxos: 2.4.0
17│      cloud.common: 2.0.3
18│      frr.frr: 1.0.3
19│      ibm.qradar: 1.0.3
20│      junipernetworks.junos: 2.2.0
21│      kubernetes.core: 2.1.1
22│      openvswitch.openvswitch: 2.0.0
23│      redhat.insights: 1.0.5
24│      redhat.openshift: 2.0.1
25│      redhat.rhel_system_roles: 1.0.1
26│      redhat.rhv: 1.4.4
27│      redhat.satellite: 2.0.1
28│      servicenow.itsm: 1.1.0
29│      splunk.es: 1.0.2
30│      trendmicro.deepsec: 1.1.0
31│      vmware.vmware_rest: 2.0.0
32│      vyos.vyos: 2.3.1
33│  version:
34│    details: core 2.11.2`

### Ansible Configuration

`ACTION_WARNINGS(/etc/ansible/ansible.cfg) = False
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/etc/ansible/ansible.cfg) = ignore
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 200
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False`

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL 

NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

EE
ee-supported-rhel8

**Comment by IPvSean** [comment]
there is now a cisco flavor https://ipvsean.github.io/workshops/exercises/ansible_network/supplemental/4-resource-module-cisco/
