### ISSUE TITLE
ansible-navigator intermittent error - lsetxattr /etc/ansible: operation not permitted

### ISSUE THREAD

**Issue by pharriso** [ansible/workshops#1417]
### Problem Summary

While running through the AAP 2.0 labs you will intermittently hit an error when running ansible-navigator inventory & run commands - "Error: lsetxattr /etc/ansible: operation not permitted". As I say, this is intermittent so some executions will work OK, but eventually you will hit the error.

Removing the label from the volume-mounts in .ansible-navigator.yml seems to resolve the issue. So changing this:

```volume-mounts:
    - src: "/etc/ansible/"
      dest: "/etc/ansible/"
      label: "Z"```

To 

```volume-mounts:
    - src: "/etc/ansible/"
      dest: "/etc/ansible/"
```

### Issue Type

Bug

### Extra vars file

Provisioned through RHPDS

### Ansible Playbook Output

ansible-navigator inventory --graph web -m stdout
Error: lsetxattr /etc/ansible: operation not permitted

### Ansible Version

ansible-navigator 1.0.0

ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/student1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

### Ansible Configuration

ACTION_WARNINGS(/etc/ansible/ansible.cfg) = False
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/etc/ansible/ansible.cfg) = ignore
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 200
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL8.5

**Comment by anshulbehl** [comment]
Removing the label from the navigator volume mount setting fixes this in my testing, if the issue still persists please let us know

**Comment by benblasco** [comment]
I still have this issue when deploying from RHPDS:

[student1@ansible-1 ~]$ ansible-navigator inventory --host node1 -m stdout 
Error: lsetxattr /etc/ansible: operation not permitted
[student1@ansible-1 ~]$ ansible-navigator inventory --host control -m stdout 
{
    "ansible_host": "18.140.70.46",
    "ansible_port": 22,
    "ansible_ssh_pass": "q3NSd8sB9e6woN",
    "ansible_user": "student1"
}

@anshulbehl Please see output from the above.  This is using the RHPDS "AAP2 Linux Automation Workshop (T)" deployed today.  Please feel free to message me via RH channels for environment access if needed.

**Comment by benblasco** [comment]
This problem is also affecting the execution of playbooks in the student environment.  I had to re-run the same commant 4 times to get it to work.  Do you think this could/should be handled as a high severity issue?  I have a customer workshop this Friday!

```
[student1@ansible-1 ansible-files]$ 
[student1@ansible-1 ansible-files]$ ansible-navigator run apache.yml -m stdout
Error: lsetxattr /etc/ansible: operation not permitted
[student1@ansible-1 ansible-files]$ ansible-navigator run apache.yml -m stdout
Error: lsetxattr /etc/ansible: operation not permitted
[student1@ansible-1 ansible-files]$ ansible-navigator run apache.yml -m stdout
Error: lsetxattr /etc/ansible: operation not permitted
[student1@ansible-1 ansible-files]$ ansible-navigator run apache.yml -m stdout

PLAY [Apache server installed] *************************************************

TASK [Gathering Facts] *********************************************************
ok: [node1]

TASK [latest Apache version installed] *****************************************
ok: [node1]

TASK [Apache enabled and running] **********************************************
changed: [node1]

PLAY RECAP *********************************************************************
node1                      : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by anshulbehl** [comment]
The PR is not merged yet, I will reply here once the PR is merged and then you can give it a try again.
