### ISSUE TITLE
AAP 2.0 workshops Linux Google Slides deck link out of date

### ISSUE THREAD

**Issue by benblasco** [ansible/workshops#1420]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

README.md in devel branch of https://github.com/ansible/workshops points to the old version of the slide deck, even though the workshop is deployed with a link to the new version of the slide deck.  Where does the new deck live?  We need to be able to copy it for our own customer presentations, and be able to read notes, comment, edit etc.  

Can you please provide a link to the correct deck and also check if the links to the other workshop decks are current?

Note: I am a RH employee and regularly deliver Ansible workshops to customers.

**Comment by benblasco** [comment]
Correction, I must have accidentally switched back to the master branch.  The devel branch is pointing to the correct deck at:

https://docs.google.com/presentation/d/1O2Gj5r_fhjM5Pi5FizrZRInmZ37IlpeKPTP6jSZxEKs/edit?usp=sharing

Thanks.

**Comment by benblasco** [comment]
I am still having trouble linking to the correct deck from Github.  Could somebody please check the page at the links above and ensure we are being pointed to the Google Slides for the right version of the deck?  Thanks @anshulbehl @IPvSean

**Comment by anshulbehl** [comment]
I think I see the problem now, looks like Readme inside  the location below
https://github.com/ansible/workshops/tree/devel/decks

is pointing to the old deck and probably that is causing some confusion, the Readme in the home location https://github.com/ansible/workshops/tree/devel points to the right google source, please use that in the meantine.

I will fix the link in the 1st Readme.

**Comment by benblasco** [comment]
Thanks!

**Comment by anshulbehl** [comment]
@benblasco PR sent, I will wait for @IPvSean to confirm this
