### ISSUE TITLE
Codebase uses itself to host artifacts (rpms, VSC plugins etc) that can timeout at deploy time

### ISSUE THREAD

**Issue by tonykay** [ansible/workshops#1427]
### Problem Summary

Placing artifacts needed at deploy time on GitHub in the repo itself makes deploys vulnerable to GitHub timeouts. Large deploys may see 50+ parallel downloads of for example the VSC rpm and a single failure breaks the workshop deploy.

Suggest a simpler, and arguably more robust, home for artifacts is found - for example an AWS S3 bucket

A secondary benefit would be that older artifacts can also be left at the location so a developer or deployer using an older commit will find the older artifact

### Issue Type

Feature Request

### Extra vars file

NA

### Ansible Playbook Output

NA

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL but NA

**Comment by IPvSean** [comment]
closing this ticket since the `windows` and `rhel` workshop have been converted to run natively on agnosticd, which is using S3 buckets for host artifacts, thanks @tonykay
