### ISSUE TITLE
Ansible Security Automation slides

### ISSUE THREAD

**Issue by AQuack** [ansible/workshops#1432]
### Area

Ansible Security Automation

### Proposed Changes

The slides for "Ansible Security Automation" slide 59 and 66 are identical, except one says "Ansible Security Automation Roles" (59) and the other says "Ansible Security Automation Content Collections" (66) but the information on the slide and the notes is all referencing roles.

[Link to google source](https://docs.google.com/presentation/d/19gVCBz1BmxC15tDDj-FUlUd_jUUUKay81E8F24cyUjk/edit#slide=id.gf28137afda_0_95)

**Comment by AQuack** [comment]
updated the link to point to the correct google slides, the first one was a copy I made

**Comment by craig-br** [comment]
Duplicate slide removed, Thank you. I'll create a PR to update the PDF
