### ISSUE TITLE
Error when editing Network Command Survey (Ansible Automation Platform Network workshop/demo)

### ISSUE THREAD

**Issue by rnunezrgn** [ansible/workshops#1434]
### Problem Summary

Hi All,
I'm getting the following error when trying editing the "Network Command" template survey:

_**Something went wrong...
There was an error loading this content. Please reload the page. Back to Dashboard.

Details
TypeError: t.choices.split is not a function at nC (https://student1.2f0d.example.opentlc.com/static/js/main.9eb9518d.chunk.js:1:1074036) at Zo (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1413653) at Cs (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1459883) at vl (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1452610) at ml (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1452535) at sl (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1449544) at https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400915 at t.unstable_runWithPriority (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1476316) at Vi (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400624) at Yi (https://student1.2f0d.example.opentlc.com/static/js/2.97c02134.chunk.js:2:1400860)**_

The error persists regardless of the browser flavor or version, and users cannot open this Survey to add or remove commands. 
Any idea about how to solve the issue?

### Issue Type

Bug

### Extra vars file

N/A for this issue

### Ansible Playbook Output

Unable to run or get output. The error is triggered when "viewing" existing survey options

### Ansible Version

$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/student1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL

**Comment by IPvSean** [comment]
will investigate

**Comment by IPvSean** [comment]
this is fixed in latest release of 2.1.1.  Please reopen if this happens again.
