### ISSUE TITLE
Provisioning rhel workshop fails to controller job templates

### ISSUE THREAD

**Issue by imak** [ansible/workshops#1443]
### Problem Summary

Standing up a 'rhel' workshop is failing during provisioning at the "install projects" task.  It appears to be looking for a response to the API call for the official Ansible demo project that was deleted in the previous task.

"msg: Request to /api/v2/projects/?name=Ansible+official+demo+project returned 0 items, expected 1"

### Issue Type

Bug

### Extra vars file

---
# region where the nodes will live
ec2_region: us-east-2

# name prefix for all the VMs
ec2_name_prefix: fiercesw-aap2

# creates student_total of workbenches for the workshop
student_total: 3

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: rhel

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "eyJhbGciOiJIUzI1NiI...."

# Required for podman authentication to registry.redhat.io
redhat_username: joe
redhat_password: password

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: p@ssw0rd123!

# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: redhat-fierce.io

# automatically installs Tower to control node
controllerinstall: true

# forces ansible.workshops collection to install latest edits every time
developer_mode: true

## select ec2_info AMI vars can be overwritten via ec2_xtra vars, e.g.:
#ec2_xtra:
#  satellite:
#    owners: 012345678910
#    filter: Satellite*
#    username: ec2-user
#    os_type: linux
#    size: r5b.2xlarge

### Ansible Playbook Output

...
TASK [ansible.workshops.populate_controller : add student user] ***************************************************************************************************************************************************
[WARNING]: The field password of user 2 has encrypted data and may inaccurately report task is changed.
changed: [fiercesw-aap2-student2-ansible-1]
changed: [fiercesw-aap2-student1-ansible-1]
changed: [fiercesw-aap2-student3-ansible-1]

TASK [ansible.workshops.populate_controller : delete demo job template] *******************************************************************************************************************************************
ok: [fiercesw-aap2-student3-ansible-1]
ok: [fiercesw-aap2-student2-ansible-1]
ok: [fiercesw-aap2-student1-ansible-1]

TASK [ansible.workshops.populate_controller : remove demo credential] *********************************************************************************************************************************************
ok: [fiercesw-aap2-student3-ansible-1]
ok: [fiercesw-aap2-student2-ansible-1]
ok: [fiercesw-aap2-student1-ansible-1]

TASK [ansible.workshops.populate_controller : remove demo inventory] **********************************************************************************************************************************************
ok: [fiercesw-aap2-student3-ansible-1]
ok: [fiercesw-aap2-student2-ansible-1]
ok: [fiercesw-aap2-student1-ansible-1]

TASK [ansible.workshops.populate_controller : remove built-in demo project] ***************************************************************************************************************************************
ok: [fiercesw-aap2-student3-ansible-1]
ok: [fiercesw-aap2-student1-ansible-1]
ok: [fiercesw-aap2-student2-ansible-1]

TASK [ansible.workshops.populate_controller : Add security workshop execution environment] ************************************************************************************************************************
ok: [fiercesw-aap2-student3-ansible-1]
ok: [fiercesw-aap2-student1-ansible-1]
ok: [fiercesw-aap2-student2-ansible-1]

TASK [ansible.workshops.populate_controller : setup workshop specific controller information] *********************************************************************************************************************
[WARNING]: While constructing a mapping from
/RH_Workshops/workshops/provisioner/workshop_collections/ansible_collections/ansible/workshops/roles/populate_controller/tasks/rhel.yml, line 10, column 5, found a
duplicate dict key (name). Using last defined value only.
included: /RH_Workshops/workshops/provisioner/workshop_collections/ansible_collections/ansible/workshops/roles/populate_controller/tasks/rhel.yml for fiercesw-aap2-student1-ansible-1, fiercesw-aap2-student3-ansible-1, fiercesw-aap2-student2-ansible-1 => (item=/Fierce/RH_Workshops/workshops/provisioner/workshop_collections/ansible_collections/ansible/workshops/roles/populate_controller/tasks/rhel.yml)

TASK [install projects] *******************************************************************************************************************************************************************************************

TASK [redhat_cop.controller_configuration.job_templates : Add Controller Job Templates] ***************************************************************************************************************************
failed: [fiercesw-aap2-student3-ansible-1] (item={'name': 'INFRASTRUCTURE / Deploy Application', 'description': 'install yum applications on Linux with a survey', 'project': 'Ansible official demo project', 'job_type': 'run', 'playbook': 'playbooks/infrastructure/deploy_application.yml', 'credentials': 'Workshop Credential', 'inventory': 'Workshop Inventory', 'survey_enabled': True, 'survey': {'name': 'Deploy application survey', 'description': 'Which application do you want to install?', 'spec': [{'question_name': 'select application to be installed', 'question_description': 'select from drop down menu', 'required': True, 'type': 'multiplechoice', 'variable': 'application', 'min': 0, 'max': 1024, 'formattedChoices': [{'choice': 'httpd', 'isDefault': True, 'id': 0}, {'choice': 'nginx', 'isDefault': False, 'id': 1}, {'choice': 'htop', 'isDefault': False, 'id': 2}, {'choice': 'gdb', 'isDefault': False, 'id': 3}], 'new_question': False, 'default': 'httpd', 'choices': 'httpd\nnginx\nhtop\ngdb'}]}}) => changed=false 
  __controller_template_item:
    credentials: Workshop Credential
    description: install yum applications on Linux with a survey
    inventory: Workshop Inventory
    job_type: run
    name: INFRASTRUCTURE / Deploy Application
    playbook: playbooks/infrastructure/deploy_application.yml
    project: Ansible official demo project
    survey:
      description: Which application do you want to install?
      name: Deploy application survey
      spec:
      - choices: |-
          httpd
          nginx
          htop
          gdb
        default: httpd
        formattedChoices:
        - choice: httpd
          id: 0
          isDefault: true
        - choice: nginx
          id: 1
          isDefault: false
        - choice: htop
          id: 2
          isDefault: false
        - choice: gdb
          id: 3
          isDefault: false
        max: 1024
        min: 0
        new_question: false
        question_description: select from drop down menu
        question_name: select application to be installed
        required: true
        type: multiplechoice
        variable: application
    survey_enabled: true
  ansible_loop_var: __controller_template_item
  msg: Request to /api/v2/projects/?name=Ansible+official+demo+project returned 0 items, expected 1
  query:
    name: Ansible official demo project
  response:
    json:
      count: 0
      next: null
      previous: null
      results: []
    status_code: 200
  total_results: 0
failed: [fiercesw-aap2-student2-ansible-1] (item={'name': 'INFRASTRUCTURE / Deploy Application', 'description': 'install yum applications on Linux with a survey', 'project': 'Ansible official demo project', 'job_type': 'run', 'playbook': 'playbooks/infrastructure/deploy_application.yml', 'credentials': 'Workshop Credential', 'inventory': 'Workshop Inventory', 'survey_enabled': True, 'survey': {'name': 'Deploy application survey', 'description': 'Which application do you want to install?', 'spec': [{'question_name': 'select application to be installed', 'question_description': 'select from drop down menu', 'required': True, 'type': 'multiplechoice', 'variable': 'application', 'min': 0, 'max': 1024, 'formattedChoices': [{'choice': 'httpd', 'isDefault': True, 'id': 0}, {'choice': 'nginx', 'isDefault': False, 'id': 1}, {'choice': 'htop', 'isDefault': False, 'id': 2}, {'choice': 'gdb', 'isDefault': False, 'id': 3}], 'new_question': False, 'default': 'httpd', 'choices': 'httpd\nnginx\nhtop\ngdb'}]}}) => changed=false 
  __controller_template_item:
    credentials: Workshop Credential
    description: install yum applications on Linux with a survey
    inventory: Workshop Inventory
    job_type: run
    name: INFRASTRUCTURE / Deploy Application
    playbook: playbooks/infrastructure/deploy_application.yml
    project: Ansible official demo project
    survey:
      description: Which application do you want to install?
      name: Deploy application survey
      spec:
      - choices: |-
          httpd
          nginx
          htop
          gdb
        default: httpd
        formattedChoices:
        - choice: httpd
          id: 0
          isDefault: true
        - choice: nginx
          id: 1
          isDefault: false
        - choice: htop
          id: 2
          isDefault: false
        - choice: gdb
          id: 3
          isDefault: false
        max: 1024
        min: 0
        new_question: false
        question_description: select from drop down menu
        question_name: select application to be installed
        required: true
        type: multiplechoice
        variable: application
    survey_enabled: true
  ansible_loop_var: __controller_template_item
  msg: Request to /api/v2/projects/?name=Ansible+official+demo+project returned 0 items, expected 1
  query:
    name: Ansible official demo project
  response:
    json:
      count: 0
      next: null
      previous: null
      results: []
    status_code: 200
  total_results: 0
failed: [fiercesw-aap2-student1-ansible-1] (item={'name': 'INFRASTRUCTURE / Deploy Application', 'description': 'install yum applications on Linux with a survey', 'project': 'Ansible official demo project', 'job_type': 'run', 'playbook': 'playbooks/infrastructure/deploy_application.yml', 'credentials': 'Workshop Credential', 'inventory': 'Workshop Inventory', 'survey_enabled': True, 'survey': {'name': 'Deploy application survey', 'description': 'Which application do you want to install?', 'spec': [{'question_name': 'select application to be installed', 'question_description': 'select from drop down menu', 'required': True, 'type': 'multiplechoice', 'variable': 'application', 'min': 0, 'max': 1024, 'formattedChoices': [{'choice': 'httpd', 'isDefault': True, 'id': 0}, {'choice': 'nginx', 'isDefault': False, 'id': 1}, {'choice': 'htop', 'isDefault': False, 'id': 2}, {'choice': 'gdb', 'isDefault': False, 'id': 3}], 'new_question': False, 'default': 'httpd', 'choices': 'httpd\nnginx\nhtop\ngdb'}]}}) => changed=false 
  __controller_template_item:
    credentials: Workshop Credential
    description: install yum applications on Linux with a survey
    inventory: Workshop Inventory
    job_type: run
    name: INFRASTRUCTURE / Deploy Application
    playbook: playbooks/infrastructure/deploy_application.yml
    project: Ansible official demo project
    survey:
      description: Which application do you want to install?
      name: Deploy application survey
      spec:
      - choices: |-
          httpd
          nginx
          htop
          gdb
        default: httpd
        formattedChoices:
        - choice: httpd
          id: 0
          isDefault: true
        - choice: nginx
          id: 1
          isDefault: false
        - choice: htop
          id: 2
          isDefault: false
        - choice: gdb
          id: 3
          isDefault: false
        max: 1024
        min: 0
        new_question: false
        question_description: select from drop down menu
        question_name: select application to be installed
        required: true
        type: multiplechoice
        variable: application
    survey_enabled: true
  ansible_loop_var: __controller_template_item
  msg: Request to /api/v2/projects/?name=Ansible+official+demo+project returned 0 items, expected 1
  query:
    name: Ansible official demo project
  response:
    json:
      count: 0
      next: null
      previous: null
      results: []
    status_code: 200
  total_results: 0

PLAY RECAP ********************************************************************************************************************************************************************************************************
attendance-host            : ok=26   changed=3    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
fiercesw-aap2-student1-ansible-1 : ok=56   changed=10   unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
fiercesw-aap2-student1-node1 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student1-node2 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student1-node3 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student2-ansible-1 : ok=54   changed=10   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
fiercesw-aap2-student2-node1 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student2-node2 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student2-node3 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student3-ansible-1 : ok=54   changed=10   unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
fiercesw-aap2-student3-node1 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student3-node2 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
fiercesw-aap2-student3-node3 : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
localhost                  : ok=83   changed=8    unreachable=0    failed=0    skipped=32   rescued=0    ignored=0   

### Ansible Version

[user@computer provisioner]$ ansible --version
ansible [core 2.11.6] 
  config file = /home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/Fierce/RH_Workshops/workshops/provisioner/workshop_collections
  executable location = /usr/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.1
  libyaml = True
[user@computer provisioner]$ 

### Ansible Configuration

COLLECTIONS_PATHS(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = ['/home/user/Fierce/RH_Workshops/workshops/provisioner/workshop_collections']
DEFAULT_FORKS(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = ['/home/user/Fierce/RH_Workshops/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/user/Fierce/RH_Workshops/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 35

**Comment by IPvSean** [comment]
interesting.... do you have the controller still online?

when you look under projects can you attach a screenshot?  I think .... it tried to install JTs before Projects... and the loop in ansible was nondeterministic (not in ordered fashion... so it tried to install JTs before projects)

**Comment by IPvSean** [comment]
should be fixed, please re-open the issue if the issue persists
