### ISSUE TITLE
code server request timeout

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1445]
#### Summary
* The student code server URL times out. After a few minutes, the code server page works
  * e.g. student1-code.WORKSHOPNAME.demoredhat.com
* Tested in Chrome, Chrome Incognito window, Firefox, Firefox Private window

#### Error
```This site can’t be reachedstudent1-code.craigsec3.demoredhat.com took too long to respond.```

### Issue Type

Bug

### Extra vars file

```# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: security

# Required for podman authentication to registry.redhat.io
redhat_username: '...'
redhat_password: '...'


offline_token: '...'

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: '...'
windows_password: '...'
# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: demoredhat.com

controllerinstall: true
create_cluster: false
ibm_community_grid: false
use_manifest: true              
attendance: true
developer_mode: true
```
### Ansible Playbook Output

Workshop deployed successfully.
`certbot` assigned certificates succesfully

### Ansible Version

ansible [core 2.12.0]

### Ansible Configuration

COLLECTIONS_PATHS(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = ['/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/workshop_collections']
DEFAULT_FORKS(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = ['/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/craig/workshops/ansible/workshop/workshop_repo/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 35

**Comment by IPvSean** [comment]
odd...... 
![image](https://user-images.githubusercontent.com/6537680/155808134-f8a30ec7-a9b2-4777-876f-3b7c223eeebd.png)
also seeing this randomly :-|
