### ISSUE TITLE
AAP2 Network: failures in provisioning: add repo into controller

### ISSUE THREAD

**Issue by dpullman-emergent** [ansible/workshops#1461]
### Problem Summary

Failure to provision four of the fifty seats in a network workshop. The task ansible.workshops.populate_controller : add repo into controller failed for the first four of the fifty ansible-1 hosts. Subsequent tasks for those hosts were not completed and they were marked failed.

### Issue Type

Bug

### Extra vars file
```
---
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: testaap2net4
# amount of work benches to provision
student_total: 50
# workshop is put into networking mode
workshop_type: network
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2NDIwOTA1OTUsImp0aSI6IjE2OWM2YTQyLWIyZTktNDk4ZS1iMDMwLTdmNzJlMTgyNjkzZiIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpkcHVsbG1hbkBlbWVyZ2VudDM2MC5jb20iLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoicmhzbS1hcGkiLCJzZXNzaW9uX3N0YXRlIjoiNzI4MjA5ZjktZmIxMy00NmUxLTlmOGEtMmQyNjhiZTEyMGRmIiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyJ9.-fC-0ljpOspzlagFub-G4jLKwnK3KevtxUodn06YB7U"
# Required for podman authentication to registry.redhat.io
redhat_username: dpullman@emergent360.com
redhat_password: [redacted]
# DNS domain
workshop_dns_zone: lab-emergent360.com
## Optional Variables
# password used for student account on control node
admin_password: emergent
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
# creates HTML website for workshop
# this will install Automation controller on all control nodes
controllerinstall: true
create_cluster: false
demos: none
```
### Ansible Playbook Output

TASK [ansible.workshops.populate_controller : add repo into controller] *******************************
fatal: [testaap2net4-student31-ansible-1]: FAILED! => changed=false
  msg: Project update failed
fatal: [testaap2net4-student16-ansible-1]: FAILED! => changed=false
  msg: Project update failed
fatal: [testaap2net4-student19-ansible-1]: FAILED! => changed=false
  msg: Project update failed
fatal: [testaap2net4-student15-ansible-1]: FAILED! => changed=false
  msg: Project update failed
changed: [testaap2net4-student13-ansible-1]
changed: [testaap2net4-student42-ansible-1]
changed: [testaap2net4-student49-ansible-1]
changed: [testaap2net4-student23-ansible-1]
changed: [testaap2net4-student47-ansible-1]
changed: [testaap2net4-student21-ansible-1]
changed: [testaap2net4-student5-ansible-1]
changed: [testaap2net4-student7-ansible-1]
changed: [testaap2net4-student1-ansible-1]
changed: [testaap2net4-student6-ansible-1]
changed: [testaap2net4-student2-ansible-1]
changed: [testaap2net4-student25-ansible-1]
...

### Ansible Version

[ec2-user@ip-172-31-13-80 provisioner]$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with
Ansible 2.12. Current version: 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat
8.4.1-1)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.7]
  config file = /home/ec2-user/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/ec2-user/workshops/provisioner/workshop_collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.1
  libyaml = True

### Ansible Configuration

[ec2-user@ip-172-31-13-80 provisioner]$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with
Ansible 2.12. Current version: 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat
8.4.1-1)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
COLLECTIONS_PATHS(/home/ec2-user/workshops/provisioner/ansible.cfg) = ['/home/ec2-user/workshops/provi>
DEFAULT_FORKS(/home/ec2-user/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/ec2-user/workshops/provisioner/ansible.cfg) = ['/home/ec2-user/workshops/provi>
DEFAULT_NO_TARGET_SYSLOG(/home/ec2-user/workshops/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/workshops/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/home/ec2-user/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ec2-user/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/ec2-user/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/ec2-user/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/ec2-user/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

[ec2-user@ip-172-31-13-80 provisioner]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)

**Comment by dpullman-emergent** [comment]
Additional info: I've been running tests to provision the networking workshop for a few days. I've tried sizes from 5 to 50 seats. The lower numbered sizes often provision successfully. The 50 seat size almost always fails (I've had one successful try in about 20 attempts.)

The failures have varied. The one in this report is the most common. They include 
- TASK [ansible.workshops.populate_controller : create show command job in controller] ******************
fatal: [test-aap2-network-student7-ansible-1]: FAILED! => changed=false
  msg: 'Unable to create job_template Network-Commands: {''playbook'': [''Playbook not found for project.'']}'
- TASK [ansible.workshops.control_node : check for base64 variable first] *******************************
fatal: [test-aap2-network-student7-ansible-1 -> localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'base64_manifest' is undefined
- TASK [ansible.workshops.populate_controller : import inventory] ***************************************
fatal: [test-network-student13-ansible-1]: FAILED! => changed=true
  cmd: tower-manage inventory_import --source=/var/lib/awx/hosts --inventory-name="Workshop Inventory"

**Comment by IPvSean** [comment]
did this get fixed with the other PR we merged?

**Comment by dpullman-emergent** [comment]
No not yet. I'm working on them, but sorry I'm delayed a bit just had surgery yesterday, hope to be home tonight. I'll update my open issues with status tomorrow.
Thanks!

David

Sent from my mobile phone.
________________________________

**Comment by IPvSean** [comment]
just reopen when you recreate, no problem to reopen, going to close so I can clear out the queue and make sure I am not missing any ongoing issues

**Comment by dpullman-emergent** [comment]
Will do, thanks!

Sent from my mobile phone.
________________________________
