### ISSUE TITLE
AAP2 Network: failures in provisioning: Create EC2 instances for rtr1 node

### ISSUE THREAD

**Issue by dpullman-emergent** [ansible/workshops#1462]
### Problem Summary

Trying to provision a fifty seat workshop, failing in this case to provision rtr1.

### Issue Type

Bug

### Extra vars file

```
---
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: testaap2net5
# amount of work benches to provision
student_total: 50
# workshop is put into networking mode
workshop_type: network
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2NDIwOTA1OTUsImp0aSI6IjE2OWM2YTQyLWIyZTktNDk4ZS1iMDMwLTdmNzJlMTgyNjkzZiIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpkcHVsbG1hbkBlbWVyZ2VudDM2MC5jb20iLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoicmhzbS1hcGkiLCJzZXNzaW9uX3N0YXRlIjoiNzI4MjA5ZjktZmIxMy00NmUxLTlmOGEtMmQyNjhiZTEyMGRmIiwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyJ9.-fC-0ljpOspzlagFub-G4jLKwnK3KevtxUodn06YB7U"
# Required for podman authentication to registry.redhat.io
redhat_username: dpullman@emergent360.com
redhat_password: []
# DNS domain
workshop_dns_zone: lab-emergent360.com
## Optional Variables
# password used for student account on control node
admin_password: emergent
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
# creates HTML website for workshop
# this will install Automation controller on all control nodes
controllerinstall: true
create_cluster: false
demos: none
```

### Ansible Playbook Output

TASK [manage_ec2_instances : find correct AMI] ********************************************************
included: /home/ec2-user/workshops/provisioner/roles/manage_ec2_instances/tasks/ami_find/ami_find_network.yml for localhost

TASK [manage_ec2_instances : find ami for cisco (NETWORKING MODE)] ************************************
ok: [localhost]

TASK [manage_ec2_instances : save ami for cisco (NETWORKING MODE)] ************************************
ok: [localhost]

TASK [manage_ec2_instances : find ami for arista (NETWORKING MODE)] ***********************************
ok: [localhost]

TASK [manage_ec2_instances : save ami for arista eos (NETWORKING MODE)] *******************************
ok: [localhost]

TASK [manage_ec2_instances : find ami for juniper vsrx (NETWORKING MODE)] *****************************
ok: [localhost]

TASK [manage_ec2_instances : save ami for juniper (NETWORKING MODE)] **********************************
ok: [localhost]

TASK [manage_ec2_instances : provision workshop instances] ********************************************
included: /home/ec2-user/workshops/provisioner/roles/manage_ec2_instances/tasks/instances/instances_network.yml for localhost

TASK [manage_ec2_instances : set router types to network_type] ****************************************
skipping: [localhost]

TASK [manage_ec2_instances : Create EC2 instances for rtr1 node (NETWORK MODE)] ***********************
fatal: [localhost]: FAILED! => changed=false
  msg: wait for instances running timeout on Tue Jan 18 14:05:43 2022

PLAY RECAP ********************************************************************************************
localhost                  : ok=81   changed=23   unreachable=0    failed=1    skipped=20   rescued=0    ignored=0

### Ansible Version

[ec2-user@ip-172-31-13-80 provisioner]$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with
Ansible 2.12. Current version: 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat
8.4.1-1)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.7]
  config file = /home/ec2-user/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/ec2-user/workshops/provisioner/workshop_collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.1
  libyaml = True

### Ansible Configuration

[ec2-user@ip-172-31-13-80 provisioner]$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with
Ansible 2.12. Current version: 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat
8.4.1-1)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be
 disabled by setting deprecation_warnings=False in ansible.cfg.
COLLECTIONS_PATHS(/home/ec2-user/workshops/provisioner/ansible.cfg) = ['/home/ec2-user/workshops/provi>
DEFAULT_FORKS(/home/ec2-user/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/ec2-user/workshops/provisioner/ansible.cfg) = ['/home/ec2-user/workshops/provi>
DEFAULT_NO_TARGET_SYSLOG(/home/ec2-user/workshops/provisioner/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/home/ec2-user/workshops/provisioner/ansible.cfg) = community.general.yaml
HOST_KEY_CHECKING(/home/ec2-user/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/home/ec2-user/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/ec2-user/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/ec2-user/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/ec2-user/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

[ec2-user@ip-172-31-13-80 provisioner]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)

**Comment by dpullman-emergent** [comment]
I’ll check and update tomorrow. We’re using us-east-1.

Sent from my mobile phone.
________________________________

**Comment by IPvSean** [comment]
any word? @dpullman-emergent hopw you are doing OK

**Comment by dpullman-emergent** [comment]
Sorry, still not back yet. We're getting home PT and nursing setup. Joint replacement is apparently complicated. :P

Sent from my mobile phone.
________________________________
