### ISSUE TITLE
Error on S3 Buckets while trying to provision a workshop

### ISSUE THREAD

**Issue by HichamMourad** [ansible/workshops#1471]
### Problem Summary

Fails during provisioning of a new workshop
=================================

TASK [manage_ec2_instances : s3 bucket for persistent storage of ec2 key exists] *********************************************************************
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (4 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (3 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (2 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
fatal: [localhost]: FAILED! => {"attempts": 4, "boto3_version": "1.20.40", "botocore_version": "1.23.40", "changed": false, "error": {"code": "OperationAborted", "message": "A conflicting conditional operation is currently in progress against this resource. Please try again."}, "msg": "Failed while creating bucket: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.", "response_metadata": {"host_id": "kHw1PGvZLvvrUYjOYvzIuxe7+8mt/yKWxq2eudwHuBjv7IcQZRcKOT+LmKxk93CNCvUmoTyWrtI=", "http_headers": {"content-type": "application/xml", "date": "Fri, 21 Jan 2022 19:18:12 GMT", "server": "AmazonS3", "transfer-encoding": "chunked", "x-amz-id-2": "kHw1PGvZLvvrUYjOYvzIuxe7+8mt/yKWxq2eudwHuBjv7IcQZRcKOT+LmKxk93CNCvUmoTyWrtI=", "x-amz-request-id": "BS6H8E3MWP8WNSCE"}, "http_status_code": 409, "request_id": "BS6H8E3MWP8WNSCE", "retry_attempts": 0}}

### Issue Type

Bug

### Extra vars file

# region where the nodes will live
ec2_region: us-east-2

# name prefix for all the VMs
ec2_name_prefix: hm-workshop01

# creates student_total of workbenches for the workshop
student_total: 1

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: rhel

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "###########"

# Required for podman authentication to registry.redhat.io
redhat_username: hmourad@redhat.com
redhat_password: ############

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: ##########
# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: demoredhat.com

# automatically installs Tower to control node
controllerinstall: true

automation_hub: true

# forces ansible.workshops collection to install latest edits every time
developer_mode: true

### Ansible Playbook Output

TASK [manage_ec2_instances : s3 bucket for persistent storage of ec2 key exists] *********************************************************************
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (4 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (3 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (2 retries left).
FAILED - RETRYING: [localhost]: s3 bucket for persistent storage of ec2 key exists (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
fatal: [localhost]: FAILED! => {"attempts": 4, "boto3_version": "1.20.40", "botocore_version": "1.23.40", "changed": false, "error": {"code": "OperationAborted", "message": "A conflicting conditional operation is currently in progress against this resource. Please try again."}, "msg": "Failed while creating bucket: An error occurred (OperationAborted) when calling the CreateBucket operation: A conflicting conditional operation is currently in progress against this resource. Please try again.", "response_metadata": {"host_id": "kHw1PGvZLvvrUYjOYvzIuxe7+8mt/yKWxq2eudwHuBjv7IcQZRcKOT+LmKxk93CNCvUmoTyWrtI=", "http_headers": {"content-type": "application/xml", "date": "Fri, 21 Jan 2022 19:18:12 GMT", "server": "AmazonS3", "transfer-encoding": "chunked", "x-amz-id-2": "kHw1PGvZLvvrUYjOYvzIuxe7+8mt/yKWxq2eudwHuBjv7IcQZRcKOT+LmKxk93CNCvUmoTyWrtI=", "x-amz-request-id": "BS6H8E3MWP8WNSCE"}, "http_status_code": 409, "request_id": "BS6H8E3MWP8WNSCE", "retry_attempts": 0}}

### Ansible Version

ansible --version
ansible [core 2.12.1]
  config file = /Users/hmourad/Documents/GitHub/workshops/provisioner/ansible.cfg
  configured module search path = ['/Users/hmourad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/hmourad/Documents/GitHub/workshops/provisioner/workshop_collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.2
  libyaml = True

### Ansible Configuration

ansible.cfg content below.

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

MacOS 12.1

**Comment by IPvSean** [comment]
is this still happening @HichamMourad ?

**Comment by HichamMourad** [comment]
I haven't seen it in the last couple of weeks.  Thank you.

Kind regards,

*Hicham (he-sham) Mourad*

**Comment by IPvSean** [comment]
i think this got fixed when i got rid of self install collection method and reverted to ../ relative path calls
