### ISSUE TITLE
[RFE] Automatin Hub

### ISSUE THREAD

**Issue by willtome** [ansible/workshops#1511]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

Add a default credential called "Automation Hub" and attach to the default organization so that project syncs can pull supported collections

ansible/product-demos #44 PR is dependent on this change

**Comment by IPvSean** [comment]
👍

**Comment by IPvSean** [comment]
There is an internal ticket opened with RHPDS team RITM1128711

**Comment by IPvSean** [comment]
this is merged into RHPDS now

**Comment by anshulbehl** [comment]
Although this enables private automation hub, this ticket talked about adding cloud hub creds to controller for project collection sync to work, which doesn't work yet, I am re-opening the issue

**Comment by IPvSean** [comment]
@anshulbehl did we do this now with the new pre_built AMI?
