### ISSUE TITLE
Wrong samples in Supplemental Exercise: Ansible Network Resource Modules

### ISSUE THREAD

**Issue by carlosfparada** [ansible/workshops#1524]
### Area

Ansible Network Automation Workshop

### Proposed Changes

Supplemental Exercise: Ansible Network Resource Modules
https://aap2.demoredhat.com/exercises/ansible_network/supplemental/resource 
Wrong message
msg: ""  -> msg: "{{ rendered_config }}"
msg: ""  -> msg: "{{ parsed_config }}"
Wrong running_config format
running_config: ".txt') }}"   ->         running_config: "{{ lookup('file', 'backup/{{ inventory_hostname }}.txt') }}"
Wrong backup format
filename: ".txt" -> filename: "{{ inventory_hostname }}.txt"
Wrong backup parser
running_config: ".txt') }}" ->        running_config: "{{ lookup('file', 'backup/{{ inventory_hostname }}.txt') }}"

**Comment by IPvSean** [comment]
fixed with https://github.com/IPvSean/workshops/commit/0017db515d7dbb2bcde7142ae6fb2d12f6718da2

**Comment by carlosfparada** [comment]
Perfect!
