### ISSUE TITLE
Exercise 4: Ansible Network Resource Modules - Cisco Example not working

### ISSUE THREAD

**Issue by carlosfparada** [ansible/workshops#1525]
### Area

Ansible Network Automation Workshop

### Proposed Changes

Exercise 4: Ansible Network Resource Modules - Cisco Example
https://aap2.demoredhat.com/exercises/ansible_network/supplemental/4-resource-module-cisco

cisco.ios.snmp_server (WRONG example in the workshop)
	cisco.ios.ios_snmp_server (not working as well, not sure why)

The example uses wrong module name "snmp_server" instead of "ios_snmp_server".
Even correcting that, the modules fails when tried to be used (other modules of the same collection work fine, but not this one).

**Comment by IPvSean** [comment]
those will not work until the next major release, its a newer module in a newer EE, will happen next week

**Comment by carlosfparada** [comment]
Ok @IPvSean!
