### ISSUE TITLE
Error in Exercise 7: Creating a Survey

### ISSUE THREAD

**Issue by carlosfparada** [ansible/workshops#1527]
### Area

Ansible Network Automation Workshop

### Proposed Changes

include_role line missing in the example
Where is
    	  name: "../roles/banner" 

should be
    include_role:
        name: "../roles/banner"

**Comment by IPvSean** [comment]
@carlosfparada will be fixed in next release, thank you for opening!

**Comment by carlosfparada** [comment]
Perfect!
