### ISSUE TITLE
Output from Exercise 3.1, step 6 does not match documentation

### ISSUE THREAD

**Issue by kyleabenson** [ansible/workshops#153]
The expected output from exercise 3.1 step 6 is a JSON dump similar to:
`ok: [rtr1] => {
    "interface_facts": [
        {
            "GigabitEthernet1": {
                "config": {
                    "description": null,
                    "mtu": 1500,
                    "name": "GigabitEthernet1",
                    "type": "CSR"
                }
            }
        },
        {
            "Loopback0": {
                "config": {
                    "description": null,
                    "mtu": 1514,
                    "name": "Loopback0",
                    "type": "Loopback"
                }
            }
        },
        {
            "Loopback1": {
                "config": {
                    "description": null,
                    "mtu": 1514,
                    "name": "Loopback1",
                    "type": "Loopback"
                }
            }
        },
        {
            "Tunnel0": {
                "config": {
                    "description": null,
                    "mtu": 9976,
                    "name": "Tunnel0",
                    "type": "Tunnel"
                }
            }
        },
        {
            "Tunnel1": {
                "config": {
                    "description": null,
                    "mtu": 9976,
                    "name": "Tunnel1",
                    "type": "Tunnel"
                }
            }
        },
        {
            "VirtualPortGroup0": {
                "config": {
                    "description": null,
                    "mtu": 1500,
                    "name": "VirtualPortGroup0",
                    "type": "Virtual"
                }
            }
        }
    ]
}`

The actual output is the same content,  but in YAML format.

This is because the .ansible.cfg for the environment has the following in defaults:
`
[defaults]
--
11 | stdout_callback = yaml

`
The default behavior of Ansible is to return JSON output -- should we modify the behavior during the workshop? If so, we'll need to make sure we cover this thoroughly to ensure students understand what the change represents.

**Comment by IPvSean** [comment]
fixed with PR https://github.com/ansible/workshops/pull/331
