### ISSUE TITLE
VSCode code-server not reachable or not securely running in workshops

### ISSUE THREAD

**Issue by anshulbehl** [ansible/workshops#1533]
### Problem Summary

F5 has raised this issue and its also visible in some of the workshops when @IPvSean tried to replicate.
Needs more triage and fixes.

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

NA

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

NA

**Comment by IPvSean** [comment]
might be a match to this https://github.com/ansible/workshops/issues/1445

**Comment by IPvSean** [comment]
did you fix this?

**Comment by IPvSean** [comment]
closing this since its been 13days
