### ISSUE TITLE
Not all browsers can be used

### ISSUE THREAD

**Issue by carlosfparada** [ansible/workshops#1536]
### Area

Ansible Security Automation

### Proposed Changes

Running the security WS, I just noticed that the QRadar tool does not work properly in all browsers.
For the 3 I checked:
- Firefox, works fine
- Safari, overall works fine, but the search and filtering capabilities are not visible (and an annoying error is there all the time)
- Chrome, does not work at all, it fails not even allowing access assuming the certificate risk
As fix it can be hard (no Red Hat dependent - IBM), it would be nice to recommend in the WS description the browser to use.

**Comment by IPvSean** [comment]
@carlosfparada just here? https://aap2.demoredhat.com/exercises/ansible_security/1.4-qradar/

I can add something to the NOTE field.  Would that be sufficient?

**Comment by IPvSean** [comment]
I have a preview here of what it could look like: https://ipvsean.github.io/workshops/exercises/ansible_security/1.4-qradar/

**Comment by carlosfparada** [comment]
@IPvSean the note seems fine. The same should also apply to exercises 2.1, 2.2 and 2.3 which also use QRadar UI.

**Comment by IPvSean** [comment]
will be fixed in next release

**Comment by evanstoner** [comment]
For posterity: on Chrome you can type `thisisunsafe` while you have focus on the QRadar window to get past the certificate issue, even though the "proceed" link is not shown. This bypass word has been known to change.
