### ISSUE TITLE
Add syntax Check in Exercise 1 for 1.1 

### ISSUE THREAD

**Issue by fuadar** [ansible/workshops#157]
##### SUMMARY
The Exercise one writes a Basic Playbook but it is good to show people ansible syntax checking capability
##### ISSUE TYPE
- Feature Idea
Putting a small mistake and then having it detected by syntax check helps them understand this 
 ansible-playbook -i lab_inventory/hosts --syntax-check gather_ios_data.ym
##### ADDITIONAL INFORMATION

```  
 ansible-playbook -i lab_inventory/hosts --syntax-check gather_ios_data.yml
yaml

```

**Comment by IPvSean** [comment]
this will change with devel branch, can you see https://ipvsean.github.io/workshops/exercises/ansible_network/3-facts/
