### ISSUE TITLE
controller install - Invalid callback for stdout specified: yaml

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1574]
### Problem Summary

The Instruqt automation mesh lab requires a re-installation of automation controller to configure the execution nodes. During the install, the following error occurs:

```ERROR! Invalid callback for stdout specified: yaml```

This is from the workshop `ansible.cfg.j2` specifying the yaml stdout_callback: 
```stdout_callback = yaml```

Attempted fixes:
`ansible-galaxy collection install community.general`
- This did not resolve the issue.

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

rhel@automation-controller21 aap_install]$ ANSIBLE_BECOME_METHOD='sudo'  ANSIBLE_BECOME=True ANSIBLE_PRIVATE_KEY_FILE='/home/rhel/.ssh/instruqt_lab' ANSIBLE_HOST_KEY_CHECKING=False  ./setup.sh -e generate_dot_file=mesh.dot -e required_ram=0 -- -vvv
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rhel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rhel/aap_install/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]  
  jinja version = 2.10.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Loading collection ansible.automation_platform_installer from /home/rhel/aap_install/collections/ansible_collections/ansible/automation_platform_installer
setting up inventory plugins
host_list declined parsing /home/rhel/aap_install/inventory as it did not pass its verify_file() method
script declined parsing /home/rhel/aap_install/inventory as it did not pass its verify_file() method
auto declined parsing /home/rhel/aap_install/inventory as it did not pass its verify_file() method
Parsed /home/rhel/aap_install/inventory inventory source with ini plugin
[WARNING]: running playbook inside collection
ansible.automation_platform_installer
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
statically imported: /home/rhel/aap_install/collections/ansible_collections/ansible/automation_platform_installer/roles/postgres/tasks/vars.yml
Loading collection community.postgresql from /home/rhel/aap_install/collections/ansible_collections/community/postgresql
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
Read vars_file 'vars/collection_global_vars.yml'
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
ERROR! Invalid callback for stdout specified: yaml
[error] Oops!  An error occurred while running setup.
cp: cannot stat 'setup.log': No such file or directory
[warn] Unable to save log to /var/log/tower. Setup log saved to setup.log.

### Ansible Version

ansible [core 2.12.1]

### Ansible Configuration

  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rhel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rhel/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL 8

**Comment by craig-br** [comment]
FYI @IPvSean

**Comment by IPvSean** [comment]
That error usually refers to the fix you did... ```ansible-galaxy collection install community.general```

I am not sure why it is still giving you that error....

can you do a `ls -la ~/.ansible/collections/ansible-collections`

Also... i guess.... you are running setup as root.... so maybe try 

```sudo ansible-playbook``` i am curious if sudo/root is using a different ansible installation or collection path?

**Comment by craig-br** [comment]
I think it has to do with how the AAP installer uses collections.

**Comment by craig-br** [comment]
#### Solution
A replacement `ansible.cfg` that excludes `stdout_callback = yaml` is installed when building Instruqt images. 

More info: https://github.com/ansible/instruqt/pull/97
