### ISSUE TITLE
RHEL WS: Inventory Connection Vars preventing SSH Connection....

### ISSUE THREAD

**Issue by goetzrieger** [ansible/workshops#1585]
### Problem Summary

We still have the legacy connection vars in the controller inventory but are using SSH key-based creds now, example:

```
{
  "ansible_port": 22,
  "ansible_ssh_pass": "TbcDKQTwsli6gY",
  "ansible_user": "student1"
}
```

This has worked for a long time but now it seems to prevent the SSH connection to the managed hosts. Discovered in RHPDS deployed envs 14/03, confirmed 15/03.

When doing the ad hoc command in one of the first exercises SSH connection fails because controller tries to use the `student1` user from the vars and not `ec2-user` from the credentials.

After deleting the inventory vars manually SSH connection uses` ec2-user` and works.

I can't think of any other reason but controller handling this differently now... but looks to me like a show stopper for at least the RHEL workshop.

@IPvSean 

PR: https://github.com/ansible/workshops/pull/1586

### Issue Type

Bug

### Extra vars file

na

### Ansible Playbook Output

na

### Ansible Version

na

### Ansible Configuration

na

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

na

**Comment by cbolz** [comment]
Until this is fixed, I wrote a little workaround playbook which deletes the before mentioned variables:
https://gitlab.com/cjung/playbook-misc/-/blob/main/rhaap-wipe-inventory-vars.yml

**Comment by cbolz** [comment]
This also seems to be on the command line. in `lab_inventory/hosts`:
```ini
[all:vars]
ansible_user=student<N>
```
However, the user is "ec2-user"

**Comment by IPvSean** [comment]
this is entirely removed in devel branch now, the next release will entirely remove this from RHEL workshop 

Wondering if we should match in security @craig-br
