### ISSUE TITLE
RHPDS Windows Workshop deploy fail: subscription issue

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1608]
### Problem Summary

Windows workshop in RHPDS fails to deploy due to a missing sub

### Issue Type

Bug

### Extra vars file

AAP2 Windows workshop in RHPDS

### Ansible Playbook Output

TASK [../roles/private_automation_hub : Register and subscribe] ****************
fatal: [automation-hub-host]: FAILED! => {"changed": false, "cmd": "/sbin/subscription-manager register --auto-attach --username ansible-demo --password '********'", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Registering to: subscription.rhsm.redhat.com:443/subscription\nThe system has been registered with ID: ac4cda4d-fd1f-4522-8e0c-cf468aa353eb\nThe registered system name is: ip-172-16-60-148.ec2.internal\nInstalled Product Current Status:\nProduct Name: Red Hat Enterprise Linux for x86_64\nStatus:       Not Subscribed\n\nUnable to find available subscriptions for all your installed products.\n", "stdout_lines": ["Registering to: subscription.rhsm.redhat.com:443/subscription", "The system has been registered with ID: ac4cda4d-fd1f-4522-8e0c-cf468aa353eb", "The registered system name is: ip-172-16-60-148.ec2.internal", "Installed Product Current Status:", "Product Name: Red Hat Enterprise Linux for x86_64", "Status:       Not Subscribed", "", "Unable to find available subscriptions for all your installed products."]}

### Ansible Version

RHPDS deployer host

### Ansible Configuration

RHPDS deployer host

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHPDS Deployer host

**Comment by cloin** [comment]
This is out of our control as this task relies on username/password for a valid account with proper subscriptions for the product. Please check the red hat portal account that is used by the provisioner for the proper subscriptions and try again.

**Comment by IPvSean** [comment]
this is fixed in our `main` branch now https://github.com/ansible/workshops/issues/1612
