### ISSUE TITLE
RHPDS deployoment failing with CheckSoftwareDeploy

### ISSUE THREAD

**Issue by amathoman** [ansible/workshops#1612]
### Problem Summary

Hi Team,

I have been trying to deploy the RHPDS workshops (Network or Linux) and have been constantly getting the error CheckSoftwareDeploy.  I have tried Linux and Network workshops in APAC.

I raised this with the RHPDS team and they have suggested i raise an issue on the repo...  Pelase find their response below...

--------------------------------
This is a known error - this lab is managed by the Ansible BU. They have a subscription-pool which the manage and to which RHPDS have no access. From what we can tell, the Ansible BU's special deployer does not clean subscriptions when labs are filled, thus the labs are now unable to obtain subs and thus fail to deploy.
 
We have notified the Ansible BU of this issue and passed the information about the AAP2 Windows workshop on to them. Feel free to raise a new issue in github to them at https://github.com/ansible/workshops if you want to directly engage them (error below):
 
For reference, the error is
fatal: [automation-hub-host]: FAILED! => {"changed": false, "cmd": "/sbin/subscription-manager register --auto-attach --username ansible-demo --password '********'", "msg": "", "rc": 1, "st
derr": "", "stderr_lines": [], "stdout": "Registering to: [subscription.rhsm.redhat.com:443/subscription](http://subscription.rhsm.redhat.com:443/subscription)\nThe system has been registered with ID: e8726103-8d61-4332-90e9-71228455247f\nThe re
gistered system name is: ip-172-16-26-16.ec2.internal\nInstalled Product Current Status:\nProduct Name: Red Hat Enterprise Linux for x86_64\nStatus: Not Subscribed\n\nUnable to find a
vailable subscriptions for all your installed products.\n", "stdout_lines": ["Registering to: [subscription.rhsm.redhat.com:443/subscription](http://subscription.rhsm.redhat.com:443/subscription)", "The system has been registered with ID: e87261
03-8d61-4332-90e9-71228455247f", "The registered system name is: ip-172-16-26-16.ec2.internal", "Installed Product Current Status:", "Product Name: Red Hat Enterprise Linux for x86_64", "St
atus: Not Subscribed", "", "Unable to find available subscriptions for all your installed products."]}
 --------------------------------

### Issue Type

Bug

### Extra vars file

N/A. Handled by RHDS team

### Ansible Playbook Output

I do not have access to the playbook output.  the email below was received...

Your service provision request for RHPDS-RH-amatheso-redhat.com-PROD_AAP2_ANSIBLE_WORKSHOPS_TRAINING-75aa for catalog item AAP2 Networking Automation Workshop failed when provisioning.
The problem is happening in step checkSoftwareDeploy
The deployment failed while deploying the lab software. This could be due to a bug in the lab playbook or its taking too long to run. If you know the demo/lab owner you may want to let them know it is failing.
The administrators have been alerted of this problem and will look into it as soon as possible. In the meantime you can attempt to order this service again. If this problem persists please go to https://red.ht/rhpds-help
To review the status of all current issues, you can visit the [GPTE Public Status Page](https://gpte.statuspage.io/) and subscribe for updates.

### Ansible Version

Not Available (assume 2.11)

### Ansible Configuration

Not Available

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

Assume RHEL

**Comment by cloin** [comment]
@IPvSean do we have a pool of subscriptions? We can fix the cleanup but if thats happening but I don't think we can free up subs in the pool as username and password are passed as extravars

**Comment by IPvSean** [comment]
i just cleaned it up manually for now in access.redhat.com
