### ISSUE TITLE
Inconsistent documentation of timing for each of the playbook runs

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1673]
### Area

Smart Management Automation Workshop

### Proposed Changes

In the beginning of the document it called out the time required for each of the playbooks to run.  I thought this was a great idea, but not consistent through the document.

Select Templates and click on thelaunchto the right of the SETUP / Controller job template.
You will be taken to the Jobs > SETUP / Controller output window where you will be able to follow each task executed as part of the playbook. **This will take approximately 2 mins to complete.**

Suggest adding these for each of the playbooks runs.

**Comment by IPvSean** [comment]
for @heatmiser

**Comment by IPvSean** [comment]
seems like this has been resolved, please re-open if this is not the case
