### ISSUE TITLE
Request changes to main workshop page

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1674]
### Area

Smart Management Automation Workshop

### Proposed Changes

Table of Contents
[Use Cases](https://aap2.demoredhat.com/exercises/ansible_smart_mgmt/#use-cases)
[Lab Diagram](https://aap2.demoredhat.com/exercises/ansible_smart_mgmt/#lab-diagram)
[Guide](https://aap2.demoredhat.com/exercises/ansible_smart_mgmt/#guide)

**Include**  additional sections to match other workshops:
- Presentations
- Time Planning

**Change** "Guilde" here to "Workshop Exercises"

**Comment by IPvSean** [comment]
for @heatmiser

**Comment by taruch** [comment]
I did a pull, and I'm planning to update the relevant README.md and do a pull request.

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/pull/1677
