### ISSUE TITLE
A Note about using Satellite vs. Ansible Automation Platform for this...

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1676]
### Area

Smart Management Automation Workshop

### Proposed Changes

Out of the box, Satellite 6 supports [RHEL systems roles](https://access.redhat.com/articles/3050101) (a collection of Ansible Roles) for a limited set of administration tasks. An Ansible Automation Platform subscription is need to execute more complex Ansible jobs, such as OS conversions and upgrades. 

This isn’t really true anymore - Satellite can be used to do OS conversions and upgrades now using Convert2RHEL and LEAAP
https://www.redhat.com/en/blog/steps-converting-centos-linux-convert2rhel-and-red-hat-satellite
https://www.redhat.com/en/blog/leapp-upgrade-using-red-hat-satellite-6

It would be better to say that Satellite can be used to do OS conversions and upgrades, however Ansible Automation Platform is required to do any complicated OS conversions and upgrades that require logic to meet uptime requirements.

**Comment by IPvSean** [comment]
@heatmiser FYI

**Comment by taruch** [comment]
These changes were already made in the last pull request.
