### ISSUE TITLE
Documentation update - font issue, content

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1678]
### Area

Smart Management Automation Workshop

### Proposed Changes

This section has writing that is unreadable due to font color (or rather the color of the font against the highlight).
"""
NOTE For the following job template, review the Variables section of the template, paying particular note to the group_tag_map variable. A mapping of nodes to group names is defined. EC2 tags for these group names will be assigned to the nodes defined and this will be utilized later via dynamic inventory building to construct Ansible inventory groups containing the nodes defined, ie. “frontends”, “apps”, “appdbs”.
"""

Also, if we just told them to go in and look at the variables, they are already in the template, and should just click the launch button at the bottom, or we should suggest they go back to the templates page and click the rocketship.

This section has writing that is unreadable due to font color (or rather the color of the font against the highlight).
"""
NOTE Before running the dynamic inventory update templates in the upcoming steps, first navigate to the Inventories location in AAP and review the following inventories:
"""
Also, don't make this a note, make it a step.

**Comment by IPvSean** [comment]
You need to link me to where you are seeing that

**Comment by IPvSean** [comment]
please reopen with screenshot so we can see what the issue is
