### ISSUE TITLE
Teardown of lab doesn't remove AWS Route 53 A Records for VSCode Server

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/workshops#1682]
### Problem Summary

The Teardown of lab doesnt trigger the deletion of the A Record in Route53 created for the VSCode instance leaving remanant A Records behind. 

**Fix is easy (either rename the file teardown_aws.yml to aws.yml or fix the code to be teardown_{{ dns_type }}.yml)**

ls roles/code_server/tasks/dns
[root@DS9 workshops-aap2]# ls -AlFh roles/code_server/tasks/dns/
total 8.0K
-rw-r--r--. 1 root root  82 Apr 27 12:24 none.yml
-rw-r--r--. 1 root root 982 Apr 27 12:24 teardown_aws.yml

cat roles/code_server/tasks/teardown.yml

```
---
- name: delete DNS specific information
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{role_path}}/tasks/dns/{{ dns_type }}.yml"
    - "{{role_path}}/tasks/dns/none.yml"

```

### Issue Type

Bug

### Extra vars file

```
---
# region where the nodes will live
ec2_region: us-west-2
# name prefix for all the VMs
ec2_name_prefix: MMABIS-AnsibleGH
# amount of work benches to provision
student_total: 50
# workshp runs in F5 mode
workshop_type: f5
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token: "OMITED"
# Required for podman authentication to registry.redhat.io
redhat_username: OMITED
redhat_password: "OMITED"
# DNS domain
workshop_dns_zone: "f5demo.net"
## Optional Variables
# password used for student account on control node
admin_password: Ansible123!
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
create_cluster: false
ibm_community_grid: false

```

### Ansible Playbook Output

![image](https://user-images.githubusercontent.com/1888195/165594872-fe5dfc52-90c9-4e48-a5d8-2fd82abf4ddc.png)

### Ansible Version

[root@DS9 workshops-aap2]# ansible --version
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Nov  9 2021, 13:31:27) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.1
  libyaml = True

### Ansible Configuration

[root@DS9 workshops-aap2]# ansible-config dump --only-changed
[root@DS9 workshops-aap2]#

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Happend on RHEL (Latest) and Rocky Linux (Python 3.9)

**Comment by IPvSean** [comment]
fixed in `devel` by @anshulbehl
