### ISSUE TITLE
Update for Exercises link

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1689]
### Area

Smart Management Automation Workshop

### Proposed Changes

FROM: 
Presentations
The exercises are self explanatory and guide the participants through the entire lab. All concepts are explained when they are introduced.

There is an optional presentation available to support the workshops and explain Automation, the basics of Ansible and the topics of the exercises in more detail. Workshop presentation is WIP and will be added soon.

Also have a look at our Ansible Best Practices Deck: [Ansible Best Practices](https://aap2.demoredhat.com/decks/ansible_best_practices.pdf)

TO:
Presentations
The exercises are self explanatory and guide the participants through the entire lab. All concepts are explained when they are introduced.

There is an optional presentation available to support the workshops and explain Automation, the basics of Ansible and the topics of the exercises in more detail. Workshop presentation is located at [Automated Smart Management Workshop](https://aap2.demoredhat.com/decks/ansible_smart_mgmt.pdf).

Also have a look at our Ansible Best Practices Deck: [Ansible Best Practices](https://aap2.demoredhat.com/decks/ansible_best_practices.pdf)

**Comment by IPvSean** [comment]
fixed by fixed by https://github.com/ansible/workshops/pull/1690
