### ISSUE TITLE
Increase "Idle Time Force Log Out"

### ISSUE THREAD

**Issue by MKletz** [ansible/workshops#1691]
### Problem Summary

Often times during demos or workshops we can have some wasted time or hangups do to the forced log outs from the default idle time. Since these are ephemeral non-production environments I think this would be a great harmless quality of life improvement for customer facing activity.

### Issue Type

Feature Request

### Extra vars file

N/A

### Ansible Playbook Output

N/A

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

N/A

**Comment by IPvSean** [comment]
question to @MKletz , are you talking about the console SSH, code-server or Automation controller webUI?

**Comment by IPvSean** [comment]
@MKletz can you provide additional information? Going to close this issue until you comment.

**Comment by MKletz** [comment]
@IPvSean sorry I missed the first notification. I was referring to the Automation controller webUI
