### ISSUE TITLE
"Note" <blockquote> css display issues (can't read)

### ISSUE THREAD

**Issue by mkbredem** [ansible/workshops#1710]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

First encountered at the bottom of Section 1: Creating the Playbook in exercise 5 of the windows workshop

![image](https://user-images.githubusercontent.com/56933449/168819944-9ccf7eb6-fff8-4d62-88e4-e437c02c7c95.png)

**Comment by cloin** [comment]
Yeah I see it too. Switching themes doesn't seem to have any affect. I may just look to change these away from blockquotes to a table maybe instead of adding custom CSS.
