### ISSUE TITLE
[Network Automation WS] Wrong list of Execution Environments

### ISSUE THREAD

**Issue by nleiva** [ansible/workshops#1711]
### Problem Summary

Step 3 - Examining Execution Environments shows an image with four EE's and references the `ee-supported-rhel8` execution environment, but students only see one EE: `network-ee `

```
NAME                                        TAG            EXECUTION ENVIRONMENT                         CREATED                  SIZE
0│network-ee (primary)                        latest                          True                         6 weeks ago              1.04 GB
```

### Issue Type

Documentation

### Extra vars file

n/a

### Ansible Playbook Output

n/a

### Ansible Version

n/a

### Ansible Configuration

n/a

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

n/a

**Comment by IPvSean** [comment]
Hey @nicholas-chia 
![image](https://user-images.githubusercontent.com/6537680/187272676-5f07ef54-dfaf-4e52-9801-291eceabc618.png)

is that not sufficient?  We were trying to match directions across different workshops and enviornments and the EEs change a lot.

**Comment by nleiva** [comment]
Thanks @IPvSean. A customer brought this up while I was running the Network workshop, so I showed them how you could open an issue for the workshop live. They thought it was misleading. Up to you :-)

**Comment by IPvSean** [comment]
fixed in `devel`
