### ISSUE TITLE
Security workshop provision - The conditional check 'security_console == 'qradar'' failed.

### ISSUE THREAD

**Issue by craig-br** [ansible/workshops#1719]
### Problem Summary

Provisioning security workshop fails with

```
FAILED! => {"msg": "The conditional check 'security_console == 'qradar'' failed. The error was: error while evaluating conditional (security_console == 'qradar'): 'security_console' is undefined"}
```

### Issue Type

Bug

### Extra vars file

# region where the nodes will live
ec2_region: us-east-1

# name prefix for all the VMs
ec2_name_prefix: craigsec5

# creates student_total of workbenches for the workshop
student_total: 1

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: security

# Required for podman authentication to registry.redhat.io
redhat_username: ****
redhat_password: ****

offline_token:  ****

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: ****
windows_password: ****
# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: demoredhat.com

controllerinstall: true
create_cluster: false
ibm_community_grid: false
use_manifest: true
attendance: false
developer_mode: true

ec2_xtra:
  qradar:
    owners: 721066863947
    size: t3.2xlarge
    os_type: linux
    disk_volume_type: gp3
    disk_space: 300
    disk_iops: 3000
    disk_throughput: 125
    architecture: x86_64
    filter: 'AnsibleSecurity-QRadarCE*'
    username: ec2-user
    python_interpreter: '/usr/bin/python'

##

### Ansible Playbook Output

TASK [Gathering Facts] *********************************************************
fatal: [craigsec5-student1-qradar]: FAILED! => {"msg": "The conditional check 'security_console == 'qradar'' failed. The error was: error while evaluating conditional (security_console == 'qradar'): 'security_console' is undefined"}

PLAY RECAP *********************************************************************
craigsec5-student1-ansible-1 : ok=142  changed=100  unreachable=0    failed=0    skipped=8    rescued=0    ignored=0
craigsec5-student1-attacker : ok=17   changed=10   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
craigsec5-student1-qradar  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
craigsec5-student1-snort   : ok=11   changed=6    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
localhost                  : ok=128  changed=55   unreachable=0    failed=0    skipped=27   rescued=0    ignored=0

### Ansible Version

ansible [core 2.12.5]
  config file = None
  configured module search path = ['/Users/craig/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/craig/.virtualenvs/ansible_latest/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/craig/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/craig/.virtualenvs/ansible_latest/bin/ansible
  python version = 3.10.4 (main, Jun  1 2022, 18:40:56) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.1
  libyaml = True

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Mac Monterey (ARM)

**Comment by IPvSean** [comment]
is this fixed? @craig-br
