### ISSUE TITLE
Workshop Project

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1724]
### Area

Other

### Proposed Changes

    <td>Project</td>
    <td>Workshop Project</td>

Workshop Project does not exist at this point in the exercise.  It is called out in the previous section - but does not actually exist in controller.  I had to create the project using the information in the "The Apache-configuration Role" section.
![Screenshot from 2022-06-09 15-29-03](https://user-images.githubusercontent.com/1851572/172929051-7bae2b75-b267-4524-8529-91241ffe681d.png)

Need to either have the workshop project in the setup automation, or add it as a step before this section (I recommend the former due to the time constraints on this workshop).

**Comment by IPvSean** [comment]
@anshulbehl since you just fixed the Ansible_90 can you investigate this?

**Comment by anshulbehl** [comment]
@dbaugh0310 In which exercise do you see this issue for RHEL and RHEL_90 workshops, I can check accordingly

**Comment by dbaugh0310** [comment]
Exercise 5 requires the workshop project.

**Comment by IPvSean** [comment]
@anshulbehl did you fix this?

**Comment by IPvSean** [comment]
follow up @anshulbehl
