### ISSUE TITLE
Ansible 90 Workshop - Timesync Role Failing

### ISSUE THREAD

**Issue by dbaugh0310** [ansible/workshops#1729]
### Problem Summary

While attempting to run the Linux System Roles exercise the timesync playbook fails because it cannot find the RHEL system role. 

### Issue Type

Bug

### Extra vars file

I'm using the lab in rhpds, I don't know where the vars file is. 

### Ansible Playbook Output

ERROR! the role 'redhat.rhel_system_roles.timesync' was not found in /runner/project/playbooks/security/roles:/runner/requirements_roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/runner/project/playbooks/security
The error appears to be in '/runner/project/playbooks/security/hardening.yml': line 20, column 15, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
      include_role:
        name: redhat.rhel_system_roles.timesync
              ^ here

### Ansible Version

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/student1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/student1/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

### Ansible Configuration

[student1@ansible-1 ansible-files]$ ansible-config dump --only-changed
ACTION_WARNINGS(/etc/ansible/ansible.cfg) = False
COLLECTIONS_ON_ANSIBLE_VERSION_MISMATCH(/etc/ansible/ansible.cfg) = ignore
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/student1/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 200
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL

**Comment by abenokraitis** [comment]
@anshulbehl can you take a look at this one?

**Comment by cloin** [comment]
Looks like the EE should have the collection: https://github.com/cloin/ee-builds/runs/6951828498?check_suite_focus=true#step:9:34

**Comment by anshulbehl** [comment]
I will work on fixing this.
