### ISSUE TITLE
AAP2 Ansible Networking Workshop fails in RHPDS

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1743]
### Problem Summary

The deploys are failing with TASK:

TASK [../roles/manage_ec2_instances : save ami for cisco (NETWORKING MODE)] ****
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: No last item, sequence was empty.\n\nThe error appears to be in '/tmp/aap2-ansible-workshops-58d6/ansible_agnostic_deployer/ansible/workdir/aap2-ansible-workshops/roles/manage_ec2_instances/tasks/ami_find/ami_find_network.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: save ami for cisco (NETWORKING MODE)\n      ^ here\n"}

### Issue Type

Bug

### Extra vars file

https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/ansible-workshops/vars/rhel_tower_workshop_vars.yml

### Ansible Playbook Output

The deploys are failing with TASK:

TASK [../roles/manage_ec2_instances : save ami for cisco (NETWORKING MODE)] ****
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: No last item, sequence was empty.\n\nThe error appears to be in '/tmp/aap2-ansible-workshops-58d6/ansible_agnostic_deployer/ansible/workdir/aap2-ansible-workshops/roles/manage_ec2_instances/tasks/ami_find/ami_find_network.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: save ami for cisco (NETWORKING MODE)\n      ^ here\n"}

### Ansible Version

./archives/prod-aap2-ansible-workshops-c4f8.log

### Ansible Configuration

./archives/prod-aap2-ansible-workshops-c4f8.log

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

rhpds - RHEL

**Comment by anshulbehl** [comment]
This is fixed now and merged into workshops main.
I am going to test other labs in DEV before acking a push to
master/aap2-master of gpe repo.
