### ISSUE TITLE
Location of default vars for ec2 AMIs in documentation

### ISSUE THREAD

**Issue by taruch** [ansible/workshops#1745]
### Area

Other

### Proposed Changes

# default vars for ec2 AMIs (ec2_info) are located in provisioner/roles/manage_ec2_instances/defaults/main/main.yml

They are actually located in roles/manage_ec2_instances/defaults/main/main.yml

**Comment by IPvSean** [comment]
@taruch not sure I understand here, is this a documentation update to where it actually is?

**Comment by IPvSean** [comment]
no response from [taruch](https://github.com/taruch)
