### ISSUE TITLE
AAP2 Windows Workshop fails to provision users

### ISSUE THREAD

**Issue by 9strands** [ansible/workshops#1750]
### Problem Summary

AAP2 for Windows Workshop provisions cleanly, but actually fails to provision student users.
Issue is documented here: https://chat.google.com/room/AAAAIFjw_Tw/ImvaeToaUow in the Ansible Workshops & Demos discussion room.

Issue is GUID 1078

Talking with Anshul, we believe this affects all other AAP labs with something in the deployer code changing from using student1-X to only "student" on each instance.  This causes issues with VSCode and Gitea access, which expects a numbered user in the deployment, but as only /home/student/ exists, it seems to break the lab function, even though the deployer throws no error.

### Issue Type

Bug

### Extra vars file

No idea where this is in the RHPDS deployer, GUID is 1078

### Ansible Playbook Output

This playbook has potentially sensitive information - log is available on the admin host.

### Ansible Version

TASK [../roles/workshop_check_setup : make sure (windows) packages required are installed on this control node] ***
ok: [localhost] => {"changed": false, "cmd": "/home/opentlc-mgr/virtualenvs/ansible-workshops-v2.1-py-v3.8-ansible-v2.11/bin/pip3 list --format=freeze", "stderr": "WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.\nYou should consider upgrading via the '/home/opentlc-mgr/virtualenvs/ansible-workshops-v2.1-py-v3.8-ansible-v2.11/bin/python -m pip install --upgrade pip' command.\n", "stderr_lines": ["WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.", "You should consider upgrading via the '/home/opentlc-mgr/virtualenvs/ansible-workshops-v2.1-py-v3.8-ansible-v2.11/bin/python -m pip install --upgrade pip' command."], "stdout": "ansible-core==2.11.7\nawscli==1.22.49\nbcrypt==3.2.0\nboto==2.49.0\nboto3==1.20.49\nbotocore==1.23.54\ncertifi==2021.10.8\ncffi==1.15.0\ncharset-normalizer==2.0.12\ncolorama==0.4.3\ncryptography==36.0.1\ndistlib==0.3.4\ndocutils==0.15.2\nfilelock==3.6.0\nidna==3.3\nJinja2==3.0.3\njmespath==0.10.0\nMarkupSafe==2.1.0\nnetaddr==0.8.0\nntlm-auth==1.5.0\npackaging==21.3\nparamiko==2.8.1\npasslib==1.7.4\npathspec==0.9.0\npip==22.0.4\nplatformdirs==2.5.1\npluggy==1.0.0\npy==1.11.0\npyasn1==0.4.8\npycparser==2.21\nPyNaCl==1.5.0\npyOpenSSL==22.0.0\npyparsing==3.0.7\npyspnego==0.5.0\npython-dateutil==2.8.2\npywinrm==0.4.2\nPyYAML==6.0\nrequests==2.27.1\nrequests-credssp==1.2.0\nrequests-ntlm==1.1.0\nresolvelib==0.5.4\nrsa==4.7.2\ns3transfer==0.5.2\nsetuptools==60.9.3\nsix==1.16.0\ntoml==0.10.2\ntox==3.22.0\nurllib3==1.26.8\nvirtualenv==20.13.3\nwheel==0.37.1\nxmltodict==0.12.0\nyamllint==1.26.3\n", "stdout_lines": ["ansible-core==2.11.7", "awscli==1.22.49", "bcrypt==3.2.0", "boto==2.49.0", "boto3==1.20.49", "botocore==1.23.54", "certifi==2021.10.8", "cffi==1.15.0", "charset-normalizer==2.0.12", "colorama==0.4.3", "cryptography==36.0.1", "distlib==0.3.4", "docutils==0.15.2", "filelock==3.6.0", "idna==3.3", "Jinja2==3.0.3", "jmespath==0.10.0", "MarkupSafe==2.1.0", "netaddr==0.8.0", "ntlm-auth==1.5.0", "packaging==21.3", "paramiko==2.8.1", "passlib==1.7.4", "pathspec==0.9.0", "pip==22.0.4", "platformdirs==2.5.1", "pluggy==1.0.0", "py==1.11.0", "pyasn1==0.4.8", "pycparser==2.21", "PyNaCl==1.5.0", "pyOpenSSL==22.0.0", "pyparsing==3.0.7", "pyspnego==0.5.0", "python-dateutil==2.8.2", "pywinrm==0.4.2", "PyYAML==6.0", "requests==2.27.1", "requests-credssp==1.2.0", "requests-ntlm==1.1.0", "resolvelib==0.5.4", "rsa==4.7.2", "s3transfer==0.5.2", "setuptools==60.9.3", "six==1.16.0", "toml==0.10.2", "tox==3.22.0", "urllib3==1.26.8", "virtualenv==20.13.3", "wheel==0.37.1", "xmltodict==0.12.0", "yamllint==1.26.3"]}

### Ansible Configuration

Unsure of how to pull this from the admin host.

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL

**Comment by cloin** [comment]
It looks like student environments are working fine. However, the link that is created for the student to access vs code had the wrong path to the workshop project.

**Comment by cloin** [comment]
@9strands the only thing I found on my first run was that code server didn't open the project directory because there's no studentN home directory. Did you happen to find anything else?

**Comment by cloin** [comment]
I believe this can be closed out. The directories were being created, but the link to codeserver didn't have the correct remote path to the project directory.
