### ISSUE TITLE
Exercise 6: Creating an Automation controller Job Template -- SSH failure to backup-server

### ISSUE THREAD

**Issue by hindman-redhat** [ansible/workshops#1769]
### Area

Ansible Network Automation Workshop

### Proposed Changes

In exercise 6 you're asked to create and run a 'Backup network configurations' template. The automation will fail with a similar message as below:

"unreachable": true,
  "msg": "Failed to connect to the host via ssh: Warning: Permanently added '3.14.245.38' (ECDSA) to the list of known hosts.\r\nstudent@3.14.245.38: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).",
  "changed": false

This error occurs because credentials to the backup-server are deployed with incorrect values. Fix is to go to AAP Controller and navigate to: Hosts > backup-server and edit the "ansible_user" to "ec2-user".

**Comment by IPvSean** [comment]
this is fixed and in release on `main`
