### ISSUE TITLE
Bug report for AAP2 Windows Workshop in RHPDS

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#1781]
### Problem Summary

AAP2 Windows consistently fails with the same error:

TASK [../../roles/common : configure sudoers] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'student_user' is undefined
fatal: [gitlab]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'student_user' is undefined"}

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

TASK [../../roles/common : configure sudoers] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'student_user' is undefined
fatal: [gitlab]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'student_user' is undefined"}

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

NA

**Comment by IPvSean** [comment]
my understanding from talking to @anshulbehl is that this is now fixed on RHPDS
