### ISSUE TITLE
Bug report for Bug report for rhel_90 workshop module, module 7, step 4

### ISSUE THREAD

**Issue by hightechrdn** [ansible/workshops#1791]
### Problem Summary

The AAP Controller instance deployed by RHPDS does not have a Job Template "SERVER / Red Hat Insights", so module 7, step 4 cannot be completed. This Job Template needs to be added to the default Controller configuration for this workshop.

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

N/A

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

N/A

**Comment by IPvSean** [comment]
That exercise is currently not supported, it is not in the agenda

![image](https://user-images.githubusercontent.com/6537680/187730674-cdba3043-7cb2-4ad7-9cbe-2cba6bc9b63d.png)
