### ISSUE TITLE
Bug report for Ansible Workshops

### ISSUE THREAD

**Issue by 9strands** [ansible/workshops#1792]
### Problem Summary

AAP2 Networking Automation Workshop [rh9acb] tdubiel:
fatal: [localhost]: FAILED! => {"boto3_version": "1.20.49", "botocore_version": "1.23.54", "changed": false, "error": {"code": "OptInRequired", "message": "In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3gruvlcso4s66wfg2mdzxg8z6"}, "msg": "Failed to create new EC2 instance: An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3gruvlcso4s66wfg2mdzxg8z6", "response_metadata": {"http_headers": {"cache-control": "no-cache, no-store", "content-type": "text/xml;charset=UTF-8", "date": "Tue, 30 Aug 2022 22:00:34 GMT", "server": "AmazonEC2", "strict-transport-security": "max-age=31536000; includeSubDomains", "transfer-encoding": "chunked", "vary": "accept-encoding", "x-amzn-requestid": "dda5ce5c-d18b-4e51-aa57-b355fd824fee"}, "http_status_code": 401, "request_id": "dda5ce5c-d18b-4e51-aa57-b355fd824fee", "retry_attempts": 0}}

### Issue Type

Bug

### Extra vars file

Available on the Admin host

### Ansible Playbook Output

AAP2 Networking Automation Workshop [rh9acb] tdubiel:
fatal: [localhost]: FAILED! => {"boto3_version": "1.20.49", "botocore_version": "1.23.54", "changed": false, "error": {"code": "OptInRequired", "message": "In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3gruvlcso4s66wfg2mdzxg8z6"}, "msg": "Failed to create new EC2 instance: An error occurred (OptInRequired) when calling the RunInstances operation: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=3gruvlcso4s66wfg2mdzxg8z6", "response_metadata": {"http_headers": {"cache-control": "no-cache, no-store", "content-type": "text/xml;charset=UTF-8", "date": "Tue, 30 Aug 2022 22:00:34 GMT", "server": "AmazonEC2", "strict-transport-security": "max-age=31536000; includeSubDomains", "transfer-encoding": "chunked", "vary": "accept-encoding", "x-amzn-requestid": "dda5ce5c-d18b-4e51-aa57-b355fd824fee"}, "http_status_code": 401, "request_id": "dda5ce5c-d18b-4e51-aa57-b355fd824fee", "retry_attempts": 0}}

### Ansible Version

RHPDS current

### Ansible Configuration

RHPDS current

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL

**Comment by 9strands** [comment]
Examples of failures today:

AAP2 Networking Automation Workshop [rh067f]
AAP2 Networking Automation Workshop [rhd351]
AAP2 Networking Automation Workshop [rha6c0]
AAP2 Networking Automation Workshop [rh189f]

**Comment by cloin** [comment]
It looks like RHPDS team need to accept the terms to use the images referenced. Can you confirm this has been done?

**Comment by cloin** [comment]
This is an action that needs to be done on the AWS account that rhpds is pointing this code at. I’d open a ticket with that team as well.

**Comment by IPvSean** [comment]
You just click the link and subscribe… not sure why it was unsubbed
randomly

**Comment by 9strands** [comment]
Hi, @IPvSean 

  Looking into the GPE account, the grant for this item exists already for this item.  We cannot tell why this is asking us to accept terms when we've already got an active "Grant" for it.

**Comment by 9strands** [comment]
So, we use a service account which has no console access in order to provision these labs - are we going to have to find a way to login to that specific account temporarily, accept the license for that individual user, and then disable it?  It seems we should be able to use the account-wide grant since this AMI is already accepted in the GPE account itself.  Ideas?

**Comment by IPvSean** [comment]
@9strands is this resolved now?  This should be something your account subscribes to yes... it is documented here: https://github.com/ansible/workshops/blob/devel/docs/setup.md

**Comment by abenokraitis** [comment]
Assuming this is resolved given no response since last comment.
