### ISSUE TITLE
Supplemental Exercise Japanese Translation

### ISSUE THREAD

**Issue by akira6592** [ansible/workshops#1809]
### Area

Ansible Network Automation Workshop

### Proposed Changes

The  README.ja.md under `Supplemental Exercise: Ansible Network Resource Modules` does not translated yet.
https://github.com/ansible/workshops/blob/devel/exercises/ansible_network/supplemental/resource/README.ja.md

Although I don't permission to assign I am going to translate.

**Comment by IPvSean** [comment]
yay 👍
