### ISSUE TITLE
Incorrect SHA value for aap.tar.gz prevents workshop from deploying

### ISSUE THREAD

**Issue by benblasco** [ansible/workshops#1821]
### Problem Summary

The SHA value defined for the download of the AAP installer does not point to a valid downloadable package:

[workshops](https://github.com/ansible/workshops)/[roles](https://github.com/ansible/workshops/tree/devel/roles)/[aap_download](https://github.com/ansible/workshops/tree/devel/roles/aap_download)/[defaults](https://github.com/ansible/workshops/tree/devel/roles/aap_download/defaults)/main.yml

I was able to successfully deploy the workshop *using an AWS OPEN environment* using the following package:
 Ansible Automation Platform 2.2.1 Setup Bundle

Last modified:
    2022-09-13
SHA-256 Checksum:
    878c2c2705e5f50e734f27fc7c50b39ddf4b2ace2d40290477d19477b82f9904 

https://access.redhat.com/downloads/content/480/ver=2.2/rhel---9/2.2/x86_64/product-software

I am not sure if this issue is impacting RHPDS deployments, but I can see the incorrect SHA defined in both the devel and main branches.

### Issue Type

Bug

### Extra vars file

This is what I used (with some help from @heatmiser ) to deploy the workshop.  It is a copy of the sample vars file for RHEL:
https://github.com/ansible/workshops/blob/main/provisioner/sample_workshops/sample-vars-rhel.yml

I had to set pre_build to false for this to work at all.  That allowed me to get to the stage where the download of aap.tar.gz failed

```
---
# region where the nodes will live
ec2_region: us-east-2
# name prefix for all the VMs
ec2_name_prefix: rhel01
# amount of work benches to provision
student_total: 1
# workshop is put into rhel mode
workshop_type: rhel
# Required for AAP download https://access.redhat.com/articles/3626371
offline_token: "<TOKEN>"
# Required for podman authentication to registry.redhat.io
redhat_username: rhn-sa-bblasco
redhat_password: <password>
# DNS domain
workshop_dns_zone: sandboxXXX.opentlc.com
## Optional Variables
# password used for student account on control node
admin_password: <password>
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
# this will install Automation controller on all control nodes
controllerinstall: true
create_cluster: false
pre_build: false

```

### Ansible Playbook Output

Can be provided upon request

### Ansible Version

```
(rhel01) [bblasco@fedora rhel01]$ ansible --version
/home/bblasco/rhel01/lib64/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.11.7] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bblasco/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bblasco/rhel01/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/bblasco/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/bblasco/rhel01/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  jinja version = 3.1.2
  libyaml = False
(rhel01) [bblasco@fedora rhel01]$ 
```

### Ansible Configuration

No change.

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Fedora 36 Server deployed from Cloud QCOW2 image

**Comment by rclements-redhat** [comment]
I have noticed this as well. I will prepare a fix and pull request.

**Comment by rclements-redhat** [comment]
The correct sha value is:

provided_sha_value: ea2843fae672274cb1b32447c9a54c627aa5bdf5577d9a6c7f957efe68be8c01

This is being discussed in a complete extra_vars overhaul in #1824 

If #1824 is accepted, then this bug fix will be closed with it as #1824 fixes this.

**Comment by benblasco** [comment]
So the fix in #1824 covers all workshops, not just the Smart Management workshop?

**Comment by rclements-redhat** [comment]
Good point. I'll double-check to ensure all sha values are updated across multiple workshops.

**Comment by IPvSean** [comment]
@benblasco can you confirm this is fixed?  Noticed this issue was from July and not been updated?  Go ahead and reopen if this is still an issue
