### ISSUE TITLE
Bug report for Ansible Workshops Network

### ISSUE THREAD

**Issue by criscofats** [ansible/workshops#1828]
### Problem Summary

When provisioning `workshop_type: 'network'` and `network_type: juniper` the provisioner will fail once it reaches this playbook: `/workshops/tree/devel/roles/manage_ec2_instances/tasks/instances/instances_network.yml` because the ami requires a c5.large to deploy now and it is trying to use a c4.xlarge. It works if you change line 40 in `/workshops/tree/devel/roles/manage_ec2_instances/defaults/main/main.yml` to be c5.large

### Issue Type

Bug

### Extra vars file

---
# region where the nodes will live
ec2_region: us-east-1

# name prefix for all the VMs
ec2_name_prefix: network-testdemo311a

# creates student_total of workbenches for the workshop
student_total: 1

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: 'network'
#demo: all

# Select between arista, cisco, juniper, and multivendor
network_type: juniper

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "token"

# Required for podman authentication to registry.redhat.io
redhat_username: username
redhat_password: 'password'

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: 'Password!'

# creates AWS S3 website for ec2_name_prefix.workshop_dns_zone
#create_login_page: true

# when towerinstall is on, this will license it with provided license
#autolicense: true

# Install Code Server
#code_server: true
#xrdp: false

# Enable AWS IAM integration with control node and workshop nodes
tower_node_aws_api_access: true

# IBM Community Grid - defaults to true if you don't tell the provisioner
#ibm_community_grid: false

# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: dnszone.opentlc.com

# automatically installs Tower to control node
controllerinstall: true

# forces ansible.workshops collection to install latest edits every time
developer_mode: true

# SHA value of targeted AAP bundle setup files.
provided_sha_value: ea2843fae672274cb1b32447c9a54c627aa5bdf5577d9a6c7f957efe68be8c01

# Automation controller install setup command. Default: "./setup.sh -e gpgcheck=0" if undefined or empty
controller_install_command: './setup.sh -e gpgcheck=0'

# default vars for ec2 AMIs (ec2_info) are located in provisioner/roles/manage_ec2_instances/defaults/main/main.yml
# select ec2_info AMI vars can be overwritten via ec2_xtra vars, e.g.:
ec2_xtra:
  satellite:
    owners: 905352580517
    username: ec2-user
    os_type: linux
    size: r5a.xlarge
    disk_volume_type: gp3
    disk_space: 500
    disk_iops: 4000
    disk_throughput: 375
    architecture: x86_64
    filter: "Satellite 6.10*"
  centos78:
    owners: 905352580517
    size: t2.medium
    os_type: linux
    disk_volume_type: gp3
    disk_space: 10
    disk_iops: 3000
    disk_throughput: 125
    architecture: x86_64
    filter: 'CentOS*7.8*x86_64'
    username: centos
    python_interpreter: '/usr/bin/python'

# Registry name to download execution environments
ee_registry_name: registry.redhat.io

# List of execution environments to download during controller installation:
ee_images:
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-29-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-supported-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-minimal-rhel8:latest"

# "Default execution environment" for controller
ee_default_image: "{{ ee_registry_name }}/ansible-automation-platform-21/ee-supported-rhel8:latest"

pre_build: false

# workshop or playground
#provision_mode: workshop

# select rhel7 or rhel8 client nodes
#rhel: rhel7
# choice of centos7 nodes
# refer to https://wiki.centos.org/Cloud/AWS for available minor releases
# select centos7 client node version
#centos7: centos78

### Ansible Playbook Output

TASK [../roles/manage_ec2_instances : Create EC2 instances for rtr1 node (workshop_type network)] *****************************************************************************************************************
task path: /home/cmcaskill/workshops/roles/manage_ec2_instances/tasks/instances/instances_network.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cmcaskill
<127.0.0.1> EXEC /bin/sh -c 'echo ~cmcaskill && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/cmcaskill/.ansible/tmp `"&& mkdir "` echo /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918 `" && echo ansible-tmp-1664918988.7458315-238685-156860650243918="` echo /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918 `" ) && sleep 0'
Using module file /home/cmcaskill/.ansible/collections/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py
<127.0.0.1> PUT /home/cmcaskill/.ansible/tmp/ansible-local-2377841eenmrty/tmpd5vynu74 TO /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918/AnsiballZ_ec2_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918/ /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/cmcaskill/.ansible/tmp/ansible-tmp-1664918988.7458315-238685-156860650243918/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_amazon.aws.ec2_instance_payload__soz8wzz/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py", line 1823, in ensure_present
  File "/tmp/ansible_amazon.aws.ec2_instance_payload__soz8wzz/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py", line 1872, in run_instances
  File "/tmp/ansible_amazon.aws.ec2_instance_payload__soz8wzz/ansible_amazon.aws.ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/core.py", line 338, in deciding_wrapper
    return unwrapped(*args, **kwargs)
  File "/home/cmcaskill/.local/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/cmcaskill/.local/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnsupportedOperation) when calling the RunInstances operation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.24.74",
    "botocore_version": "1.27.74",
    "changed": false,
    "error": {
        "code": "UnsupportedOperation",
        "message": "The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems."
    },
    "invocation": {
        "module_args": {
            "availability_zone": null,
            "aws_access_key": null,
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": null,
            "count": null,
            "cpu_credit_specification": null,
            "cpu_options": null,
            "debug_botocore_endpoint_logs": false,
            "detailed_monitoring": null,
            "ebs_optimized": null,
            "ec2_url": null,
            "exact_count": 1,
            "filters": {
                "instance-state-name": "running",
                "tag:Workshop_rtr1": "network-testdemo311a-rtr1"
            },
            "image": null,
            "image_id": "ami-0e592e38d3977e348",
            "instance_ids": [],
            "instance_initiated_shutdown_behavior": null,
            "instance_role": null,
            "instance_type": "c4.xlarge",
            "key_name": "network-testdemo311a-key",
            "launch_template": null,
            "metadata_options": null,
            "name": null,
            "network": {
                "assign_public_ip": true
            },
            "placement_group": null,
            "profile": null,
            "purge_tags": false,
            "region": "us-east-1",
            "security_group": "network-testdemo311a-insecure_all",
            "security_groups": [],
            "security_token": null,
            "state": "running",
            "tags": {
                "AWS_USERNAME": "cmcaskil@redhat.com-6xc9q-admin",
                "Info": "AWS_USERNAME that provisioned this-> cmcaskil@redhat.com-6xc9q-admin",
                "Linklight": "This was provisioned through the linklight provisioner",
                "Students": 1,
                "Workshop": "network-testdemo311a",
                "Workshop_rtr1": "network-testdemo311a-rtr1",
                "Workshop_type": "network",
                "ansible-workshops": "true",
                "ansible_network_os": "junos",
                "guid": "network-testdemo311a",
                "owner": "cmcaskil@redhat.com-6xc9q-admin",
                "security_group": "core",
                "short_name": "rtr1",
                "username": "ec2-user",
                "uuid": "network-testdemo311a"
            },
            "tenancy": null,
            "termination_protection": null,
            "to_launch": 1,
            "tower_callback": null,
            "user_data": "",
            "validate_certs": true,
            "volumes": [
                {
                    "device_name": "/dev/sda1",
                    "ebs": {
                        "delete_on_termination": true,
                        "iops": 1000,
                        "volume_size": 40,
                        "volume_type": "io1"
                    }
                }
            ],
            "vpc_subnet_id": "subnet-0541bfffcdddfe7a6",
            "wait": true,
            "wait_timeout": 600
        }
    },
    "msg": "Failed to create new EC2 instance: An error occurred (UnsupportedOperation) when calling the RunInstances operation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.",
    "response_metadata": {
        "http_headers": {
            "cache-control": "no-cache, no-store",
            "connection": "close",
            "content-type": "text/xml;charset=UTF-8",
            "date": "Tue, 04 Oct 2022 21:29:49 GMT",
            "server": "AmazonEC2",
            "strict-transport-security": "max-age=31536000; includeSubDomains",
            "transfer-encoding": "chunked",
            "vary": "accept-encoding",
            "x-amzn-requestid": "34e68fdc-9228-43bd-b2d3-0c03d86744cd"
        },
        "http_status_code": 400,
        "request_id": "34e68fdc-9228-43bd-b2d3-0c03d86744cd",
        "retry_attempts": 0
    }
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=80   changed=6    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   

### Ansible Version

[cmcaskill@rhel90 provisioner]$ ansible --version
/home/cmcaskill/.local/lib/python3.9/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible [core 2.13.4]
  config file = /home/cmcaskill/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/cmcaskill/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cmcaskill/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cmcaskill/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cmcaskill/.local/bin/ansible
  python version = 3.9.10 (main, Feb  9 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.2
  libyaml = True

### Ansible Configuration

[cmcaskill@rhel90 provisioner]$ ansible-config dump --only-changed
DEFAULT_FORKS(/home/cmcaskill/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/cmcaskill/workshops/provisioner/ansible.cfg) = ['/home/cmcaskill/workshops/provisioner/hosts']
HOST_KEY_CHECKING(/home/cmcaskill/workshops/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/cmcaskill/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/cmcaskill/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/cmcaskill/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL 9

**Comment by IPvSean** [comment]
This is fixed now:
```
  juniper:
    size: c5.xlarge
    ami: "{{ juniper_ami | default(omit) }}"
    os: junos
    username: ec2-user
    filter: "junos-vsrx3-x86-64-20.4R2-S1-byol*"
    volume:
      - device_name: /dev/sda1
        ebs:
          volume_type: io1
          iops: 1000
          volume_size: 40
          delete_on_termination: true
```

sorry for the delay on closing issue
