### ISSUE TITLE
Ansible Tower reference

### ISSUE THREAD

**Issue by sebw** [ansible/workshops#1830]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

https://aap2.demoredhat.com/decks/ansible_windows.pdf

Slide 3 mentions "Ansible Tower"

**Comment by binaryclock01** [comment]
Thank you for your submission, sebw. We will update this accordingly.

**Comment by rclements-redhat** [comment]
Thank you for raising this issue, sebw. We will correct this asap.
