### ISSUE TITLE
Bug report for Ansible Workshops

### ISSUE THREAD

**Issue by rlopez133** [ansible/workshops#1849]
### Problem Summary

Workshop uses redhat_cop collection but doesn't check if already present or attempt to install if not. 

### Issue Type

Bug

### Extra vars file

---

ec2_region: us-east-1
ec2_name_prefix: ROGERWORKSHOP
student_total: 1
workshop_type: rhel
offline_token: "omitted"
redhat_username: "rlopez@redhat.com"
redhat_password: "omitted"

dns_type: aws
admin_password: "omitted"
workshop_dns_zone: demoredhat.com
controllerinstall: true
developer_mode: true
provided_sha_value: ea2843fae672274cb1b32447c9a54c627aa5bdf5577d9a6c7f957efe68be8c01
controller_install_command: './setup.sh -e gpgcheck=0'
ee_registry_name: registry.redhat.io
ee_images:
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-29-rhel8:latest"
   - "{{ ee_registry_name }}/ee-supported-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-minimal-rhel8:latest"

ee_default_image: "{{ ee_registry_name }}/ee-supported-rhel8:latest"

### Ansible Playbook Output

```
TASK [install projects] *************************************************************************************************************************************************************************************
[WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.
[WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and unexpected behavior.
ERROR! the role 'redhat_cop.controller_configuration.projects' was not found in /Users/rlopez/git_projects/workshops/provisioner/roles:/Users/rlopez/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/rlopez/git_projects/workshops/provisioner
ERROR! the role 'redhat_cop.controller_configuration.job_templates' was not found in /Users/rlopez/git_projects/workshops/provisioner/roles:/Users/rlopez/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/rlopez/git_projects/workshops/provisioner


```

### Ansible Version

2.12.4

### Ansible Configuration

DEFAULT_FORKS(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = ['/Users/rlopez/git_projects/workshops/provisioner/hosts']
HOST_KEY_CHECKING(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/rlopez/git_projects/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

MacOS 12.6

**Comment by IPvSean** [comment]
@rlopez133 do you need help on this one?

**Comment by rlopez133** [comment]
I'll have to go back at some point and fix. Not a big issue. @IPvSean

**Comment by IPvSean** [comment]
@rlopez133 this is critical, have you fixed this?!?!?!??!?!

**Comment by rlopez133** [comment]
@IPvSean closing this is as this is related to installation (which we don't own) and I can't confirm this issue even exists anymore.
