### ISSUE TITLE
Bug Report - AAP2 Automation Hub option

### ISSUE THREAD

**Issue by bbethell-1** [ansible/workshops#1852]
### Problem Summary

1) The HUB URL provided is incorrect 
URL Pattern is https://hub-student/.<GUID>.[example.opentlc.com/](http://example.opentlc.com/) not the one provided in the instructions. This is also missing from the student view
EG : https://hub-student.rh8fd4.example.opentlc.com/ui/ 
admin
3pxsf24VpeLQBr

2) Not able to see anything in collections tab. sync for rh certified content is also failing:
400 message= Bad Request 

### Issue Type

Bug

### Extra vars file

![image (19)](https://user-images.githubusercontent.com/93923166/200580962-481be899-f8ca-4f8a-929f-0229c480664e.png)
https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z3IHLWJZOU9SRT
search with "rh8fd4

### Ansible Playbook Output

TASK [redhat_cop.controller_configuration.hosts : Add Controller host] *********
changed: [rh8fd4-student1-ansible-1] => (item={'name': 'backup-server', 'description': 'this server is where we backup network configuration', 'inventory': 'Workshop Inventory', 'variables': {'note': 'in production these passwords would be encrypted in vault', 'ansible_user': 'ec2-user', 'ansible_password': '3pxsf24VpeLQBr', 'ansible_host': '54.169.199.183'}}) => {"__controller_host_item": {"description": "this server is where we backup network configuration", "inventory": "Workshop Inventory", "name": "backup-server", "variables": {"ansible_host": "54.169.199.183", "ansible_password": "3pxsf24VpeLQBr", "ansible_user": "ec2-user", "note": "in production these passwords would be encrypted in vault"}}, "ansible_loop_var": "__controller_host_item", "changed": true, "id": 7, "name": "backup-server", "warnings": ["You are using the awx version of this collection but connecting to Red Hat Ansible Automation Platform"]}

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL

**Comment by IPvSean** [comment]
This should all be fixed on our `main` now and I tested this on RHPDS `devel`.  Fixed with https://github.com/ansible/workshops/pull/1885

Please work with RHPDS team to "release" RHPDS dev to main for Ansible Automation Workshops and it should fix all issues here.
