### ISSUE TITLE
Bug report for Ansible Workshops - RHPDS rheee5 AAP2 Linux Automation Workshop 

### ISSUE THREAD

**Issue by 9strands** [ansible/workshops#1854]
### Problem Summary

Issue with Linux Workshop deploy (GUID rheee5) where 4 fatal errors occurred but did not fail the deployer, and route53 entries were never created for these hosts leading to a workshop that appeared to complete successfully but was unusable.

Service name is: RHPDS-RH-gobrien-redhat.com-PROD_AAP2_ANSIBLE_WORKSHOPS_TRAINING-rheee5_COMPLETED

### Issue Type

Bug

### Extra vars file

Deployment is RHPDS guid rheee5 - there is no vars.yaml available in the workdir tarball.

### Ansible Playbook Output

Relevant sections:These

$ grep -n fatal ./deployment_logs/archives/prod-aap2-ansible-workshops-rheee5.log
908:fatal: [rheee5-student1-node1]: FAILED! => {"changed": false, "elapsed": 408, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: Connection timed out during banner exchange"}
909:fatal: [attendance-host]: FAILED! => {"changed": false, "elapsed": 408, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: Connection timed out during banner exchange"}
910:fatal: [rheee5-student1-ansible-1]: FAILED! => {"changed": false, "elapsed": 408, "msg": "timed out waiting for ping module test: Failed to connect to the host via ssh: Connection timed out during banner exchange"}
917:fatal: [rheee5-student1-node3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange", "unreachable": true}

### Ansible Version

RHPDS version

### Ansible Configuration

RHPDS Configuration

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

RHEL

**Comment by IPvSean** [comment]
This should all be fixed on our `main` now and I tested this on RHPDS `devel`.  Fixed with https://github.com/ansible/workshops/pull/1885

Please work with RHPDS team to "release" RHPDS dev to main for Ansible Automation Workshops and it should fix all issues here.
