### ISSUE TITLE
 Enhancement for Ansible Workshops - AAP2 Ansible & Smart Management Workshop

### ISSUE THREAD

**Issue by amelie1979** [ansible/workshops#1856]
### Problem Summary

Is this possible to create the RH Satellite (RHPDS Student LAB) with a valid SSL Certificate.  This is now difficult at customer location to allow invalid SSL Cert passed. (Allow untrusted)

Workshops - AAP2 Ansible & Smart Management Workshop

### Issue Type

Feature Request

### Extra vars file

N/A

### Ansible Playbook Output

N/A

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

N/A

**Comment by IPvSean** [comment]
cc @heatmiser

**Comment by heatmiser** [comment]
The AAP2 Ansible & Smart Management workshop has been deprecated and replaced with the AAP2 Ansible & Satellite workshop, where a valid SSL Certificate is generated and deployed on the Satellite system. @abenokraitis I move that this issue be closed.
