### ISSUE TITLE
RHEL 90: Workshop Project is not pre-created

### ISSUE THREAD

**Issue by evanstoner** [ansible/workshops#1857]
### Problem Summary

In the RHEL 90 workshop, [Exercise 5 - Self-service IT via surveys](https://aap2.demoredhat.com/exercises/ansible_rhel_90/5-surveys) requires creating a job template using the Workshop Project, but that project doesn't exist. The RHEL 90 workshop does not include directions for creating this project. In the full RHEL workshop it is created in [Exercise 2.3 - Projects & job templates](https://aap2.demoredhat.com/exercises/ansible_rhel/2.3-projects)

The RHEL 90 workshop should pre-create the Workshop Project.

### Issue Type

Bug

### Extra vars file

n/a provisioned via RHPDS

### Ansible Playbook Output

n/a provisioned via RHPDS

### Ansible Version

n/a provisioned via RHPDS

### Ansible Configuration

n/a provisioned via RHPDS

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

n/a provisioned via RHPDS

**Comment by IPvSean** [comment]
Hey @anshulbehl can you investigate this one?

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/pull/1886
