### ISSUE TITLE
Bug report for Ansible Automation Platform 2 Networking Automation Workshop

### ISSUE THREAD

**Issue by 9strands** [ansible/workshops#1864]
### Problem Summary

RHPDS User Report (User type: Solution Architect)

Additional information:: Ansible Network Automation Workshop (https://aap2.demo.redhat.com/exercises/ansible_network/) Exercise 6 references a job template that is failing because the underlying playbook doesn't see the "ansible.controller" collection as being installed on the controller (and the repo code isn't satisfying the dependency a different way, e.g., in https://github.com/network-automation/toolkit/blob/master/collections/requirements.yml):

Identity added: /runner/artifacts/3/ssh_key_data (/runner/artifacts/3/ssh_key_data)
ERROR! couldn't resolve module/action 'ansible.controller.job_template'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/playbooks/network_backup.yml': line 62, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: create restore job template
      ^ here

https://aap2.demoredhat.com/exercises/ansible_network/6-controller-job-template/#step-1-create-a-job-template

ansible.controller is found not in the default execution environment:

https://student2.rha8ce.example.opentlc.com/#/jobs/playbook/3/output

However, the ansible.controller collection IS in the "network workshop execution environment":

https://student2.rha8ce.example.opentlc.com/#/jobs/playbook/10/output

So it seems like a quick fix would be to update Exercise 6 instructions to use the "network workshop execution environment" instead of the Default execution environment.

### Issue Type

Bug

### Extra vars file

RHPDS GUID rha8ce

### Ansible Playbook Output

Build is clean, issue inside of the lab itself with potentially bad instructions

### Ansible Version

RHPDS standard

### Ansible Configuration

RHPDS

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHPDS - RHEL

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/pull/1869
