### ISSUE TITLE
TASK aap_repo.yml: create repo pointing to wrong baseurl

### ISSUE THREAD

**Issue by criscofats** [ansible/workshops#1867]
### Problem Summary

`roles/aap_repo/tasks/create_repo.yml` line 6 baseurl is pointing to the wrong path causing the install of base packages to fail with

> Cannot download repodata/repomd.xml: All mirrors were tried

Logging into the Ansible host the baseurl seems to be
`{{ aap_dir }}/bundle/el8/repos`

Made this modification on a fork and the playbook proceeded.

https://github.com/ansible/workshops/blob/505e3d0d59974b308068d29a821fd9974b97b853/roles/aap_repo/tasks/create_repo.yml#L6

### Issue Type

Bug

### Extra vars file

---
# region where the nodes will live
ec2_region: us-east-1

# name prefix for all the VMs (No uppercase, no underscores)
ec2_name_prefix: test-deploy

# creates student_total of workbenches for the workshop
student_total: 1

# Set the right workshop type, like network, rhel or f5 (see above)
workshop_type: 'smart_mgmt'
#demo: all

# Generate offline token to authenticate the calls to Red Hat's APIs
# Can be accessed at https://access.redhat.com/management/api
offline_token: "x"

# Required for podman authentication to registry.redhat.io
redhat_username: x
redhat_password: 'x'

#####OPTIONAL VARIABLES

# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws

# password for Ansible control node
admin_password: 'x'

# creates AWS S3 website for ec2_name_prefix.workshop_dns_zone
create_login_page: true

# when towerinstall is on, this will license it with provided license
autolicense: true

# Install Code Server
code_server: true
xrdp: false

# Enable AWS IAM integration with control node and workshop nodes
tower_node_aws_api_access: true

# IBM Community Grid - defaults to true if you don't tell the provisioner
ibm_community_grid: false

# Sets the Route53 DNS zone to use for Amazon Web Services
workshop_dns_zone: x

# automatically installs Tower to control node
controllerinstall: true

# forces ansible.workshops collection to install latest edits every time
developer_mode: true

# SHA value of targeted AAP bundle setup files.
provided_sha_value: ea2843fae672274cb1b32447c9a54c627aa5bdf5577d9a6c7f957efe68be8c01

# Automation controller install setup command. Default: "./setup.sh -e gpgcheck=0" if undefined or empty
controller_install_command: './setup.sh -e gpgcheck=0'

# default vars for ec2 AMIs (ec2_info) are located in provisioner/roles/manage_ec2_instances/defaults/main/main.yml
# select ec2_info AMI vars can be overwritten via ec2_xtra vars, e.g.:
ec2_xtra:
  satellite:
    owners: x
    username: ec2-user
    os_type: linux
    size: r5a.xlarge
    disk_volume_type: gp3
    disk_space: 500
    disk_iops: 4000
    disk_throughput: 375
    architecture: x86_64
    filter: "Satellite 6.10*"
  centos78:
    owners: x
    size: t2.medium
    os_type: linux
    disk_volume_type: gp3
    disk_space: 10
    disk_iops: 3000
    disk_throughput: 125
    architecture: x86_64
    filter: 'CentOS*7.8*x86_64'
    username: centos
    python_interpreter: '/usr/bin/python'

# Registry name to download execution environments
ee_registry_name: registry.redhat.io

# List of execution environments to download during controller installation:
ee_images:
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-29-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-supported-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-21/ee-minimal-rhel8:latest"

# "Default execution environment" for controller
ee_default_image: "{{ ee_registry_name }}/ansible-automation-platform-21/ee-supported-rhel8:latest"

pre_build: false

# workshop or playground
provision_mode: workshop

# select rhel7 or rhel8 client nodes
rhel: rhel7
# choice of centos7 nodes
# refer to https://wiki.centos.org/Cloud/AWS for available minor releases
# select centos7 client node version
centos7: centos78

automation_hub: false
#automationhub_admin_password: 'x'

### Ansible Playbook Output

{
  "results": [],
  "rc": 1,
  "msg": "Failed to download metadata for repo 'aap_installer': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried",
  "invocation": {
    "module_args": {
      "name": [
        "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
      ],
      "state": "present",
      "disable_gpg_check": true,
      "allow_downgrade": false,
      "autoremove": false,
      "bugfix": false,
      "cacheonly": false,
      "disable_plugin": [],
      "disablerepo": [],
      "download_only": false,
      "enable_plugin": [],
      "enablerepo": [],
      "exclude": [],
      "installroot": "/",
      "install_repoquery": true,
      "install_weak_deps": true,
      "security": false,
      "skip_broken": false,
      "update_cache": false,
      "update_only": false,
      "validate_certs": true,
      "sslverify": true,
      "lock_timeout": 30,
      "allowerasing": false,
      "nobest": false,
      "conf_file": null,
      "disable_excludes": null,
      "download_dir": null,
      "list": null,
      "releasever": null
    }
  },
  "_ansible_no_log": null,
  "changed": false
}

### Ansible Version

Ansible Automation Platform Controller 4.2.1

### Ansible Configuration

How can I get this from AAP?

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

RHEL 9

**Comment by IPvSean** [comment]
@criscofats we actually had already hit this and fixed it :( I guess your fork was not up to date on `devel` https://github.com/ansible/workshops/blob/devel/roles/aap_repo/tasks/create_repo.yml

sorry that you ran into this still, make sure before opening bugs to rebase on devel

```
git pull --rebase upstream devel
```
