### ISSUE TITLE
6-controller-job-template (Error with Instruction vs Screenshot)

### ISSUE THREAD

**Issue by amelie1979** [ansible/workshops#1898]
### Area

Ansible Network Automation Workshop

### Proposed Changes

In the tab section where to create the job the parameter : **network workshop execution environment** should be change to **Default execution environment** to reflect the screenshot.

https://aap2.demoredhat.com/exercises/ansible_network/6-controller-job-template/

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/pull/1911
