### ISSUE TITLE
Bug report for Ansible Networking  Automation Workshops

### ISSUE THREAD

**Issue by amelie1979** [ansible/workshops#1902]
### Problem Summary

Ansible Automation Platform 2 Networking Automation Workshop
The labs are provisioned, but some lab failed to sync the git repo project and some ansible job template are missing in the same lab.

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

N/A

### Ansible Version

N/A

### Ansible Configuration

N/A

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

N/A

**Comment by rhjcd** [comment]
specific log error:
{
  "redirected": false,
  "url": "https://ansible.demoredhat.com/api/v2/job_templates/17/launch/",
  "status": 400,
  "server": "nginx",
  "date": "Mon, 23 Jan 2023 22:21:47 GMT",
  "content_type": "application/json",
  "content_length": "89",
  "connection": "close",
  "vary": "Accept, Accept-Language, Origin, Cookie",
  "allow": "GET, POST, HEAD, OPTIONS",
  "x_api_product_version": "4.3.0",
  "x_api_product_name": "Red Hat Ansible Automation Platform",
  "x_api_node": "172.16.129.140",
  "x_api_time": "0.281s",
  "content_language": "en",
  "x_api_total_time": "0.351s",
  "x_api_request_id": "92eac70d91d84fa29c1dcd0d62ff4901",
  "access_control_expose_headers": "X-API-Request-Id",
  "elapsed": 0,
  "changed": false,
  "json": {
    "variables_needed_to_start": [
      "Value 20 for 'student_total' expected to be an integer."
    ]
  },
  "msg": "Status code was 400 and not [200, 201]: HTTP Error 400: Bad Request",
  "invocation": {
    "module_args": {
      "url": "https://ansible.demoredhat.com/api/v2/job_templates/17/launch/",
      "validate_certs": false,
      "method": "POST",
      "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "status_code": [
        200,
        201
      ],
      "force_basic_auth": true,
      "body": {
        "extra_vars": {
          "ec2_name_prefix": "bxs22",
          "aws_user": "opentlc-mgr",
          "ec2_region": "us-east-2",
          "student_total": "20",
          "workshop_type": "network"
        }
      },
      "body_format": "json",
      "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "force": false,
      "http_agent": "ansible-httpget",
      "use_proxy": true,
      "use_gssapi": false,
      "return_content": false,
      "follow_redirects": "safe",
      "timeout": 30,
      "headers": {
        "Content-Type": "application/json"
      },
      "remote_src": false,
      "unredirected_headers": [],
      "unsafe_writes": false,
      "client_cert": null,
      "client_key": null,
      "dest": null,
      "src": null,
      "creates": null,
      "removes": null,
      "unix_socket": null,
      "ca_path": null,
      "mode": null,
      "owner": null,
      "group": null,
      "seuser": null,
      "serole": null,
      "selevel": null,
      "setype": null,
      "attributes": null
    }
  },
  "_ansible_no_log": null
}

**Comment by IPvSean** [comment]
@rhjcd is this still an issue or did it get resolved?

**Comment by IPvSean** [comment]
closing due to no response
