### ISSUE TITLE
RHEL90 Workshop directory should be rhel_90-workshop

### ISSUE THREAD

**Issue by hgonzalerh** [ansible/workshops#1921]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

Docs for the 90 minute RHEL workshop whould refer to the directoy in the environment as rhel_90-workshop instead of rhel-workshop  https://aap2.demoredhat.com/exercises/ansible_rhel_90/1-setup/#step-1---access-the-environment

**Comment by IPvSean** [comment]
this is fixed
