### ISSUE TITLE
Ansible-navigator configuration linnk broken - Ex1,St4

### ISSUE THREAD

**Issue by nleiva** [ansible/workshops#1950]
### Area

Ansible Network Automation Workshop

### Proposed Changes

Ansible Network Automation Exercises > Exercise 1 - Exploring the lab environment > Step 4 - Examining the ansible-navigator configuration
...
For a full listing of every configurable knob checkout the [documentation](https://ansible-navigator.readthedocs.io/en/latest/settings/)

I believe it should point to https://ansible-navigator.readthedocs.io/settings/ instead of https://ansible-navigator.readthedocs.io/en/latest/settings/

**Comment by IPvSean** [comment]
link looks broken too... let me talk to the navigator team

**Comment by IPvSean** [comment]
fixed now, let me know if its broken again and you can re-open!
