### ISSUE TITLE
Linux Workshop Exercise 5 - misspelled 'ansible.builtin.um'

### ISSUE THREAD

**Issue by corumj** [ansible/workshops#1994]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

Correct the spelling from "ansible.builtin.um" to ansible.builtin.yum, or better yet, use the ansible.builtin.package module to future proof.

**Comment by IPvSean** [comment]
This has been fixed, thank you, you can see the newly rendered page here: https://ipvsean.github.io/workshops/exercises/ansible_rhel/1.5-handlers/
