### ISSUE TITLE
Exerciese 1.4, step 7, mispelled ansible

### ISSUE THREAD

**Issue by corumj** [ansible/workshops#1995]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

change 'anisble.builtin.debug:'
to 'ansible.builtin.debug:'

**Comment by IPvSean** [comment]
This has been fixed, thank you for reporting 

you can see the newly rendered page here: https://aap2.demoredhat.com/exercises/ansible_rhel/1.4-variables/
