### ISSUE TITLE
PAH user name is admin, not studentX

### ISSUE THREAD

**Issue by cbolz** [ansible/workshops#1997]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

lab overview says the username for private automation hub is "studentX", however it seems to be admin, there is no "studentX" user on PAH.

This is at least in the Windows workshop, but maybe others as well.

**Comment by cloin** [comment]
Windows workshop doesn't use PAH does it? What lab guide is this?

**Comment by cbolz** [comment]
you're right and I don't remember where I saw this... closing it.
