### ISSUE TITLE
Exercise - Linux System Roles

### ISSUE THREAD

**Issue by belznotbells** [ansible/workshops#2011]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

https://aap2.demoredhat.com/exercises/ansible_rhel_90/6-system-roles/

The following exercise instructs the students to navigate to a URL in github that does not exist. 

Step 1. says to navigate to https://github.com/ansible/product-demos

Step 2. says to navigate to playbooks/security/hardening.yml and that path does not exist. I was only able to find the playbook at https://github.com/ansible/product-demos/blob/main/linux/hardening.yml

Could you validate that the instructions are correct and if so possibly change the wording as it's confusing to the students and instructor. Thank you!

**Comment by IPvSean** [comment]
@belznotbells thanks for opening this issue, will be fixed in my next release
