### ISSUE TITLE
RHDP: Ansible Windows Workshop - provision fail / TASK infra-ec2-wait_for_windows_hosts

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#2012]
### Problem Summary

example log: https://tower.dark-tower-prod.infra.open.redhat.com/#/jobs/playbook/1514768?job_search=page_size:20;order_by:-finished;not__launch_type:sync

AAP2 Windows constistently fails to deploy with this error:

TASK [infra-ec2-wait_for_windows_hosts : wait for windows host to be available (retry)] ***
fatal: [win1.example.com]: FAILED! => {"changed": false, "elapsed": 1020, "msg": "timed out waiting for ping module test success: ssl: HTTPSConnectionPool(host='ec2-3-16-223-175.us-east-2.compute.amazonaws.com', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ef6958898>, 'Connection to ec2-3-16-223-175.us-east-2.compute.amazonaws.com timed out. (connect timeout=30)'))"}

### Issue Type

Bug

### Extra vars file

x

### Ansible Playbook Output

{
    "msg": "timed out waiting for ping module test success: ssl: HTTPSConnectionPool(host='ec2-3-16-223-175.us-east-2.compute.amazonaws.com', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ef6958898>, 'Connection to ec2-3-16-223-175.us-east-2.compute.amazonaws.com timed out. (connect timeout=30)'))",
    "elapsed": 1020,
    "_ansible_no_log": false,
    "changed": false
}

TASK [infra-ec2-wait_for_windows_hosts : wait for windows host to be available (retry)] ***
fatal: [win1.example.com]: FAILED! => {"changed": false, "elapsed": 1020, "msg": "timed out waiting for ping module test success: ssl: HTTPSConnectionPool(host='ec2-3-16-223-175.us-east-2.compute.amazonaws.com', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ef6958898>, 'Connection to ec2-3-16-223-175.us-east-2.compute.amazonaws.com timed out. (connect timeout=30)'))"}

### Ansible Version

ok

### Ansible Configuration

ok

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

ok

**Comment by IPvSean** [comment]
same problem as last time, solved with https://github.com/ansible/workshops/pull/2014
