### ISSUE TITLE
Broken Link for ansible-navigator config list documentation

### ISSUE THREAD

**Issue by nyanavila** [ansible/workshops#2020]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

https://aap2.demoredhat.com/exercises/ansible_rhel/1.1-setup/

For a full listing of every configurable knob checkout the [documentation](https://ansible-navigator.readthedocs.io/en/latest/settings/)

The 'documentation' link is broken.

**Comment by IPvSean** [comment]
thank you @nyanavila for opening this issue, will be fixed in the next release!
