### ISSUE TITLE
RHDP Bug report for Ansible RIPU Workshop

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#2026]
### Problem Summary

fails to deploy - error:

LOG: https://controller.aap5ao6oghnkg6u4.ansiblecloud.redhat.com/#/jobs/playbook/34971/output

TASK [Check API until OS / Patch OS to latest job is successful]

fatal: [lh7kj-student1-ansible-1]: FAILED! => {"access_control_expose_headers": "X-API-Request-Id", "allow": "GET, DELETE, HEAD, OPTIONS", "attempts": 45, "cache_control": "no-cache, no-store, must-revalidate", "changed": false, "connection": "close", "content": "{\"id\":10,\"type\":\"job\",\"url\":\"/api/v2/jobs/10/\",\"related\":{\"created_by\":\"/api/v2/users/1/\",\"labels\":\"/api/v2/jobs/10/labels/\",\"inventory\":\"/api/v2/inventories/2/\",\"project\":\"/api/v2/projects/9/\",\"organization\":\"/api/v2/organizations/1/\",\"credentials\":\"/api/v2/jobs/10/credentials/\",\"unified_job_template\":\"/api/v2/job_templates/15/\",\"stdout\":\"/api/v2/jobs/10/stdout/\",\"execution_environment\":\"/api/v2/execution_environments/5/\",\"job_events\":\"/api/v2/jobs/10/job_events/\",\"job_host_summaries\":\"/api/v2/jobs/10/job_host_summaries/\",\"activity_stream\":\"/api/v2/jobs/10/activity_stream/\",\"notifications\":\"/api/v2/jobs/10/notifications/\",\"create_schedule\":\"/api/v2/jobs/10/create_schedule/\",…

### Issue Type

Bug

### Extra vars file

NA

### Ansible Playbook Output

TASK [Check API until OS / Patch OS to latest job is successful]

fatal: [lh7kj-student1-ansible-1]: FAILED! => {"access_control_expose_headers": "X-API-Request-Id", "allow": "GET, DELETE, HEAD, OPTIONS", "attempts": 45, "cache_control": "no-cache, no-store, must-revalidate", "changed": false, "connection": "close", "content": "{\"id\":10,\"type\":\"job\",\"url\":\"/api/v2/jobs/10/\",\"related\":{\"created_by\":\"/api/v2/users/1/\",\"labels\":\"/api/v2/jobs/10/labels/\",\"inventory\":\"/api/v2/inventories/2/\",\"project\":\"/api/v2/projects/9/\",\"organization\":\"/api/v2/organizations/1/\",\"credentials\":\"/api/v2/jobs/10/credentials/\",\"unified_job_template\":\"/api/v2/job_templates/15/\",\"stdout\":\"/api/v2/jobs/10/stdout/\",\"execution_environment\":\"/api/v2/execution_environments/5/\",\"job_events\":\"/api/v2/jobs/10/job_events/\",\"job_host_summaries\":\"/api/v2/jobs/10/job_host_summaries/\",\"activity_stream\":\"/api/v2/jobs/10/activity_stream/\",\"notifications\":\"/api/v2/jobs/10/notifications/\",\"create_schedule\":\"/api/v2/jobs/10/create_schedule/\",…

### Ansible Version

NA

### Ansible Configuration

NA

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

NA

**Comment by heatmiser** [comment]
I do not believe this was a systemic issue, more likely due to occasional transient nature of cloud deployments. @rhjcd Please advise if this is still and issue in RIPU prod workshop.

**Comment by rhjcd** [comment]
@heatmiser I have tested again and this is successful now. You are correct - transient
