### ISSUE TITLE
Bug report for Ansible Workshops - SAP End to End Automation - OSP mtkrx, has failed to provision. Please see attached Ansible log.

### ISSUE THREAD

**Issue by rnunezrgn** [ansible/workshops#2044]
### Problem Summary

Hi everyone,
This is the error I'm receiving when trying spin this SAP+AAP lab:
Your RHDP service, SAP End to End Automation - OSP mtkrx, has failed to provision. Please see attached Ansible log."

Please, see additional information in next sections.
Thanks,
Roberto

### Issue Type

Bug

### Extra vars file

Unknown

### Ansible Playbook Output

TASK [Install roles from requirements.yml] *************************************
FAILED - RETRYING: Install roles from requirements.yml (10 retries left).
FAILED - RETRYING: Install roles from requirements.yml (9 retries left).
FAILED - RETRYING: Install roles from requirements.yml (8 retries left).
FAILED - RETRYING: Install roles from requirements.yml (7 retries left).
FAILED - RETRYING: Install roles from requirements.yml (6 retries left).
FAILED - RETRYING: Install roles from requirements.yml (5 retries left).
FAILED - RETRYING: Install roles from requirements.yml (4 retries left).
FAILED - RETRYING: Install roles from requirements.yml (3 retries left).
FAILED - RETRYING: Install roles from requirements.yml (2 retries left).
FAILED - RETRYING: Install roles from requirements.yml (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": ["ansible-galaxy", "install", "-r", "configs/sap-hana/requirements.yml", "-p", "/tmp/awx_1597420_ab_z7lsl/project/ansible/configs/sap-hana/roles"], "delta": "0:00:01.456114", "end": "2023-10-02 20:13:14.809577", "msg": "non-zero return code", "rc": 1, "start": "2023-10-02 20:13:13.353463", "stderr": "\\u001b[0;31m [ERROR]: failed to download the file: HTTP Error 404: Not Found\\u001b[0m\\n\\u001b[1;35m[WARNING]: - redhat_sap.sap_rhsm was NOT installed successfully.\\u001b[0m\\n\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m", "stderr_lines": ["\\u001b[0;31m [ERROR]: failed to download the file: HTTP Error 404: Not Found\\u001b[0m", "\\u001b[1;35m[WARNING]: - redhat_sap.sap_rhsm was NOT installed successfully.\\u001b[0m", "\\u001b[0;31mERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.\\u001b[0m"], "stdout": "- infra-ansible (v2.0.8) is already installed, skipping.\\n- downloading role 'sap_rhsm', owned by redhat_sap\\n- downloading role from https://github.com/redhat_sap/sap-rhsm/archive/v1.1.2.tar.gz", "stdout_lines": ["- infra-ansible (v2.0.8) is already installed, skipping.", "- downloading role 'sap_rhsm', owned by redhat_sap", "- downloading role from https://github.com/redhat_sap/sap-rhsm/archive/v1.1.2.tar.gz"]}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

### Ansible Version

unknown

### Ansible Configuration

unknow

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

unknown

**Comment by bbethell-1** [comment]
Not relevant to AAP2 - can be closed @sean-m-sullivan

**Comment by IPvSean** [comment]
closing at per suggestion from @bbethell-1
