### ISSUE TITLE
Bug report for Ansible Workshops

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#2046]
### Problem Summary

need to add in `update-crypto-policies --set LEGACY` to control nodes for `network` workshop.  There is an issue with newer RHEL9.X with Cisco CSR images, where Cisco is running an older version of SSH that we consider legacy 

### Issue Type

Bug

### Extra vars file

n/a

### Ansible Playbook Output

n/a

### Ansible Version

n/a

### Ansible Configuration

n/a

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

n/a

**Comment by abenokraitis** [comment]
How's this going @IPvSean, does this need to be added as part of the move to AgnosticD

**Comment by IPvSean** [comment]
this is no longer an issue with RHEL9 because I upgrade the network switch to a newer model which no longer needs this legacy crypto policy, thanks for reminding me about this issue!
