### ISSUE TITLE
Automate Satellite Exercises

### ISSUE THREAD

**Issue by linebackj** [ansible/workshops#2051]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

First off the Automation Workshop called:  Ansible Automation Platform 2 & Satellite Workshop is not listed in the drop down or on the Gibhub.

Second on Chapter O exercise there is only CENTOS - Publish Content View NOT RHEL.  See below

Run the SATELLITE / RHEL - Publish Content View job template by clicking the launch to launch. When prompted by the survey for the content view to publish, from the drop down menu, select RHEL7

![AAP_RHEL_EXCERICSE](https://github.com/ansible/workshops/assets/56732984/1ec9d997-eefa-40dd-95a7-a57f92dc67c7)

**Comment by heatmiser** [comment]
Dan and I had a meeting to discuss these two issues.

> First off the Automation Workshop called: Ansible Automation Platform 2 & Satellite Workshop is not listed in the drop down or on the Gibhub.

I've made a note and will work to make this adjustment.

> Second on Chapter O exercise there is only CENTOS - Publish Content View NOT RHEL. See below
> 
> Run the SATELLITE / RHEL - Publish Content View job template by clicking the launch to launch. When prompted by the survey for the content view to publish, from the drop down menu, select RHEL7

This is not an issue, verified via screen share of a deployed workbench.
