### ISSUE TITLE
Bug report for Ansible Workshops

### ISSUE THREAD

**Issue by JayDi11a** [ansible/workshops#2063]
### Problem Summary

I am simply trying to run the provisioner.yml after doing the latest git pull which usually works. I am getting the error:

```
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: No last item, sequence was empty.. No last item, sequence was empty.\n\nThe error appears to be in '/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/provision.yml': line 46, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: save ami for ansible control node\n      ^ here\n"
}
```

When you look at the code itself where it is complaining it appears to be here:
```

- name: save ami for ansible control node
      set_fact:
        ansible_control_node_ami: >
          {{ amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}  
```

### Issue Type

Bug

### Extra vars file

---
# region where the nodes will live
ec2_region: us-east-2
# name prefix for all the VMs
# ec2_name_prefix: SECURITYWORKSHOP
# ec2_name_prefix: SECURITYWORKSHOPTWO
ec2_name_prefix: SECURITYWORKSHOPTHREE
# amount of work benches to provision
student_total: 1
# workshop is put into rhel mode
workshop_type: security
# Required for AAP download https://access.redhat.com/articles/3626371
# Required for podman authentication to registry.redhat.io
redhat_username: "username"
redhat_password: "password"
# DNS domain
workshop_dns_zone: trotman.com
#workshop_dns_zone: cloudpak4security.com
# workshop_dns_zone: gerald-trotman.com
## Optional Variables
# password used for student account on control node
admin_password: "password"
# turn DNS on for control nodes, and set to type in valid_dns_type
dns_type: aws
# this will install Automation controller on all control nodes
controllerinstall: true 
create_cluster: false
controllerinstall: true
create_cluster: false
ibm_community_grid: false
use_manifest: true
attendance: false
windows_password: "password"
ansible_async_dir: '/tmp/.ansible_async'

### Ansible Playbook Output

TASK [../roles/manage_ec2_instances : save ami for ansible control node] ****************************************************************************************************************************************************************************
task path: /Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/provision.yml:46
Friday 01 December 2023  20:18:31 -0800 (0:00:01.069)       0:00:23.075 ******* 
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: No last item, sequence was empty.. No last item, sequence was empty.\n\nThe error appears to be in '/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/provision.yml': line 46, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: save ami for ansible control node\n      ^ here\n"
}
PLAY RECAP ******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=45   changed=1    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0   

Friday 01 December 2023  20:18:31 -0800 (0:00:00.033)       0:00:23.109 ******* 
=============================================================================== 
../roles/manage_ec2_instances : Create EC2 security group for VPC named SECURITYWORKSHOPTHREE-vpc -------------------------------------------------------------------------------------------------------------------------------------------- 2.18s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:32 -------------------------------------------------------------------------------------------------------------------------------------------------
../roles/aws_check_setup : does route53 zone exist ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.77s
/Users/gerald.trotmanibm.com/workshops/roles/aws_check_setup/tasks/main.yml:21 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : vpc public subnet route table is present for vpc-088b93e019b2fa094 ------------------------------------------------------------------------------------------------------------------------------------------- 1.76s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:110 ------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Create AWS VPC SECURITYWORKSHOPTHREE-vpc --------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.72s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:3 --------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : s3 bucket for persistent storage of ec2 key exists ----------------------------------------------------------------------------------------------------------------------------------------------------------- 1.63s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/aws.yml:2 --------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Save Private key from S3 Bucket when not generating it ------------------------------------------------------------------------------------------------------------------------------------------------------- 1.41s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/aws.yml:26 -------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Create subnet for SECURITYWORKSHOPTHREE-vpc ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 1.35s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:54 -------------------------------------------------------------------------------------------------------------------------------------------------
../roles/aws_check_setup : grab information about AWS user ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.26s
/Users/gerald.trotmanibm.com/workshops/roles/aws_check_setup/tasks/main.yml:59 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/workshop_check_setup : Install required roles --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.23s
/Users/gerald.trotmanibm.com/workshops/roles/workshop_check_setup/tasks/security.yml:8 -------------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : vpc internet gateway is present for vpc-088b93e019b2fa094 ---------------------------------------------------------------------------------------------------------------------------------------------------- 1.18s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:94 -------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Create subnet2 for SECURITYWORKSHOPTHREE-vpc (SECURITY MODE) ------------------------------------------------------------------------------------------------------------------------------------------------- 1.12s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:74 -------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : find ami for ansible control node with pre_build image ------------------------------------------------------------------------------------------------------------------------------------------------------- 1.07s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/provision.yml:37 -----------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Create ssh key pair for workshop SECURITYWORKSHOPTHREE ------------------------------------------------------------------------------------------------------------------------------------------------------- 1.00s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:138 ------------------------------------------------------------------------------------------------------------------------------------------------
../roles/aws_check_setup : Find available AZ for region us-east-2 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.92s
/Users/gerald.trotmanibm.com/workshops/roles/aws_check_setup/tasks/main.yml:36 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.63s
/Users/gerald.trotmanibm.com/workshops/provisioner/provision_lab.yml:2 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/aws_check_setup : grab boto version ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.45s
/Users/gerald.trotmanibm.com/workshops/roles/aws_check_setup/tasks/main.yml:2 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : create file for all AWS security group rules ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.42s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:22 -------------------------------------------------------------------------------------------------------------------------------------------------
../roles/workshop_check_setup : ensure workshop folder SECURITYWORKSHOPTHREE exists ---------------------------------------------------------------------------------------------------------------------------------------------------------- 0.33s
/Users/gerald.trotmanibm.com/workshops/roles/workshop_check_setup/tasks/controller.yml:2 -----------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/workshop_check_setup : Check that the manifest.zip exists --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.32s
/Users/gerald.trotmanibm.com/workshops/roles/workshop_check_setup/tasks/controller.yml:31 ----------------------------------------------------------------------------------------------------------------------------------------------------------
../roles/manage_ec2_instances : Ensure key file has proper permissions ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.25s
/Users/gerald.trotmanibm.com/workshops/roles/manage_ec2_instances/tasks/resources/resources.yml:154 -

### Ansible Version

ansible [core 2.15.3]
  config file = /Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg
  configured module search path = ['/Users/gerald.trotmanibm.com/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gerald.trotmanibm.com/.pyenv/versions/3.9.17/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/gerald.trotmanibm.com/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/gerald.trotmanibm.com/.pyenv/versions/3.9.17/bin/ansible
  python version = 3.9.17 (main, Aug 27 2023, 13:28:07) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/gerald.trotmanibm.com/.pyenv/versions/3.9.17/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

### Ansible Configuration

CALLBACKS_ENABLED(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = ['ansible.posix.profile_tasks']
CONFIG_FILE() = /Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg
DEFAULT_FORKS(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = ['/Users/gerald.trotmanibm.com/workshops/provisioner/hosts']
HOST_KEY_CHECKING(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/gerald.trotmanibm.com/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

MacOS 14.1.1

**Comment by IPvSean** [comment]
I can pre-share the AMI since you are an IBM employee, but to make this work if you are not a Red Hat employee, partner or IBM employee would be simply to set this var in your extra_vars.yml 

```
pre_build: false
```

My email is scavanau@ if you want the pre_build AMI
