### ISSUE TITLE
Bug report for Ansible Workshops - Configuration as Code for Ansible Automation Platform 2

### ISSUE THREAD

**Issue by daleroux** [ansible/workshops#2077]
### Problem Summary

While using the Configuration as Code for Ansible Automation Platform 2 workshop, at "Step 8"  the task failed as the version of ansible-builder is 1.1.0 and incompatible with a v3 definition schema (as build in the lab).    Taking the same V3 definition schema on a system with ansible-builder v 3.0.0  works and building the EE succeeds.

### Issue Type

Bug

### Extra vars file

N/A

### Ansible Playbook Output

TASK [infra.ee_utilities.ee_builder : Run the Ansible Builder Program] *********************************************
fatal: [student1.h8d9j.example.opentlc.com]: FAILED! => {"changed": true, "cmd": ["ansible-builder", "build", "-f", "/tmp/ansible.tadk1j8wtemp/execution_environment.yml", "-t", "config_as_code", "--container-runtime=podman", "--verbosity", "0"], "delta": "0:00:00.229930", "end": "2024-01-19 18:14:32.787685", "msg": "non-zero return code", "rc": 1, "start": "2024-01-19 18:14:32.557755", "stderr": "ansible_builder.exceptions.DefinitionError: \nError: Unknown yaml key(s), {'options', 'images'}, found in the definition file.\n\nAllowed options are:\n['version', 'build_arg_defaults', 'dependencies', 'ansible_config', 'additional_build_steps']", "stderr_lines": ["ansible_builder.exceptions.DefinitionError: ", "Error: Unknown yaml key(s), {'options', 'images'}, found in the definition file.", "", "Allowed options are:", "['version', 'build_arg_defaults', 'dependencies', 'ansible_config', 'additional_build_steps']"], "stdout": "", "stdout_lines": []}

### Ansible Version

ansible [core 2.13.2]
  config file = /home/student/ansible.cfg
  configured module search path = ['/home/student/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/student/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True

### Ansible Configuration

DEFAULT_VAULT_PASSWORD_FILE(/home/student/ansible.cfg) = /home/student/.password

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

[student@ansible-1 ~]$ more /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)
[student@ansible-1 ~]$ ansible-builder --version
1.1.0

**Comment by abenokraitis** [comment]
@sean-m-sullivan FYI

**Comment by sean-m-sullivan** [comment]
I believe this is an older lab, and may have updated or changed in a way that we were not anticipating. I would redirect you to our instruqt version of this lab, that is updated and expanded [here](https://play.instruqt.com/redhat/invite/yinrttmwemvw). The newer lab uses the updated version of builder and should not have this problem.

**Comment by daleroux** [comment]
You're correct, this is fixed in the new lab, thank you!

**Comment by daleroux** [comment]
closing as the issue is fixed in the more recent lab on instruqt
