### ISSUE TITLE
Change BIG-IP F5 mgmt password task fails

### ISSUE THREAD

**Issue by dirkhamilton** [ansible/workshops#2079]
### Problem Summary

Trying to deploy f5 workshop.  Changed roles/manage_ec2_instances/defaults/main/main.yml to    
filter: 'F5 BIGIP-17*PAYG-Good 25Mbps*'  It wouldn't match anything with the default value.

### Issue Type

Bug

### Extra vars file

ec2_region: us-east-1                  # region where the nodes will live
ec2_name_prefix: flywheel          # name prefix for all the VMs
student_total: 2                       # creates student_total of workbenches for the workshop
workshop_type: f5
#OPTIONAL VARIABLES
admin_password: cfdsa%$69FDAR
networking: true                       # Set this if you want the workshop in networking mode
create_login_page: true                # creates AWS S3 website for ec2_name_prefix.workshop_dns_zone
workshop_dns_zone: dirk-flywheeldata.com       # Sets the Route53 DNS zone to use for the S3 website
towerinstall: true                     # automatically installs Tower to control node
autolicense: true                     # automatically licenses Tower if license is provided
#xrdp: true                            # install xrdp with xfce for graphical interface
offline_token: foo
redhat_username: dirk-bar
redhat_password: foo
pre_build: false
attendance: false
provided_sha_value: 7c4509b3436c7423a60a65815493b3d66162acd09dbca131a9b5edad9e319a40
#provided_sha_value: 0781cab21cd21992a22bb8ed6f9b1018dff0d092d5882e1e9aafbd48337f6662

rhel: rhel9
f5_ee: "quay.io/f5_business_development/mmabis-ee-test:latest"

### Ansible Playbook Output

TASK [../../roles/f5_setup : Change BIG-IP F5 mgmt password] ***********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Name or service not known)
fatal: [flywheel-student1-f5]: FAILED! => {"msg": "Unexpected failure during module execution: ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Name or service not known)", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Name or service not known)

### Ansible Version

ansible [core 2.15.8]
  config file = /home/dirk/workshops/provisioner/ansible.cfg
  configured module search path = ['/home/dirk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dirk/3.9env/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/dirk/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dirk/3.9env/bin/ansible
  python version = 3.9.18 (main, Sep 22 2023, 17:58:34) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/home/dirk/3.9env/bin/python3.9)
  jinja version = 3.1.3
  libyaml = True

### Ansible Configuration

CONFIG_FILE() = /home/dirk/workshops/provisioner/ansible.cfg
DEFAULT_FORKS(/home/dirk/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/dirk/workshops/provisioner/ansible.cfg) = ['/home/dirk/workshops/provisioner/hosts']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /usr/local/ansible/vault_passwd
HOST_KEY_CHECKING(/home/dirk/workshops/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/dirk/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/dirk/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/dirk/workshops/provisioner/ansible.cfg) = False

### Ansible Execution Node

CLI Ansible (Ansible Core)

### Operating System

Red Hat Enterprise Linux release 8.9 (Ootpa)

**Comment by IPvSean** [comment]
@dirkhamilton this repo has stopped supporting the F5 automation workshop.  I removed F5 from most documentation but I must have missed something.  I left the code in there for people to tinker if they wanted to recreate it.

I would suggest just manually provisioning an F5 AMI through the AWS console and figuring out what the new filter is.  I assume F5 has changed their image names so my filter is not working anymore.

Thank you for opening an issue!
