### ISSUE TITLE
Ansible _rhel workshop : Section 2 : Worshop Inventory : hosts disabled by default

### ISSUE THREAD

**Issue by idhaoui** [ansible/workshops#2130]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

When Ansible for RHEL workshop is deployed, it creates a workshop inventory in the automation controller that has 4 hosts : ansible-1 and node{1,2,3}.
All hosts are by default disabled and I can't seem to find any indication in the lab guide to enable them during the section 2 of the lab.
We might either fix the installer of the lab to enable node1,node2 and node 3 by default or suggest that explicitely in the lab guide.

**Comment by bbethell-1** [comment]
Fixed here: https://github.com/rhpds/agnosticv/pull/15766
