### ISSUE TITLE
apache role allows https instead of http

### ISSUE THREAD

**Issue by mkbredem** [ansible/workshops#2136]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

When building the tasks/main.yml for the apache role in https://aap2.demoredhat.com/exercises/ansible_rhel/1.7-role/#step-3---building-the-apache-role

the task "Allow HTTPS traffic on web servers" should allow "http" instead for the subsequent config and curl http://node1 command to work.

**Comment by mkbredem** [comment]
Hereis the specific task as it should appear:

- name: Allow HTTPS traffic on web servers
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
  when: inventory_hostname in groups['web']
  notify: Reload Firewall

**Comment by rlopez133** [comment]
Closing as its a duplicate to #2131
