### ISSUE TITLE
workshop_inventory nodes default to off

### ISSUE THREAD

**Issue by mkbredem** [ansible/workshops#2137]
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

in exercise https://aap2.demoredhat.com/exercises/ansible_rhel/2.3-projects/#create-a-job-template-and-run-a-job

job template runs, but doesn't match any hosts because the nodes in the inventory are toggled off:

![image](https://github.com/ansible/workshops/assets/56933449/6bd0a240-67c2-438b-915e-bc681b246b1f)

**Comment by rlopez133** [comment]
Closing as a duplicate to #2130
