### ISSUE TITLE
Ansible Security Workshop in RHDP

### ISSUE THREAD

**Issue by rhjcd** [ansible/workshops#2143]
### Problem Summary

failing to provision:

TASK [install idstools] ********************************************************
fatal: [8gs28-student1-snort]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python", "-m", "pip.__main__", "install", "idstools"], "msg": "stdout: Collecting idstools\n  Could not fetch URL https://pypi.python.org/simple/idstools/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) - skipping\n\n:stderr:   Could not find a version that satisfies the requirement idstools (from versions: )\nNo matching distribution found for idstools\n"}

### Issue Type

Bug

### Extra vars file

https://github.com/rhpds/agnosticv/tree/master/ansiblebu/AAP2_WORKSHOP_SECURITY_AUTOMATION

### Ansible Playbook Output

**TASK [install idstools] ********************************************************
fatal: [8gs28-student1-snort]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python", "-m", "pip.__main__", "install", "idstools"], "msg": "stdout: Collecting idstools\n  Could not fetch URL https://pypi.python.org/simple/idstools/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) - skipping\n\n:stderr:   Could not find a version that satisfies the requirement idstools (from versions: )\nNo matching distribution found for idstools\n"}**

### Ansible Version

TASK [install idstools] ********************************************************
fatal: [8gs28-student1-snort]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python", "-m", "pip.__main__", "install", "idstools"], "msg": "stdout: Collecting idstools\n  Could not fetch URL https://pypi.python.org/simple/idstools/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) - skipping\n\n:stderr:   Could not find a version that satisfies the requirement idstools (from versions: )\nNo matching distribution found for idstools\n"}

### Ansible Configuration

https://github.com/rhpds/agnosticv/tree/master/ansiblebu/AAP2_WORKSHOP_SECURITY_AUTOMATION

### Ansible Execution Node

Ansible Controller (previously known as Ansible Tower)

### Operating System

https://github.com/rhpds/agnosticv/tree/master/ansiblebu/AAP2_WORKSHOP_SECURITY_AUTOMATION

**Comment by perryrivera1** [comment]
Hello Ansible BU Team: Might there be a status update to this bug report? At least 1 customer has tagged the Impact/Urgency as High. Thank you for any news you may have.

**Comment by abenokraitis** [comment]
The Ansible Security Workshop has been deprecated since ... a while ago and should have been removed on Dec 31, 2023. Only one workshop after that date was officially "supported" due to its scheduling. Therefore, bugs are no longer being considered as the workshop is now end of life.
