### ISSUE TITLE
 workshop refactor - INTRO DEMO - tower demo (intro demo)

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#218]
##### SUMMARY
we need prescriptive demo for the pre-populated demo

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
exercises/demos

##### ADDITIONAL INFORMATION
as per notes for network workshop 3.0
https://docs.google.com/document/d/1A4-yYcKnpmfX-2Aqcqmh82AmLXpTvIxjwtEj-1mmu9k/edit?usp=sharing (internal red hat only link)

**Comment by victorock** [comment]
@IPvSean could you clarify what is the expectation on this? Maybe i can help..

**Comment by IPvSean** [comment]
I am not sure, I think @termlen0 or @gdykeman can help jog my memory, we might have this covered but not documented at this point b/c Gerald pre-loaded a bunch of tower job templates

**Comment by IPvSean** [comment]
closing issue, no update from @termlen0 or @gdykeman
