### ISSUE TITLE
Apache Guacamole integration

### ISSUE THREAD

**Issue by colin-mccarthy** [ansible/workshops#244]
##### SUMMARY
Add a nob that uses HTTP/Apache Guacamole for the labs. For customers that have SSH/22 blocked on their network firewall.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Apache Guacamole integration

##### ADDITIONAL INFORMATION
 
RedHat folks like Med, Eric & Michael have used this before during labs.

**Comment by jmcleroy** [comment]
There is an issue with this type of build and that is the need to setup the Guacamole server that would prevent this from working unless they are some ansible modules for Guacamole that could update the connection lists.

**Comment by IPvSean** [comment]
do we still need this @jmcleroy & @colin-mccarthy if we have VScode?

**Comment by jmcleroy** [comment]
Yes for two reasons. Until it has a cert yes it’s still needed. Also some
times I have the students use rdp to pass their security restrictions this
was needed for 2 customers recently where there security didn’t trust let’s
encrypt.

Thanks

Eric

**Comment by IPvSean** [comment]
this is for guacamole, not for the xdrp

**Comment by jmcleroy** [comment]
I misread the request. Yes this would still be needed until VSCode has a valid certificate. It is also very useful if the customers need to whitelist a single item for a workshop to occur. But if VSCode is signed it would take away alot of the need for guac. 

Thanks,

Eric

**Comment by cloin** [comment]
I have an issue open to add the cert to coder. I can knock that out pretty quickly. Doesn’t address the issue of customers not trusting letsencrypt though.
