### ISSUE TITLE
Need to install "jmespath" for F5 exercises

### ISSUE THREAD

**Issue by irixjp** [ansible/workshops#262]
##### SUMMARY
Exercises doesn't work at "Output parsing" in exercises/ansible_f5/1.4-add-pool-members/README.md.

```
TASK [Show members belonging to pool] ***********************************
fatal: [f5]: FAILED! =>
  msg: You need to install "jmespath" prior to running json_query filter
```

##### ISSUE TYPE
It is necessary to install jmespath to control node.

Workaround:
A instructor guides to install the package in the following way:

[student1@ansible ~]$ `sudo yum install -y python-jmespath`

**Comment by IPvSean** [comment]
this is part of devel branch, thanks for bringing this to our attention @payalsin

**Comment by brianstinehart** [comment]
We're still experiencing this issue...

TASK [Show members belonging to pool http_pool] **********************************************************************************************************************************************************************************************
fatal: [f5]: FAILED! =>
  msg: You need to install "jmespath" prior to running json_query filter

Our workaround: sudo pip install jmespath

**Comment by IPvSean** [comment]
still testing this... will try to figure out what is going on b/c we def install jmespath

**Comment by IPvSean** [comment]
I am not seeing a `jmespath` error anymore, please reopen this bug if you can replicate this and tell me how you provision the workbench

**Comment by ericzji** [comment]
Hi Sean,
I also saw this issue, but I guess it's not consistently happening. 

`
TASK [Show members belonging to pool http_pool] *******************************************************************************************************************************************************
fatal: [f5]: FAILED! =>
  msg: You need to install "jmespath" prior to running json_query filter

PLAY RECAP ********************************************************************************************************************************************************************************************
f5                         : ok=4    changed=1    unreachable=0    failed=1

[student1@ansible 2.0-disable-pool-member]$
`
