### ISSUE TITLE
Broken URL: https://network-automation.github.io - page is 404.

### ISSUE THREAD

**Issue by Valien** [ansible/workshops#268]
##### SUMMARY
The sub-domain: network-automation.github.io is broken.

##### ISSUE TYPE

 - Bug Report

Looks like the link on the front page [README.MD](https://github.com/ansible/workshops/blob/master/README.md) has a bunch of links to the https://network-automation.github.io page but that page is now 404.

https://network-automation.github.io/linklight/decks/ansible-essentials.html
It affects the following:

- Ansible Essentials Deck
- Intro to Ansible Tower Deck
- Ansible Networking-v2 Deck
- Ansible F5 Deck

You can still click and find these decks but no more network-automation link. This also affects RHPDS as they are linking to the 404'd page as well.

**Comment by IPvSean** [comment]
not broken, moved entirely, I will get the links updated so this doesn't fail :( Sorry about the confusion here.
The new URL is here: https://ansible.github.io/workshops/

The short URL ansible.com/linklight was already fixed

**Comment by IPvSean** [comment]
@Valien can you confirm this is fixed for you?

**Comment by Valien** [comment]
All fixed! I spun up a new workshop and going through content and links work now. Thanks for getting this fixed quickly.
