### ISSUE TITLE
workshop_type is not optional anymore, needs to be reflexc

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#273]
##### SUMMARY

Currently the documentation and the variable examples in `sample_workshops/` explain the variable `workshop_type` as optional. However, the [provisioner code](https://github.com/ansible/workshops/blob/f943bf7bcd508be21988a6cd5c4fdb03caa77a8b/provisioner/provision_lab.yml#L16) hard-codes a check if the workshop type is defined.

We need to update our documentation and samples to reflect this.

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
in addition to this PR, we should `assert` for this right at the beginning so we get predictive failures, keeping this open for now

**Comment by IPvSean** [comment]
closed by https://github.com/ansible/workshops/pull/274
