### ISSUE TITLE
vagrant-demo/README.md has syntax errors

### ISSUE THREAD

**Issue by Dostonbek1** [ansible/workshops#309]
##### SUMMARY

vagrant-demo/README.md has markdown syntax errors, like the following

       ```bash
       git clone https://github.com/network-automation/linklight
       ```

 Probably because of extra tab spases.

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by IPvSean** [comment]
I think is fixed now, I forgot to close out this issue, please reopen if there is still a bug!
