### ISSUE TITLE
Devel Branch - missing hosts file

### ISSUE THREAD

**Issue by colin-mccarthy** [ansible/workshops#332]
##### SUMMARY
Tried to run provisioner from the Devel branch via instructions and got a weird "Boto3 not installed error". Noticed ansible.cfg points to hosts for inventory. This branch contains an inventory directory with some    
ec2 files in it. Long story short I created a hosts file with local host in it and the playbook ran fine the "Boto3 error" was no longer an issue. 

I'm not sure what the inventory directory and ec2 files are for, so I figured I would file an issue instead of a PR. Maybe you don't want a host file for some reason. 

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: COLINRULES
admin_password: ansible
student_total: 1
workshop_type: networking
# possible values cisco, arista, juniper or multivendor
network_type: arista
## Optional Variables
create_login_page: true



##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```
ansible 2.8.2
  config file = /Users/colin/work/workshops/provisioner/ansible.cfg
  configured module search path = ['/Users/colin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```


##### OS / ENVIRONMENT
Mac

**Comment by IPvSean** [comment]
fixed!
