### ISSUE TITLE
Translate new server workshop contents to Japanese

### ISSUE THREAD

**Issue by hiro52** [ansible/workshops#333]
Base English contents.
https://github.com/ansible/workshops/tree/devel/exercises/ansible_rhel

**Comment by IPvSean** [comment]
https://github.com/ansible/workshops/pull/337

**Comment by IPvSean** [comment]
@hiro52 do you have time or energy to look at the ansible_network exercises?

**Comment by Canalroy** [comment]
Hi
I create some more Japanese transcript files for the RHLE workshop at PR #350.

**Comment by Canalroy** [comment]
Thank you for Merged my PR to Devel branch!
Can you change this issue status to close when you merged Devel branch to Master?

I will create another issue and send PR when I translate network/Tower/F5 exercises.

**Comment by IPvSean** [comment]
this is now merged!
