### ISSUE TITLE
Put raw/endraw in HTML comments

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#334]
##### SUMMARY

Github.io pages' markdown has problems rendering curly brakcets, `{` `}`. Thus, Currently the networking workshops use `{% raw %}` and `{% endraw %}` to work around this limitation.
However, those then show up in the main github.com markdown rendering, as shown below:
![github-raw](https://user-images.githubusercontent.com/1998084/61569319-10c28080-aa87-11e9-8c35-c35aed2aa5de.png)

This can be solved by putting the `{% raw %}` / `{% endraw %}` into HTML styled comments:
```
<!-- {% raw %} -->
- name: something
  debug: "{{ myvar }}"
<!-- {% endraw %} -->
```

This was successfully used in all RHEL workshops, as it can be seen in the following screenshots:

Rendering on github.com:
![github com-simple-loops](https://user-images.githubusercontent.com/1998084/61569474-ce4d7380-aa87-11e9-9812-c8a4e86ac8d8.png)

Rendering on github.io pages:
![github io-loops](https://user-images.githubusercontent.com/1998084/61569475-cee60a00-aa87-11e9-8277-3bc4ed38ccb5.png)

Actual source code:
![raw-simple-loops](https://user-images.githubusercontent.com/1998084/61569521-efae5f80-aa87-11e9-9ea6-5a9b848c7194.png)

##### ISSUE TYPE

- Documentation Report

**Comment by IPvSean** [comment]
STOP WORKING ON PTO!, this is awesome though

**Comment by IPvSean** [comment]
this has been synced for all workshop variants
