### ISSUE TITLE
lab deployment failure in step checkSoftwareDeploy

### ISSUE THREAD

**Issue by brianstinehart** [ansible/workshops#365]
Hello,

My deployment is failing through RHPDS with the following:

Your service provision request for RHPDS-DEM-bstineha-redhat.com-PROD_LINKLIGHT_ALL-c7e2 failed when provisioning.
The problem is happening in step checkSoftwareDeploy
The deployment failed while deploying the lab software. This could be due to a bug in the lab playbook or its taking too long to run. If you know the demo/lab owner you may want to let them know it is failing.
The administrators have been alerted of this problem and will look into it as soon as possible. In the meantime you can attempt to order this service again. If this problem persists please contact OPENTLC/RHPDS Admins at rhpds-admins@redhat.com

Could this please be looked into urgently?

Thank you,

Brian

**Comment by IPvSean** [comment]
this issue was a problem with an optional knob turned on that is not used `xrdp: true` that allows students to RDP into a xfce visual desktop environment and use vscode.

We have done two things

- disabled this knob for all Red Hat Product Demo System (RHPDS) workshops (ansible_rhel, ansible_network and ansible_f5) 
- fixed the issue with xfce which is this single task:
```
- name: ENSURE XFCE IS INSTALLED
  yum:
    name: "@xfce"
    skip_broken: true
```

**Comment by IPvSean** [comment]
tagging @tonykay

**Comment by brianstinehart** [comment]
This same failure has cropped back up in the RHPDS deployment.

Any chance we can look back into it?

**Comment by brianstinehart** [comment]
> This same failure has cropped back up in the RHPDS deployment.
> 
> Any chance we can look back into it?

This has somehow been resolved and I'm able to deploy in RHPDS. Does anyone know what caused the issue or what corrected it?

**Comment by IPvSean** [comment]
License needed to be updated for both GPTE and another server I maintain, both have been updated and I’m working on ways to fail and pass and the future with messages about limitations or what happened
