### ISSUE TITLE
Link to "archived exercises" in network automation does not work

### ISSUE THREAD

**Issue by gdykeman** [ansible/workshops#376]
https://ansible.github.io/workshops/exercises/ansible_network/

For "There are additional older exercises that are archived here."

Link goes to:
https://ansible.github.io/workshops/exercises/ansible_network/archive/

@IPvSean

**Comment by liquidat** [comment]
@IPvSean This still does not fix the issue entirely:
https://github.com/ansible/workshops/blob/devel/exercises/ansible_network/supplemental/README.md
expects the exercises under the directory `supplemental/exercise`, but they are directly under `supplemental/`.

Example:
```
- [Exercise 1.0 - Exploring the lab environment](./exercises/1-0-explore)
```

The location of the exercise is however:
```
workshops/exercises/ansible_network/supplemental/1-0-explore/README.md
```

**Comment by IPvSean** [comment]
this is fixed, just checked https://ansible.github.io/workshops/exercises/ansible_network/supplemental/
