### ISSUE TITLE
Service Exercise 2.1: Put 'admin' username at top this section, boldly

### ISSUE THREAD

**Issue by rcpavlicek** [ansible/workshops#381]
When giving the workshop, users immediately try to log in to tower as they begin exercise 2.1.  However, the 'admin' username is not specified until 2.2.  Please specify the 'admin' username boldly near the top of 2.1.

**Comment by liquidat** [comment]
The idea is that people first read, then do the actual tasks.
Thus, would it also be ok to boldly clarify that the login happens first in exercise 2.2? Or is that just not realistic?

**Comment by rcpavlicek** [comment]
I understand the premise. I contend it isn't realistic, based on what I just witnessed.  At least a third of the class tried to sign in immediately, perhaps more.  Putting it at the top of 2.1 is prudent, in my opinion.

**Comment by liquidat** [comment]
Thanks for the answer. I will try to find a solution which does not disrupt the flow of the workshop but is also visible enough to folks who really want to start on this.

**Comment by liquidat** [comment]
I submitted a fix for this. Basically I restructured the workshop a bit to make more sense: people will not immediately be able to login to the page - and are then asked to read on to understand the concepts and everything. That way we cater to their curiosity without loosing them to the UI.
