### ISSUE TITLE
Network Exercise 6, Step 5

### ISSUE THREAD

**Issue by brianstinehart** [ansible/workshops#399]
https://github.com/ansible/workshops/tree/master/exercises/ansible_network/6-tower-job-template

Backup directory incorrect. Currently listed as "/tmp/backup" -> Actual existing directory is just "/backup"

**Comment by IPvSean** [comment]
thanks! Fix will go in the next release

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/releases/tag/v1.2
