### ISSUE TITLE
Network Exercise 7 Step 2

### ISSUE THREAD

**Issue by gdykeman** [ansible/workshops#400]
The role banner has a very simple main.yml file:
https://ansible.github.io/workshops/exercises/ansible_network/7-tower-survey/

- name: configure banner
  include_tasks: ".yml"

Should be:
include_tasks: "{{ ansible_network_os}}.yml"

@IPvSean

**Comment by IPvSean** [comment]
thanks! Fix will go in the next release

**Comment by IPvSean** [comment]
fixed with https://github.com/ansible/workshops/releases/tag/v1.2
