### ISSUE TITLE
Ansible RHEL Workshop Exercise 1.6 template error

### ISSUE THREAD

**Issue by mcvic1rj** [ansible/workshops#441]
##### SUMMARY

The Challenge Lab for exercise 1.6 has a display error in solution the Jinja2 template when being rendered by Github Pages.

Displays:
```bash 
Welcome to .
 
deployed on  architecture
running kernel .
```
Expected:
```bash
Welcome to {{ ansible_hostname }}.
{{ ansible_distribution }} {{ ansible_distribution_version}}
deployed on {{ ansible_architecture }} architecture
running kernel {{ ansible_kernel }}.
```
##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

N/A

e.g. here is an example of an extra vars file we are looking for:
N/A
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by liquidat** [comment]
Closed via #471
