### ISSUE TITLE
Make all passwords configurable

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#447]
##### SUMMARY

Currently there are many instances which are using default passwords. While these are only short living instances, we should nevertheless make all passwords configurable during provisioning so that attackers cannot guess the passwords during mass scans.

Machines in question which do not have configurable passwords:

- Check Point MGMT
- Check Point GW
- QRadar

Not affected:

- Control Host
- Snort
- Attacker

##### ISSUE TYPE

 - Bug Report

**Comment by liquidat** [comment]
@IPvSean Can you please check the instances of the networking/F5 workshops if any of them have configurable passwords or not, and add them to one of the two lists above?

**Comment by ericzji** [comment]
@IPvSean Wanted to check if you have randomized the password for ansible control node? I got the request for such, and would like to see if you had it already implemented.

**Comment by t-prinz** [comment]
I believe I am experiencing an issue that is related to this.  In particular, I am provisioning the RHEL workshop with a custom password:

$ grep admin_password extra_vars.yml 
admin_password: r3dh4t1!

The following task in ./workshops/provisioner/roles/control_node/tasks/tower.yml failed:

- name: specify in Tower which directory to look for custom venvs
  uri:
    url: https://localhost/api/v2/settings/system/
    method: PATCH
    user: admin
    password: "ansible"
    validate_certs: False
    force_basic_auth: yes
    body_format: json
    body: '{"CUSTOM_VENV_PATHS": ["/opt/my-envs/"]}'
    status_code:
      - 200

Changing the password variable as follows rectified the situation and the provisioner worked fine:

    password: "{{admin_password}}"

**Comment by liquidat** [comment]
@ericzji:
> @IPvSean Wanted to check if you have randomized the password for ansible control node? I got the request for such, and would like to see if you had it already implemented.

We do not randomize the password, but we do support any password you provide in the provisioner. So in our current deployments via for example RHPDS each deployment has a different password provided to the provisioner.

**Comment by liquidat** [comment]
@t-prinz 
> I believe I am experiencing an issue that is related to this. In particular, I am provisioning the RHEL workshop with a custom password:
> 
> $ grep admin_password extra_vars.yml
> admin_password: r3dh4t1!
> 
> The following task in ./workshops/provisioner/roles/control_node/tasks/tower.yml failed:
> 
> * name: specify in Tower which directory to look for custom venvs
>   uri:
>   url: https://localhost/api/v2/settings/system/
>   method: PATCH
>   user: admin
>   password: "ansible"
>   validate_certs: False
>   force_basic_auth: yes
>   body_format: json
>   body: '{"CUSTOM_VENV_PATHS": ["/opt/my-envs/"]}'
>   status_code:
>   - 200
> 
> Changing the password variable as follows rectified the situation and the provisioner worked fine:
> 
> ```
> password: "{{admin_password}}"
> ```

This is already fixed in the devel branch: https://github.com/ansible/workshops/blob/a99dec6d283382e9332d47572354e6ca8e524423/provisioner/roles/control_node/tasks/tower.yml#L69

**Comment by IPvSean** [comment]
as part of release https://github.com/ansible/workshops/pull/540 this is now configurable for Ansible Tower, we need to make sure this reflects to all appliances as well (e.g. F5) @ericzji  I need to check later about f5.... it should be working but I need to test again.  RHPDS will now force a randomized password as per Tony Kay.

**Comment by t-prinz** [comment]
Thanks @liquidat!

**Comment by IPvSean** [comment]
this is configurable for f5 as well https://github.com/ansible/workshops/blob/devel/provisioner/roles/f5_setup/tasks/main.yml#L15
