### ISSUE TITLE
Wording and spacing issue in network deck

### ISSUE THREAD

**Issue by jmighion** [ansible/workshops#462]
##### SUMMARY

https://github.com/ansible/workshops/blob/master/decks/ansible_network.pdf
The slides near the end in exercise 3 about facts the title say `Running the Ansible Playbook with verbosity` but the example isn't being ran with any verbosity. The slide before that has a debug task with msg `The serial number is:{{ ansible_net_serialnum }}"`. There should be a space between the `:` and the var.
##### ISSUE TYPE

 - Bug Report

**Comment by IPvSean** [comment]
fixed!
