### ISSUE TITLE
Wrong admin password in the exercise instructions

### ISSUE THREAD

**Issue by jmighion** [ansible/workshops#463]
##### SUMMARY

https://github.com/ansible/workshops/blob/master/exercises/ansible_network/5-explore-tower/README.md
The docs says the password is `instructor` but it's `ansible`.
https://github.com/ansible/workshops/blob/master/provisioner/group_vars/all.yml#L1

**Comment by colin-mccarthy** [comment]
Now the docs says the password will be provided by instructor.

This issue can be closed.
