### ISSUE TITLE
Broken link for Ansible Automation Workshops presentation deck

### ISSUE THREAD

**Issue by tabowling** [ansible/workshops#468]
##### SUMMARY
This link is not valid https://ansible.github.io/workshops/decks/ansible_technical.pdf

The following pages refer to it resulted in dead links
 - http://rhelkev.rhdemo.io/ for the Ansible Technical Deck button.
 - https://github.com/ansible/workshops/blob/master/README.md for the "Ansible Red Hat Enterprise Linux Workshop" presentation deck.

##### ISSUE TYPE
 - Bug Report

**Comment by aenertia** [comment]
confirmed

**Comment by liquidat** [comment]
Fixed in devel: https://github.com/ansible/workshops/commit/f7419e0c566e6c96f80535642d0193ca6e48a69a#diff-04c6e90faac2675aa89e2176d2eec7d8
