### ISSUE TITLE
Network Workshop Exercise 5 will not succeed

### ISSUE THREAD

**Issue by irixjp** [ansible/workshops#482]
##### SUMMARY
Network Workshop Exercise 5 will not succeed.

##### ISSUE TYPE
 - Bug Report

##### DETAILS
This is because the old fixed password is used in the following playbook.
https://github.com/network-automation/tower_workshop/blob/master/network_backup.yml#L65

Therefore, creation of the restore job used in Exercise 9 fails.

**Comment by brianstinehart** [comment]
+1

Failed for all students in a large group for a workshop with a major bank today.

**Comment by IPvSean** [comment]
Will try to get this sorted tomorrow I had to prepare for RHTE North America today and did not have sufficient time to bite into this.

**Comment by IPvSean** [comment]
This has been fixed with https://github.com/ansible/workshops/pull/493 can you please confirm if this is still an issue and reopen the ticket. Thanks for your patience.
