### ISSUE TITLE
[Security Exercises] Missing step 1.2 on exercise 1.1

### ISSUE THREAD

**Issue by colin-mccarthy** [ansible/workshops#527]
##### SUMMARY
There is no step 1.2 on exercise 1.1

It goes from Step 1.1 (- Objective) then to Step 1.3 (- Architecture of the lab, Nodes and Services). 😀😀😀

##### ISSUE TYPE
- Documentation Report

**Comment by liquidat** [comment]
Nice catch, PR is on its way!

**Comment by IPvSean** [comment]
this is part of release: https://github.com/ansible/workshops/pull/540
