### ISSUE TITLE
2.4 Surveys lab has incorrect Inventory

### ISSUE THREAD

**Issue by hataylorjr** [ansible/workshops#531]
##### SUMMARY

INVENTORY: Webserver is not right in this exercises.  Should be Workshop inventory.

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
more info needed, which workshop variant, etc?

**Comment by IPvSean** [comment]
can I get an update here @hataylorjr

**Comment by dpullman-emergent** [comment]
@hataylorjr Respectfully suggest that Webserver is the right inventory in this exercise. We had issues with students who lost access to their tower instance (and code-server) when they used Workshop inventory. Please see [#807](https://github.com/ansible/workshops/issues/807) for details.
