### ISSUE TITLE
2.6 Workflows final test returns no output

### ISSUE THREAD

**Issue by hataylorjr** [ansible/workshops#532]
##### SUMMARY

Curl command to retrieve the Hello World fails for me, no output is returned.

Same URL in the web browser shows Hello World! 

I would suggest dropping the curl command and have them open a new tab on the browser with the URL specified. 

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
which workshop_type?

**Comment by hataylorjr** [comment]
Ansible Tower, part of the virtual bootcamp @IPvSean is helping us with over the past month.

**Comment by IPvSean** [comment]
can you try now?  let me know if this is still an issue.  I think this is fixed.

**Comment by IPvSean** [comment]
if this is the `rhel` workshop this should be fixed with https://github.com/ansible/workshops/pull/878
