### ISSUE TITLE
Windows workshop `create_login_page`

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#543]
##### SUMMARY

Docs hosting strategy for Windows workshop should be closer to the other workshop types. We should get rid of the `docs` instance that is provisioned and implement `create_login_page` as done in other workshops to create S3 static site for student landing page and docs host. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- docs
- provisioner

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by cigamit** [comment]
Or we should move the other workshops to utilizing a sign up page.  The intent is to stop having to manually assign students an ID.  When you do workshops that have upwards of 100 people, either manually writing out post it notes with numbers on them, or assigning them as they come in the door can become tedious.

It also has the added benefit of knowing exactly who attended the workshop (sometimes we don't have a list of who showed up when we are doing it for individual clients) and how far they actually progressed through the workshop.

**Comment by cloin** [comment]
Yeah I shouldn’t have been so opinionated in the issue description. I do think it would be good to come together on this one and figure out a uniform student “onboarding” experience.

**Comment by ffirg** [comment]
Might also be worth considering this : https://github.com/ansible/workshops/issues/435
I've used a Grafana dashboard for tracking student progress. Works well but needs some refinement. Or maybe just further food for thought.

**Comment by cloin** [comment]
I think the sign up page definitely has value, can't argue that it doesn't. However, if we're thinking about enablement of this workshop type for all SAs, we need to keep new workshop types as predictable as possible. Keeping this workshop consistent with all others benefits maintainers, contributors, and presenters. 

While I do think that the current implementation works and has for some time, this will be the only workshop type that does it differently and I don't know that anybody else will have time or see it as a priority to adopt the skylight strategy. If the windows workshop adopts `create_login_page`, that's just another component that doesn't need to be maintained by a windows workshop specific maintainer/contributor.

**Comment by IPvSean** [comment]
Why don't we discuss at the upcoming Friday sync meeting.  The `create_login_page` methodology was literally taken from the SA tiger-team org and I just updated and it and took over maintaining an up-to-date version of it that could handle multiple workshop types.  I even tried to make CSS match.  I would like to see this version of the sign-up, I am surprised that no one has brought me this strategy before.

**Comment by cloin** [comment]
Closing.

Windows workshop now uses `create_login_page`. It'd be good to look at putting the old skylight page in front for *all* workshop types to dole out student numbers making things a bit easier when running a workshop. 

Using `create_login_page` for now so when we make updates, we don't have to duplicate for a single workshop type.
