### ISSUE TITLE
Revisit vscode + gitlab for Windows

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#544]
##### SUMMARY

It may cut down on complexity to eliminate the workstation instance for students in the Windows workshop by adopting Coder(vscode) + Gitlab/Tower-local git repos. This also would eliminate lag, rdp/ssh client setup and window interaction issues with keyboard/mouse passthru. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- exercises
- provisioner

**Comment by cigamit** [comment]
We would have to ensure we put proper certs on the Tower servers and ensure we are using DNS Domains (which might be difficult for anyone that doesn't have that option).  A lot of corporate laptops will not connect if there is not a valid cert / domain.

If we drop those, we could technically drop the Domain Controller and everything that goes along with that too.

**Comment by cloin** [comment]
It might be nice to drop the DC. It doesn’t add a lot resource wise for the workshops but does add complexity. I wonder if we could potentially do more without it? On the other hand, I kind of like the idea of having it. It would also be cool to work it into the workshop content as opposed to being supporting infrastructure.

**Comment by ffirg** [comment]
It would be nice to still have the DC option in there and do more with it, as it's a fundamental part of a windows admin role.

**Comment by cloin** [comment]
It almost seems disingenuous to drop the DC. Though maybe we revisit it in the future to cut down complexity and potentially cost by not including it by default. 

Coder now has a password for basic auth, we could change it to per student if necessary. There's also an issue open to add a cert (https://github.com/ansible/workshops/issues/569). I think we're close to being able to offer coder in Windows as the primary mechanism for editing, pushing and executing playbooks from CLI. 

We can always keep the workstation as is and reevaluate down the road.

**Comment by cigamit** [comment]
What port will coder be running on?  I thought someone in slack mentioned it running on port 8080, which would be a no go for a lot of corporate firewalls (common proxy port).

**Comment by cloin** [comment]
Yep 8080 is default. The idea is to add in another option and see how adoption goes. 8080 is of course customizable and nothing proposed here will eliminate the current implementation unless it makes sense down the road.

Currently, rdp seems to be the most common way students interact with the workshop followed by html5 rdp which is less favorable due to latency. Coder has the potential to remove the client altogether. Couple this with a student login page and docs hosted by a static site or on the control node itself, and you have a workshop and all the student needs in 3 browser tabs.

As it stands, Coder is there and ready to be used. It's an additional option to evaluate as we run more and more of these workshops.

**Comment by dlemus** [comment]
I actually have been looking at using the visual studio code plugin for the non-windows workshops as well, as it helps when giving the workshop for clients that disallow SSH on their network.  But I agree that having the interface to the workshop be the visual studio code and tower to the windows students makes a lot of sense as an alternative to RDPing into a windows host. What happens in the background with a DC I have no opinion on, as the students interactions would be purely through Tower and VS Code (in my workshops).

**Comment by cloin** [comment]
Coder is now in devel for all workshop types. It includes password authentication and its own cert and runs on 443.

**Comment by kenmoini** [comment]
A thought looking forward: nginx reverse proxy is easy to deploy with automated Let's Encrypt on a front-facing standard port and forward to any internal port/service.

An additional note about Let's Encrypt - you will likely run into quota limit issues using the HTTP solver when deploying a large workshop environment, or doing so repeatedly in testing.  Week-long time out, I learned the hard way and had to buy a new domain on the day of a workshop.

Testing an AWS R53 + LE Wildcard role that can be distributed to all nodes to avoid such rate limits.  Will submit a PR if it works and there's interest?

**Comment by IPvSean** [comment]
We already have that?  We have two certs, one for tower and one for vs code
and a huge quote increase for rhdemo.io

**Comment by kenmoini** [comment]
Aha, did not know you could get a quota increase from LE for a domain.
We're operating on a different set of domains.  (@ a RH PS Partner)

**Comment by dlemus** [comment]
@kenmoini One thing I did in the past, if I'm redeploying or testing a workshop, is to use staging parameters instead: https://letsencrypt.org/docs/staging-environment/

This gives 30,000 certs a week versus 50 certs a week. It's a good backup plan when or if certs run out in the production area.

**Comment by cloin** [comment]
Closing.

Windows workshop is on devel with a couple PRs in flight to fix exercises. Dropped the DC and the workstation in favor of code-server hosted on the tower server for each student. code-server, tower and gitlab all have certs issued and all operating on 443. Only pre-req for students is a modern browser (chromium based browsers seem to work slightly better for code-server).
