### ISSUE TITLE
Typo in ansible_rhel.pdf

### ISSUE THREAD

**Issue by dynamiteSkunkApe** [ansible/workshops#563]
##### SUMMARY
Page 53 of the workshop/decks/ansible_rhel.pdf contains a typo. There is a missing quotation on the content: line

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
fixed in the master deck, will do a PR soon for this deck

**Comment by IPvSean** [comment]
https://github.com/ansible/workshops/blob/master/decks/ansible_rhel.pdf
