### ISSUE TITLE
F5 AS3 Exercises will not currently work

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#565]
##### SUMMARY
The error is happening for F5 workshop variant: 

```
TASK [CREATE AS3 JSON BODY] ****************************************************

fatal: [f5]: FAILED! => 

  msg: 'An unhandled exception occurred while running the lookup plugin ''template''. Error was a <type ''exceptions.AttributeError''>, original message: ''VariableManager'' object has no attribute ''_loader'''
```

The relevant code is here: https://github.com/ansible/workshops/blob/master/exercises/ansible_f5/3.0-as3-intro/as3.yml#L11

This will automatically get fixed when yum goes to ansible 2.9.1 or newer with this PR:
- https://github.com/ansible/ansible/pull/64517

In the meantime please use pip to install ansible 2.9.1 or newer 

##### ISSUE TYPE
 - Bug Report

##### EXTRA VARS FILE
```paste below
workshop_type: f5
```

##### ANSIBLE VERSION
```paste below
Ansible 2.9.0
```

##### OS / ENVIRONMENT
RHEL 7.6

##### TOWER
No, recreated in Engine

##### PLAYBOOK SHORT OUTPUT
N/A

##### PLAYBOOK LONG OUTPUT
N/A

**Comment by Spredzy** [comment]
Fixed by https://github.com/ansible/workshops/pull/571
