### ISSUE TITLE
Add cert to coder

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#569]
##### SUMMARY

Add cert for https 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- provisioner

##### ADDITIONAL INFORMATION

https://github.com/cdr/code-server#encrypting-traffic-with-https

```yaml

```

**Comment by IPvSean** [comment]
I think the first step is that we need to listen on nginx to both services... I got this working today->


`/etc/nginx/nginx.conf`
```
    server {
        listen 80;
        listen [::]:80;
        listen 80;
        listen [::]:80;
        server_name seantest.rhdemo.io;
      location / {
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header Host $host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection upgrade;
          proxy_set_header Accept-Encoding gzip;
      }
    }
```
using an example from: https://github.com/cdr/code-server/blob/master/doc/quickstart.md

**Comment by IPvSean** [comment]
merged
