### ISSUE TITLE
cleanup tower-qe DNS entries that are orphaned 

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#575]
##### SUMMARY
right now the tower-qe system is creating a route53 entry like this->

```student1.tower-qe-f5-tower-3.5.2-null-351-devel.rhdemo.io```

the problem is the periods, there is actually 5 periods in this DNS entry.... the route53 support page->

>For records that have four or more labels, you must specify the exact name of the record. No wildcard searches are supported. For example, if the hosted zone includes a record named label4.record1.example.com, you can find that record only if you specify label4.record1.example.com in the search field.

source: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-listing.html

The problem is I can't easily clean these up, and I can't easily even search on wildcard b/c of the periods.... so I have to manually go and delete each one of these :( . If we just use dashes or anything else versus periods I could automate this in our normal system :(

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
n/a

**Comment by IPvSean** [comment]
@Spredzy is this something that is easily fixable?  I have not looked yet at the code

**Comment by Spredzy** [comment]
Easil fixable, will do tomm

**Comment by Spredzy** [comment]
Fixed by https://github.com/ansible/workshops/pull/577
