### ISSUE TITLE
Instructor Tower

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#585]
##### SUMMARY

It would be nice to have an instructor Tower or create an instructor login on student1-ansible or reserve studentN workbench for instructor. Tower would be potentially preloaded with https://github.com/ansible/workshops/tree/master/demos
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- provisioner

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by IPvSean** [comment]
we could just make a student0 and not make it part of the webpage?  this makes it super easy to match the code without adding a special name for it

**Comment by dlemus** [comment]
If it helps, I also have pre-built ansible tower credentials, projects, templates, exercises if its easier to have prebuilt collateral for the instructor instance (less typing, more instructing).

**Comment by cloin** [comment]
I think much of the benefit of having an instructor tower will be delivered through product-demos as those become available which will allow an instructor to use a student tower instance to add additional content to the entire workshop.
