### ISSUE TITLE
Document demos

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#586]
##### SUMMARY

It would be nice to include workbench documentation for each workshop type on the readme of https://github.com/ansible/workshops/tree/master/demos

This could accompany an onboarding doc on how to write demos on top of a specific workbench by workshop type which would help to push new workshops out as demos on top of existing workshop types.

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
can you re-open in https://github.com/ansible/product-demos
