### ISSUE TITLE
S3 Bucket User Login doesn't clearly highlight Tower login and password

### ISSUE THREAD

**Issue by tonykay** [ansible/workshops#613]
##### SUMMARY
The stduent login details share the ssh login details, IPs, FQDN etc for the control name and the IP/FQDN for Ansible Tower. 

However, they do not indicate the Tower login and password. 

##### ISSUE TYPE
- Ease of use enhancement

##### COMPONENT NAME
- docs

##### ADDITIONAL INFORMATION

It would reduce friction and enhance ease of use if all the necessary login information could be provided on the landing page/S3 bucket, including the tower login/password combination

**Comment by IPvSean** [comment]
testing fix/enhancements

![picture of login](https://github.com/IPvSean/pictures_for_github/blob/master/example_login.png?raw=true)

**Comment by IPvSean** [comment]
@cloin @liquidat hopefully this looks OK?  Just trying to make this more clear to students....

**Comment by cloin** [comment]
I love it

**Comment by cigamit** [comment]
On the windows workshop we make it so they log in to tower with their student user to prevent this type of confusion.  We use LDAP, but you could just as easily add their student account as an Org Admin (so they can't see the license info) or System Admin.

**Comment by IPvSean** [comment]
@cigamit great idea 
 all workshop variants will now have studentX / password work the same as control node command line like you have on windows 

that should squash this :) . Only reason I am also leaving webpage is
- already finished, no added time for me
- some workshop variants have different tower directions so i can revisit just using the student user for both when i can audit all the variants and see how folks are doing it, some have hardcoded admin directions in like several places

**Comment by IPvSean** [comment]
fixed as part of `devel` branch
