### ISSUE TITLE
Add a link to the GitHub pages rendered version

### ISSUE THREAD

**Issue by cbolz** [ansible/workshops#640]
##### SUMMARY
If someones find the Github repo (e.g. by doing a Google search), there is no link to the GitHub pages rendered version.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- exercises

##### ADDITIONAL INFORMATION
It would be nice to have a link to the GitHub pages rendered version. 
Ideas:
- add a link to the project description
OR
- add a link to the initial README

**Comment by IPvSean** [comment]
finally an easy one 😆

**Comment by IPvSean** [comment]
what about something like this? https://github.com/IPvSean/workshops/tree/gh-pages @cbolz 

checkout the readme.md file or https://ipvsean.github.io/workshops/

**Comment by cbolz** [comment]
looks good enough for me

**Comment by IPvSean** [comment]
@cloin or @liquidat what do you think of this?  Just so people who end up on github can find the ansible.github.io page faster?  THoughts?  The main problem is that it shows up on the webpage itself as well.... is this a big deal?

**Comment by IPvSean** [comment]
ping @cloin

**Comment by cloin** [comment]
I don’t think it’s a big deal and looks fine to me. Worst is somebody gets stuck in a weird click loop for a min.

**Comment by liquidat** [comment]
It's not a big deal, so that would be ok.
My preference would however be to put it directly into the description of the repository. Much like https://github.com/ansible/ansible has two links at the top, to the docs and the main page. We currently have the github URL in the description which is kind of redundant.

**Comment by IPvSean** [comment]
fixed both!  thanks @liquidat @cloin @cbolz
