### ISSUE TITLE
easy defaults for VS Code, open directory for respective workshop 

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#664]
##### SUMMARY

I have been having issues trying to default open a directory so that its clear to the user how VS code works.... I have this thread open->
https://spectrum.chat/theia/general/is-there-a-way-to-launch-and-default-open-a-particular-folder-as-a-workspace~0606c98e-ed88-450b-930e-17a81ceefdcd

want to circle back on this to make user experience easier for students

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
N/A

**Comment by cloin** [comment]
I started looking into this yesterday as well. I'm thinking we could set the default to make the welcome page always open and find where that html is for the welcome page. Then we can template out that page per workshop. That html page has links to recent projects that open the recent projects when clicked so there should be a way to call that out to the student "hey click here to access the workshop files"

**Comment by cloin** [comment]
Boom. I'll probably just change the URL to open coder directly to the workshop directory. This is what I'll do for the windows workshop: https://student1-code.win-test1.rhdemo.io/?folder=vscode-remote%3A%2F%2Fstudent1-code.win-test1.rhdemo.io%2Fhome%2Fstudent1%2Fwindows-workshop

**Comment by IPvSean** [comment]
looking forward to your PR so I can copy it

**Comment by cloin** [comment]
This is what I've managed to do

![image](https://user-images.githubusercontent.com/8515817/73474996-89bb6280-435d-11ea-852c-cb7960c05f5b.png)

**Comment by IPvSean** [comment]
SEND THE PR, I want it

**Comment by IPvSean** [comment]
![nice](https://media0.giphy.com/media/IUZtGhVO8hZ6w/giphy.gif)

**Comment by IPvSean** [comment]
so this is done right?

**Comment by cloin** [comment]
This is done right.
