### ISSUE TITLE
code-server extensions not installed

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#665]
##### SUMMARY

`code-server` extensions are not being installed. There's something blocking it and I think it's an upstream issue. Extensions must be manually placed in the extensions dir `/home/student1/.local/share/code-server/extensions` and then installed with `/opt/code-server --install-extension *.vsix`

https://github.com/ansible/workshops/blob/0a4e7814e7dfe4375eb834f8034f4ea8b0ed7ac7/provisioner/roles/code_server/tasks/codeserver.yml#L42

##### ISSUE TYPE

 - Bug Report

**Comment by IPvSean** [comment]
can this issue be closed? @cloin
