### ISSUE TITLE
RHEL Workshop does NOT include solution & answer playbooks

### ISSUE THREAD

**Issue by gdykeman** [ansible/workshops#672]
@IPvSean 
RHEL Workshop currently does not include the answer playbooks.

**Comment by AugustasV** [comment]
Why it should be? I could see expected output, you just try to do it until you got desired output.

**Comment by rhcreynold** [comment]
@AugustasV they are used for several reasons. So the instructor doesn't have to keep a copy and can use it during the walkthrough of the exercise.  Also when running these for super large groups (50+) sometimes you have to keep timing and people can use them as catchup.

**Comment by liquidat** [comment]
In the security workshop we provide at least some of the playbooks to test the environment if it behaves as expected.
So, my suggestion: let's write those - and write them in a way that we can include them in testing.

**Comment by liquidat** [comment]
Also, we should carefully track what happens in #734 - a progress tracker would even be better.

**Comment by liquidat** [comment]
@gdykeman Where would you like to have the solutions? Would a sub-directory be ok? That is how it is done in the security workshop. Currently, with PR #760 the solutions are placed right in the directory itself which can lead to problems with the rendering of the github pages, see #772

**Comment by IPvSean** [comment]
I think i have most of these now with this release https://github.com/ansible/workshops/pull/878

please re-open the bug with a specific exercise I missed

answers are stored into `rhel-workshop` directory in the student's home directory for the relevant exercise
