### ISSUE TITLE
broke aws_check_setup : make sure workshop_type is set to a correct value

### ISSUE THREAD

**Issue by rhcreynold** [ansible/workshops#674]
`
TASK [aws_check_setup : make sure workshop_type is set to a correct value] *************************************************************************************************************************************
fatal: [localhost]: FAILED! =>
  msg: Incorrect type for fail_msg or msg, expected string and got <type 'list'>`

**Comment by cloin** [comment]
Hey Chris. What branch are you on? Post your extra vars please.

**Comment by rhcreynold** [comment]
fixed, needed to use a version of ansible that was newer than 2.8
