### ISSUE TITLE
Missing Ansible Best Practices Deck on https://ansible.github.io/workshops/

### ISSUE THREAD

**Issue by nqb** [ansible/workshops#685]
##### SUMMARY
Ansible Best Practices Deck is missing from https://ansible.github.io/workshops/ but file is available in this github repository.

**Comment by liquidat** [comment]
It is linked here:
https://ansible.github.io/workshops/exercises/ansible_rhel/

The link you provided is for the different workshops - the best practice is provided as part of the RHEL workshop. Does that make sense?

**Comment by nqb** [comment]
Hello @liquidat,

I got it. From my point of view, it makes mor sense to add it on first page of https://ansible.github.io/workshops/ to make it more visible.

It's a really interesting document.

**Comment by liquidat** [comment]
Personally, since we want to limit the material here to what is really needed in the workshops, I would actually remove it. The deck is available in multiple other places.
However, that is my opinion - @cloin, what do you think?

**Comment by nqb** [comment]
> Personally, since we want to limit the material here to what is really needed in the workshops, I would actually remove it.

Personnally, I lead some Ansible workshops and best practices is **always** what students want to know. From my point of view, it makes sense to keep it here.

> The deck is available in multiple other places.

Could you provide some links ?

**Comment by cloin** [comment]
@liquidat to me I think it comes down to partner access. The decks here are exported to pdf each week or two and then committed to the repo here. If we remove it the pdf, we probably remove partner access to that resource. I haven't personally used this deck in a workshop, though I could see it being useful. I just don't think we have a good way to know how this resource is being used by outside resources. Otherwise, I'd probably vote to remove it and just make the resource known to internal people.

**Comment by liquidat** [comment]
Ok, I stand corrected. We can leave it in and add it to the documentation part. @nqb care to make a PR?

> Could you provide some links ?
Sure. The content is based on the [upstream best practices documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html). The slide deck is regularly presented across the globe, and thus often available via the events. You can also [get it from my speaker hub profile](https://speakerhub.com/sites/default/files/Ansible-Best-Practices.pdf). A maybe even better version from Tim Appnel is available as well, split up into the two parts [essentials](https://www.ansible.com/hubfs/2018_Content/AA%20BOS%202018%20Slides/Ansible%20Best%20Practices.pdf) and [roles & modules](https://www.ansible.com/hubfs/2018_Content/Ansible%20Best%20Practices%20Roles%20&%20Modules.pdf).

**Comment by nqb** [comment]
Hello @liquidat,

So my proposal is to add a dedicated sections on first page of https://ansible.github.io/workshops/  called "Best practices" and provide links to:
- current PDF in this repo or link to your speakerhub profile
- @tima's PDF

Let me know if it's good for you and I will open a PR. Otherwise, could you propose a solution ?

Thanks.

**Comment by IPvSean** [comment]
@cloin what are your thoughts?

My thoughts are I am fine with adding best practices link to the top page... but I don't really want to link to speakerhub.  I would rather link to ansible.com or redhat.com or keep this repo self-contained.

**Comment by cloin** [comment]
No strong opinions from me. I don’t think it makes sense to link to external resources outside of the domains we are associated with though.

**Comment by liquidat** [comment]
OK - so @nqb, how about you do a PR for this? Then we can work on that.
If that is not an option for you right now I can do it.

**Comment by IPvSean** [comment]
what is plan here @nqb

**Comment by IPvSean** [comment]
@liquidat is this something you want to follow-up on?

**Comment by liquidat** [comment]
@IPvSean Let's wait a few more days for a PR; if we don't get a PR, we just keep things like they are right now and close this issue.

**Comment by nqb** [comment]
Hi @IPvSean and @liquidat,

Sorry for my late reply, I will be able to work on this issue next friday.

**Comment by ffirg** [comment]
I've put in PR https://github.com/ansible/workshops/pull/1069 to address this short-term. Points to the public latest docs.

**Comment by IPvSean** [comment]
merged! closing issue, sorry for late rely, doing some cleanup
