### ISSUE TITLE
AnsibleSecurity-QRadarCE not available

### ISSUE THREAD

**Issue by lucalann** [ansible/workshops#707]
Hi,
In security workshop, the ansible fails to find AnsibleSecurity-QRadarCE image on aws. (Also in other region isn't available).
Can we resolve in some way? We prepared an ami image from IBM ova, but how we have to configure it to be Ansible ready (user access ,key)? 
Thanks in advance ,
Luca

**Comment by liquidat** [comment]
@lucalann I am very sorry, I somehow missed this.
The QRadar image is currently a custom image we need to built. We can provide it to you but need your AWS account ID for that. Also, please keep in mind that we only support few major regions with that.

Besides, @maxamillion, do we currently have a complete re-usable built documentation for this image?

**Comment by maxamillion** [comment]
@liquidat I followed IBM's QRadar CE documentation for install on a RHEL 7.5 EUS image and created a custom AWS image out of that following the Amazon documentation on the topic. If we could get permission to open that image to the public I would love to but at this time it would unfortunately violate the QRadar EULA. I had looked into making an Ansible playbook to perform the install but the QRadar installer is an interactive cli run inside GNU screen so I'm not really sure what reasonable options there are there.

**Comment by liquidat** [comment]
@maxamillion Just to get the documentation together - you mean [this QRadar documentation](https://developer.ibm.com/qradar/wp-content/uploads/sites/89/2020/02/b_qradar_community_edition_7.3.3GA_v1.0.pdf)?
And [this AWS documentation](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html)?

**Comment by pseguel-redhat** [comment]
Hi @liquidat can you share the image with me? 
Should  I post the AWS account id here?

**Comment by liquidat** [comment]
@pseguel-redhat Please reach out to me via liquidat@redhat.com and we will take it from there.

**Comment by IPvSean** [comment]
please reopen if there is an issue
