### ISSUE TITLE
Issue with table in github pages

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#711]
##### SUMMARY

master doc for exercise 1 step 3 of windows workshop looks fine but github page tables is messed up. 

<img width="675" alt="image" src="https://user-images.githubusercontent.com/8515817/75462538-6979c600-5952-11ea-822a-aaf75078130b.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/8515817/75462522-61218b00-5952-11ea-9427-92d2b7b97d9d.png">

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by bpayton** [comment]
I think this can be fixed by adding a blank line after the markdown table and before "SCM UPDATE OPTIONS".

**Comment by IPvSean** [comment]
Is this fixed ?

**Comment by bpayton** [comment]
It looks like this was fixed in this commit https://github.com/ansible/workshops/commit/7d8726f5eda8a10568880b05caf92cf7f942ab38#diff-9877e9645e27c21fd840cf38ff673de0.
