### ISSUE TITLE
Fail if code-server is not deployed properly

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#718]
##### SUMMARY

Currently if the code-server deployment fails for whatever reason, the workshop is deployed nevertheless.
However, since all exercises are now migrated to teach the students to access the environments via code-server, this should be a hard dependency: the workshop should fail if the code-server is not deployed properly.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- provisioner

**Comment by IPvSean** [comment]
this has been added, please re-open if you are still having issues
