### ISSUE TITLE
ServiceNow demo 2 does not close out ticket

### ISSUE THREAD

**Issue by bpayton** [ansible/workshops#729]
##### SUMMARY

When running the Closed Loop Incident Management SNOW demo https://github.com/ansible/workshops/tree/master/demos/servicenow/2-closed_loop_incident_mgmt#running-the-demo, it makes it to Step 5 and successfully updates the banner, but it never closes the ticket in ServiceNow. This is because Tower never receives the "INC" variable from ServiceNow. This is because the job template does not have Extra Variables set to "PROMP ON LAUNCH" in the Tower UI.

This can be fixed by adding "ask_extra_vars: yes"  to https://github.com/ansible/workshops/blob/7cbd8da98d554d4d0c06d84732d80c2f394913e2/demos/servicenow/2-closed_loop_incident_mgmt/demo_setup.yml#L84 This will ensure the PROMPT ON LAUNCH box is checked when the template is generated by demo_setup.yml.

##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Used the networking workshop environment from RHPDS.

**Comment by IPvSean** [comment]
@termlen0 do you still use this demo?

@cloin anything we can recycle here or should I go ahead and deprecate this old demo or wait until your new one is up?

**Comment by termlen0** [comment]
I do use this demo. Used it even last week. It still works as described
