### ISSUE TITLE
Port skylight progress checker

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#734]
##### SUMMARY

Skylight has a way to report back student progress that would be beneficial to include especially to facilitate remote delivery of windows workshop.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- provisioner

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ffirg** [comment]
I suggested something like this a while back: https://github.com/ansible/workshops/issues/435
We used to use it in workshops. Would be easy to add grafana etc into the provisioner and would require a student step/task to be run at the end of every exercise

**Comment by cloin** [comment]
Closing. See #435
