### ISSUE TITLE
match f5 workshop to rhel workshop nomenclature 

### ISSUE THREAD

**Issue by IPvSean** [ansible/workshops#741]
##### SUMMARY

minor changes for f5 workshop to match the rhel workshop type

- Change host1 to node1
- Change host2 to node2
- Change group webservers to web

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
this will allow demos to work on F5 workbench as well-> https://github.com/ansible/product-demos

**Comment by IPvSean** [comment]
still need to fix screenshots and diagrams

**Comment by IPvSean** [comment]
@payalsin this is mostly done now

**Comment by senpot** [comment]
I found a problem. Several playbook expect 'webservers' in F5 Exercise 4.2 and 4.3.
Because we use playbook in https://github.com/f5devcentral/ansible-tower-workshop-examples.
For example:
- create_node.yml
- create_pool.yml
- create_vs.yml
- disable_node.yml
- enable_node.yml

**Comment by IPvSean** [comment]
@senpot that is not my repo, need to open an issue with @payalsin and @ericzji

**Comment by senpot** [comment]
@IPvSean I’m sorry that I don’t know rule. I closed that pull request in https://github.com/f5devcentral/ansible-tower-workshop-examples
