### ISSUE TITLE
Security provisioner is not idempotent

### ISSUE THREAD

**Issue by liquidat** [ansible/workshops#746]
##### SUMMARY

Currently the provisioner for the security workshop is not idempotent. If it fails somewhere along the line and is restarted, most likely the setup will not work afterwards.

This is most likely due to the interfaces management of the Check Point setup with the additional interfaces. Needs to be investigated and fixed.

##### ISSUE TYPE

 - Bug Report

**Comment by IPvSean** [comment]
is this fixed now @craig-br ?

**Comment by liquidat** [comment]
@IPvSean is right, @craig-br , is this fixed?

![](https://media4.giphy.com/media/QBd2kLB5qDmysEXre9/giphy.gif?cid=ecf05e470hm1jg1r89tnc3pyn1rzx2ilsoj7h5mlfrf6903o&rid=giphy.gif&ct=g)

**Comment by IPvSean** [comment]
closing this due to lack of urgency
