### ISSUE TITLE
Workshops page that assigns student numbers

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#750]
##### SUMMARY

This is implemented in skylight. The idea is to have a page where a student inputs email address and receives a student number. This makes it easier to assign numbers to students and helps in delivery workshops virtually/remote. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- provisioner

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by cloin** [comment]
Trying to figure out if there’s a way to host just some simple js or php page to prompt for email and spit out a link like in #751 without duplicating numbers and recording what email is associated with which student. Trying to do it as simply as possible.

**Comment by IPvSean** [comment]
any update on this?
![waiting](https://media1.tenor.com/images/aa574640b0f3e2c22a4798233212e35d/tenor.gif?itemid=13052487)

**Comment by IPvSean** [comment]
![still waiting](https://media3.giphy.com/media/l0HlBO7eyXzSZkJri/giphy.gif)

**Comment by liquidat** [comment]
@goetzrieger Just so that you are aware of, @cloin is working on something here.

**Comment by goetzrieger** [comment]
Important initiative, but this can become pretty complex. But we need something like this... back in the day with Ravello and RHPDS Pat Rutledge wrote a tool called GUIDGrabber we used at lots of conferences. Lot's of Python cgi's, but worked.

**Comment by liquidat** [comment]
![giphy](https://user-images.githubusercontent.com/1998084/80035519-75b47680-84f0-11ea-8678-6963ad2166bc.gif)

**Comment by IPvSean** [comment]
![where is it?](https://static.carthrottle.com/workspace/uploads/memes/grjpscp-541bfbe71daab.gif)

cc @liquidat

**Comment by IPvSean** [comment]
![just waiting around](https://cdn.dribbble.com/users/149398/screenshots/4143720/023-perrin.gif)

**Comment by liquidat** [comment]
![giphy](https://user-images.githubusercontent.com/1998084/80488970-7705f900-895f-11ea-9ee9-252174be0577.gif)

**Comment by goetzrieger** [comment]
![yoda](https://user-images.githubusercontent.com/10989245/80494583-1aa6d780-8967-11ea-87a8-bfe690f1f46b.gif)

**Comment by abenokraitis** [comment]
https://media1.giphy.com/media/3PWpklqhHbkyY/source.gif

**Comment by abenokraitis** [comment]
![minions](https://user-images.githubusercontent.com/16416990/80496063-aeac7b00-8936-11ea-878a-6418c2faf4b1.gif)

**Comment by IPvSean** [comment]
![the waiting place](https://www.reactiongifs.com/r/waiting.gif)

**Comment by goetzrieger** [comment]
![image](https://user-images.githubusercontent.com/10989245/80791553-4d80e380-8b92-11ea-9a2a-69c87c813ae7.png)

**Comment by goetzrieger** [comment]
![giphy (1)](https://user-images.githubusercontent.com/10989245/80792007-a2712980-8b93-11ea-9550-12e5fa47003f.gif)

**Comment by IPvSean** [comment]
![just waiting](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

**Comment by liquidat** [comment]
![giphy](https://user-images.githubusercontent.com/1998084/80970214-15400600-8e1b-11ea-83f4-e9482939f088.gif)

**Comment by IPvSean** [comment]
![just waiting around](https://viralviralvideos.com/wp-content/uploads/GIF/2014/12/Waiting-GIF-2015.gif)

**Comment by IPvSean** [comment]
![crab time](https://media3.giphy.com/media/13uaMxgBhGP9ba/giphy.gif)

**Comment by IPvSean** [comment]
![so bored right now](https://media.giphy.com/media/RGXvVUUdks40M/giphy.gif)

**Comment by liquidat** [comment]
![Seymour-Waits-For-Fry-To-Come-Back-For-Him-On-Saddest-Moment-In-Futurama-History](https://user-images.githubusercontent.com/1998084/81454586-f7610100-918c-11ea-8283-47b127447c9e.gif)

**Comment by cigamit** [comment]
![giphy](https://user-images.githubusercontent.com/957322/81462343-764b3f00-9177-11ea-98fa-4d08f0f3b2bd.gif)

**Comment by IPvSean** [comment]
finally, we merged this into `devel` https://github.com/ansible/workshops/pull/829

**Comment by goetzrieger** [comment]
This is sad... I had so many more GIFs lined-up...
![giphy (1)](https://user-images.githubusercontent.com/10989245/81536786-63e62680-936c-11ea-8e57-bba8573c136c.gif)
