### ISSUE TITLE
7 different Issues within the Ansible Lab "Linux Automation" (Attached as PDF)

### ISSUE THREAD

**Issue by tux1980** [ansible/workshops#797]
[Lab Errors.pdf](https://github.com/ansible/workshops/files/4521586/Lab.Errors.pdf)

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by IPvSean** [comment]
this is amazing, I got them all fixed but one where I need to sync with @goetzrieger

**Comment by IPvSean** [comment]
@liquidat UGHH i just added your stuff to my PR, sorry about that

**Comment by IPvSean** [comment]
Fixed with https://github.com/ansible/workshops/pull/800
