### ISSUE TITLE
Some ideas regarding the "attendance" feature

### ISSUE THREAD

**Issue by goetzrieger** [ansible/workshops#857]
##### SUMMARY
I've tested the attendance feature @cloin implemented, it looks great and is something we definitely need for events, esp when delivered virtually. Here's just some thoughts to make it even more useful.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
Some things to make it even more useful IMHO:

- Have a switch to disable showing the "header" information (links to lab guides, slide decks, Worskhop Resource") on the landing page, in my experience this mostly distracts students when run in a classroom-like session.
-  Disable or password protect the main http://WORKSHOP.rhdemo.io page
- Having a check box in RHPDS to enable this feature.

**Comment by cigamit** [comment]
The attendance page is made to be a direct replacement for the default main page, which is why it shows the same material.

We had planned to move the page  from "login" directly to the main page in the future once more people bought in on the idea.

**Comment by cloin** [comment]
re: RHPDS, this is actually turned on by default so all RHPDS provisions have the login page.

**Comment by goetzrieger** [comment]
This issue is slightly dated, so some of this has been addressed (RHPDS default). We have used the attendance feature a good number of times now in Ansible Workshops and it proved to be solid and very helpful. Thanks again for creating it!

I'd still like being able to disable the "header information" completely when running in person/virtual workshops because all the information students need comes from me then. And the other links like to the presos are just distracting folks.

But again, minor stuff, I'm happy as is! 

I'm fine to close this then.

**Comment by goetzrieger** [comment]
Just thinking out loud, couldn't we just have a checkbox on the "admin page" to disable viewing the information and links in the upper part of the site? PHP not being my strong side...

**Comment by cloin** [comment]
PHP, you say? That sounds like a @cigamit question! On a related note, I know that @liquidat was looking at removing some links (putty? and something else) from the header to clean up the page.

**Comment by cigamit** [comment]
We could probably also change the look of the display so that everything else doesn't unnecessarily take up so much of the screen real estate.   Could probably move the login info above everything else if that would help.

**Comment by liquidat** [comment]
I like @cigamit's idea to put the login data further up!
And I would remove putty and the license page, since we usually deploy with license.

**Comment by goetzrieger** [comment]
+1, easy win

I'd actually only keep the link to the exercises and maybe the deck. But IMHO Putty, license, template tester, regex tool can go. Students just start to get distracted with these other things.

**Comment by IPvSean** [comment]
Does anyone have a problem with me fully deprecating the old S3 website since we have this feature now? @liquidat @cloin @cigamit @goetzrieger ?

It seems redundant? We literally default `attedance: true` in the `provisioner/group_vars/all/all.yml` so unless you know its there you are just using both....

**Comment by IPvSean** [comment]
also @goetzrieger is this what you were thinking? 
![image](https://user-images.githubusercontent.com/6537680/102937006-353e3b80-4477-11eb-9e57-c71d52641041.png)

just remove the extra stuff and only have exercises and login?  

I can also match the theme to the new one on https://ansible.github.io/workshops and simplify it a bit so it fits better and there is less white space

**Comment by IPvSean** [comment]
@goetzrieger if this passes CI testing, can you give me a 👍  to make sure I am on track to make a happy Goetz for Christmas?

**Comment by goetzrieger** [comment]
Spot on, /me happy! ;)
