### ISSUE TITLE
Make boinc_auth in community_grid role configurable

### ISSUE THREAD

**Issue by dmc5179** [ansible/workshops#887]
##### SUMMARY

Make boinc_auth a configurable value in the community_grid role to enable users to allocate the WU points to an account that they choose.

##### ISSUE TYPE
 - Bug Report

**Comment by dmc5179** [comment]
The default value in the role should be set to annoymous or the ibm grid equivalent.

**Comment by IPvSean** [comment]
>The default value in the role should be set to annoymous or the ibm grid equivalent.

If we just document this why would this matter?  We are not getting paid by IBM Community Grid?  It is already completely configurable.  I can just add additional documentation.  It is a totally optional role to run.

**Comment by dmc5179** [comment]
There are 2 lines in the documentation that even mention the existence of the role which don't even explain what the role is doing. It is on by default and contributing back to a RedHat team. There are absolutely ethical implications of doing so. If, as you say, it doesn't matter, then there should be no issues setting the default to anonymous. The goal is to contribute to the cause. But it isn't as interesting to put out a snap of the grid dashboard showing how much the anonymous team has contributed. It's far more interesting to put out a snap of the dashboard showing how much the RedHatAnsible team has contributed by defaulting the role to on and sending points to their account.

**Comment by IPvSean** [comment]
@dmc5179 there is a blog post here explaining everything publicly on the open internet: https://www.ansible.com/blog/ansible-and-ibm-community-grid

I have also been publicly tweeting the data until we can find another technical solution.

if you look through the release PRs you see the release notes for every release. 

I think it is disingenuous to use the word ethical here...  The goal is to contribute to the cause but the primary and default contributor is the Red Hat Ansible Team hence why it is the default.  You can easily override that var with extra_vars, see the documentation here: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by dmc5179** [comment]
OK, if you feel that it is clear enough that 2 lines in an extra_vars example to disable the role shows users how to configure the role using an extra_vars file to set a role variable that isn't listed as a variable in the role defaults or vars and defaults to the RedHatAnsible team then I'm good to close this issue.

Defaulting distributed compute points back to your own team when this can be run by anyone, in their own environments, including non RedHat, is absolutely an ethical question. We came to different conclusions regarding the answer.

**Comment by IPvSean** [comment]
@dmc5179 I want to remind you and the community that these points are purely meaningless internet points to help non-profit causes from the IBM Community Grid.  I am simply tracking all the points the "project" is tracking and it is completely configurable.  We can add more documentation but I really confused by the ethical question.  I will wait for others like @cloin and @liquidat to weigh in on this.  Just because you THINK one way doesn't mean that others THINK another way, there is not an absolutes with ethical concerns.  Everything in this repo is 100% open source so I find it really hard to believe that someone would run this Ansible Playbook without investigating what it does.

**Comment by dmc5179** [comment]
@IPvSean It's not meaningless if you put out a tweet showing how much you've contributed with your team name on the top.

If it were meaningless you'd have defaulted to anonymous which is what we did in the F@H effort. Because you're right, they are meaningless. But the tweets suggest perhaps they are not meaningless to everyone.

**Comment by abenokraitis** [comment]
> > The default value in the role should be set to annoymous or the ibm grid equivalent.
> 
> If we just document this why would this matter? We are not getting paid by IBM Community Grid? It is already completely configurable. I can just add additional documentation. It is a totally optional role to run.

+1 to this

**Comment by IPvSean** [comment]
>@IPvSean It's not meaningless if you put out a tweet showing how much you've contributed with your team name on the top.

![sigh](https://media.tenor.com/images/d8fcca857e34afac73069fb02c5b5b0b/tenor.gif)

I would have hoped that all IBMers and Red Hatters, our partners and community would be happy we are trying.  Sorry that we tried to contribute to make the world a better place.

**Comment by dmc5179** [comment]
> > @IPvSean It's not meaningless if you put out a tweet showing how much you've contributed with your team name on the top.
> 
> ![sigh](https://camo.githubusercontent.com/af720f36df938a403e2d5bc2ea9f9cd9b5d836d2/68747470733a2f2f6d656469612e74656e6f722e636f6d2f696d616765732f64386663636138353765333461666163373330363966623032633562356230622f74656e6f722e676966)
> 
> I would have hoped that all IBMers and Red Hatters, our partners and community would be happy we are trying. Sorry that we tried to contribute to make the world a better place.

Hahahaha, that's awesome. I've questioned why you would default the points to your account and not anonymous. And why you would have almost no documentation in the repo about the role. And your response is childish; clearly you don't want to help the world.

The F@H team has done more to help the Covid effort than this team. We've worked directly with the team that runs the entire effort. We've watched as the team has scrambled up the leader board. You know what we didn't do? Default points to our own account:

https://stats.foldingathome.org/team/11812

We also don't waste time setting boinc to run on t2/t3 instances which have to be the worst instances to run these jobs on.

I've learned a great deal here today. About what some people think is ethical and what some people's response to disagreement. The fact that your team thinks this is ok and the fact that RedHat legal ok'd it is impressive. Though I give RH legal a pass. I doubt defaulting to your account was presented to them

**Comment by cloin** [comment]
What's the exchange rate between IBM points and Schrute bucks?

**Comment by dmc5179** [comment]
@IPvSean I also love that Sean refuses to address the inefficiency of running CPU based WUs at all, let alone running them on t2/t3 instances. You know how many points you get from running 24 cores on FAH CPU WUs is for several days, like 12000. In the same time GPUs get millions of points. So when you look at the Points Per Day (PPD) and the Watts per Point (WPP) you find that CPU compute is so bad that essentially you'd contribute more to the Covid cause if you went outside and burned a barrel of paper.

**Comment by rhenshall** [comment]
@dmc5179 I think that's enough now, I'm unsure what point is being made now so suggest the back and forth stops

**Comment by liquidat** [comment]
As discussed, we chose a different approach. Right now all the configuration can be easily turned off. But we are always open for improvements, and if a configurable boinc_auth is requested by the community, why not.

Do you happen to be willing to work on a PR here? My time is limited right now so this has a low priority right now for me.

**Comment by IPvSean** [comment]
more info added here, you can see this now on my fork: https://ipvsean.github.io/workshops/provisioner/#ibm-community-grid
