### ISSUE TITLE
Update the provisioner README with more details about the IBM Grid Role

### ISSUE THREAD

**Issue by dmc5179** [ansible/workshops#888]
##### SUMMARY

The provisioner documentation appears to have a single reference to the ibm_community_grid role in the same extra_vars.yml file. There doesn't appear to be any other documentation about the role or what it does.

https://github.com/ansible/workshops/tree/devel/provisioner

##### ISSUE TYPE
- Documentation Report

**Comment by liquidat** [comment]
Hi @dmc5179, we would be happy to have more documentation, for sure. We are open for PRs, are you interested in contributing? I would be happy to co-work on documentation, but my time is limited.
