### ISSUE TITLE
Demo mode: windows passwords not added to inventory

### ISSUE THREAD

**Issue by cloin** [ansible/workshops#898]
##### SUMMARY

Windows workshop doesn't send a default pw, just gets it from ec2 after instance creation. Demo mode doesn't account for this somewhere.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/8515817/83581509-feb9c700-a50c-11ea-9977-4ff3ee4b5dfb.png">

##### ISSUE TYPE

 - Bug Report

**Comment by cigamit** [comment]
That's all normally imported from the student inventory, so we may want to start checking there when in demo mode.

This brings up another topic though, in the Windows workshop exercise 1, we have the users create a "Machine Credential" and they will then apply it to all their future playbook runs / adhocs runs.  It currently isn't actually being used though (its a student account which doesn't exist on the host) and we are overriding it with the host vars as your screenshot shows.   We may instead want to set the password on these hosts and remove it from the inventory and create the student accounts on the hosts.
