### ISSUE TITLE
Translate Ansible Security Automation into Japanese

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/workshops#910]
##### SUMMARY

Translate Ansible Security Automation into Japanese like other exercises.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- exercises

**Comment by IPvSean** [comment]
hey @hiyokotaisa is this complete? can I close this issue?  Thank you so much for all the hard work.

**Comment by hiyokotaisa** [comment]
@IPvSean I will close this issue since the translation has been merged. Thank you for letting me know!
