### ISSUE TITLE
F5 Ansible Workshop Documentation vs Tower pre-populated configuration discrepancies

### ISSUE THREAD

**Issue by tarexveff** [ansible/workshops#913]
##### SUMMARY
I found numerous discrepancies between what the F5 Ansible workshop documentation states and what the provisioner pushes to the Tower instances.

##### ISSUE TYPE
 - Bug Report

##### Notes
**Exercise 4.0**

Step 2:  

- Documentation states “Demo Inventory” but the inventory in Tower is called “Workshop Inventory”

Step 3:  

- Documentation states “Demo Project,” but the project in Tower is called “Ansible official demo project”

Step 4:  

- Documentation states “Demo Credential,” but there are two credentials in Tower:
  - Tower Credential
  - Workshop Credential:  This is a machine credential, but it is an SSH key credential, not a password credential like the documentation states.

Step 5:  

- Documentation states “Demo Job Template,” but the template pre-populated in Tower is called “INFRASTRUCTURE / Turn off IBM Community Grid”

**Exercise 4.1**

Step 1

- The Workshop Credential already exists in Tower, and is an SSH key credential versus the password credential that the documentation tells the student to create.

- The documentation suggests that the Workshop Credential password should be “ansible,” however, the password specified will never be “ansible,” since the workshop provisioner prevents this.  Documentation should refer the student to their self-registration page for the password.

Step 2

- The Workshop Inventory already exists in Tower.
- The “webservers” group is named “web” in Tower.

  
Step 3

- The “Workshop Credential” pre-populated in Tower will not work, per corrections in Step 1 above.

**Comment by IPvSean** [comment]
fixed in `devel`

the credential installed by default will just "work" with the f5 appliance, no need to have the student setup the credential
