### ISSUE TITLE
Where is the page where instructor can view student number assignments?

### ISSUE THREAD

**Issue by dpullman-emergent** [ansible/workshops#918]
##### SUMMARY

I've provisioned a workshop with the attendance feature and we see the url for the Auto-Assignment website. Where is the page for the instructor to check the student assignments?

"a page where instructor can view student number assignments and name + email association."

Thanks!

##### ISSUE TYPE
- Documentation Report

**Comment by cigamit** [comment]
Goto list.php and enter the workshop password.

**Comment by dpullman-emergent** [comment]
Jimmy,

Thanks very much. That works.

Just to reiterate: to get to the instructor page for the attendance feature, if your workshop is myworkshop.rhdemo.io, then browse to login.myworkshop.rhdemo.io/list.php and enter the workshop password.

Thanks again!
