### ISSUE TITLE
workshops/decks/ansible_windows.pdf slide #47 variable precedence

### ISSUE THREAD

**Issue by marktonneson** [ansible/workshops#922]
##### SUMMARY

Slide #47 Variable precedence the second column numbering repeats column one
 

I created my own edited version, feel free to copy-paste from here -- https://docs.google.com/presentation/d/1QjIIb5lZbWc2gaPZYNfh2_ED3hu6-FdTkKpXVYYKA9g/edit#slide=id.g75f72e5ca6_0_19

##### ISSUE TYPE
- Documentation Report

**Comment by marktonneson** [comment]
Also there are a number of reference notation [1] [2] [3] [4] that do not have actual references or links, so they become irrelevant.

**Comment by cigamit** [comment]
I have fixed the numbering in the Google Deck now.

> Also there are a number of reference notation [1] [2] [3] [4] that do not have actual references or links, so they become irrelevant.

In the Google deck the references are actually links, that basically point the associated footnotes here.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#id15
We seem to lose that when converting to PDF, so probably should remove them.

**Comment by IPvSean** [comment]
@cigamit did you change the PDF as well?

**Comment by cigamit** [comment]
Yes, the numbering is fixed in the pdf.  The links still don't resolve, but that is a different issue.  Feel free to close this.
