### ISSUE TITLE
Windows workshop Ad-Hoc exercise #2

### ISSUE THREAD

**Issue by marktonneson** [ansible/workshops#923]
##### SUMMARY

The documentation for Exercise #2 Ad-Hoc Commands instructs the student to use the "Windows Workshop Inventory"  however the most recent workshop deployment (as of June 17) only has a "Workshop Inventory" defined.  Wasn't sure whether to file as a documentation bug [e.g. use "Workshop Inventory" and select "windows" group] or if the "fix" should be on the deployment.

##### ISSUE TYPE
- Documentation Report

**Comment by IPvSean** [comment]
fixed on `devel` branch, you can see the fixes on my fork here: http://ipvsean.github.io/workshops
