### ISSUE TITLE
workshops/decks/ansible_windows.pdf repeat slides #12 & #16

### ISSUE THREAD

**Issue by marktonneson** [ansible/workshops#924]
##### SUMMARY

Slides 12 & 16 "Ansible automates technologies you use" are identical.  Probably don't need both.

##### ISSUE TYPE
- Documentation Report

**Comment by cigamit** [comment]
I already fixed this a few weeks ago in the Google slide deck, we just haven't exported it and committed it to the repo.

**Comment by IPvSean** [comment]
has this been fixed in the PDF? @cloin @cigamit

**Comment by cigamit** [comment]
Yes, this has been fixed in the PDF
