### ISSUE TITLE
Missing Links for the supplemental exercises 

### ISSUE THREAD

**Issue by tux1980** [ansible/workshops#942]
##### SUMMARY
Hi! All the Links for the supplemental exercises are going into /dev/null obviously. Please have the links point to the right destinations. Right now we are getting error "404, not found"

Example:
https://github.com/ansible/workshops/blob/devel/exercises/ansible_network/supplemental/exercises/2-0-config 

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by IPvSean** [comment]
back from parental leave, let me investigate

**Comment by IPvSean** [comment]
i think I have a fix, waiting on some CI testing to complete.  In the meantime you can see the exercises by using the github navigation here: https://github.com/ansible/workshops/tree/devel/exercises/ansible_network/supplemental

**Comment by IPvSean** [comment]
fixed in `devel` branch, you can see render working on my fork https://ipvsean.github.io/workshops/exercises/ansible_network/supplemental/
