### ISSUE TITLE
Network workshop needs tcp port 8888 open to the control node

### ISSUE THREAD

**Issue by mlowcher61** [ansible/workshops#945]
##### SUMMARY
When you run the network_report.yml playbook it creates a website with the statistics from the switch/routers. The webpage is at tcp port 8888. I have verified that the content is there by doing a curl command from the Tower instance ssh session. The security group in AWS is not allowing tcp port 8888.
I tried deploying the workshop from my laptop rather than RHPDS. I ran into the same issue. I was then able to add tcp port 8888 as allowed to my security group and the page was then reachable.

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE
N/A

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

This is happening from an RHPDS deployment as well as by cloning the repo and running it myself.

##### PLAYBOOK SHORT OUTPUT

The playbook finishes without issue. It's just not configured to open tcp port 8888 to the Tower device.
```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by cigamit** [comment]
Would it make more sense to change this port to 8080, which is already open via the security rules?  Several of the other workshop exercises use that port, so to me, it would make sense to standardize on it across all of the workshops.

**Comment by IPvSean** [comment]
ugh we can't use 8080 b/c we use that for vscode

**Comment by cigamit** [comment]
Ya, I would just leave it at 8888, and just mark it as a network port in the defaults

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/tower_workshop/pull/11
