### ISSUE TITLE
Ansible for Windows Automation not creating workshop folder

### ISSUE THREAD

**Issue by open-sudo** [ansible/workshops#969]
##### SUMMARY

I created the  "Ansible for Windows Automation" workshop twice. Both times the following folder was missing:

1) workshop_project is not created in gitlab
2) workshop_project is not created in control node

I am not able to provide environment variables because SSH is not provided. The terminal is not opening from the VS Code. The error message VS Code throws is: The terminal shell CWD: "/home/student1/windows-project/workshop_project" does not exist.

**Comment by cloin** [comment]
Fixed on devel. Thanks for the issue!
