### ISSUE TITLE
Ansible Windows Automation - pre-made "workshop_project" not available

### ISSUE THREAD

**Issue by tux1980** [ansible/workshops#978]
Hi!

in the Workshop "Ansible Automation", there is expected a pre-made Project in Gitlab (Step1, the first Chapter) to import it later on in Tower. Unfortunately, the Gitlab is empty. Not a single Playbook or role. So, without the pre-fabricate Gitlab Project "workshop_project" I can't continue the Lab. 

Challenge is, in one week I have to carry out this very Workshop in front of several partners. So, without having solved that beforehand I would have to cancel that workshop. 
Might that be solved in the short-term?

regards
Wolfgang Marx
Red Hat

**Comment by cloin** [comment]
This has been fixed in this repo for a couple weeks. However, GPTE have forked the repo and haven't applied the fix. Please reach out rhpds admins. Feel free to get in touch with me over email if you need the address.
